// Generated by `cargo xtask registry` from crates/km43/protocol.toml.
// Do not edit. A number lives in one place or two people allocate it twice.
// registry-digest: 06e88cc1d931d3ca

/**
 * The high bit means *response to a request*. `Event` is the only unsolicited
 * message.
 */
export enum MessageType {
  /**
   * The `Discover` request. Auth `none`. Unauthenticated: no key exists yet
   * (P-054). Answered by {@link MessageType.DiscoverResponse}. Since 1.0.
   */
  Discover = 0x0,
  /**
   * The answer to {@link MessageType.Discover}. Auth `none`. Unauthenticated:
   * no key exists yet (P-054). Since 1.0.
   */
  DiscoverResponse = 0x80,
  /**
   * The `Hello` request. Auth `proof`. A proof carried inside the body, so the
   * body is decoded before it verifies. Answered by
   * {@link MessageType.HelloResponse}. Since 1.0.
   */
  Hello = 0x1,
  /**
   * The answer to {@link MessageType.Hello}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   */
  HelloResponse = 0x81,
  /**
   * The `Subscribe` request. Auth `wrq`. Wrapped under `session_key` with the
   * `km43/v1/wrq` label. Read-only, so it carries no counter (P-052). Answered
   * by {@link MessageType.SubscribeResponse}. Since 1.0.
   */
  Subscribe = 0x3,
  /**
   * The answer to {@link MessageType.Subscribe}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   */
  SubscribeResponse = 0x83,
  /**
   * The `Event` message. Auth `evt`. Wrapped under `session_key` with the
   * `km43/v1/evt` label (P-052). Since 1.0.
   */
  EventResponse = 0x4,
  /**
   * The `ReadLog` request. Auth `wrq`. Wrapped under `session_key` with the
   * `km43/v1/wrq` label. Read-only, so it carries no counter (P-052). Answered
   * by {@link MessageType.ReadLogResponse}. Since 1.0.
   */
  ReadLog = 0x5,
  /**
   * The answer to {@link MessageType.ReadLog}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   */
  ReadLogResponse = 0x85,
  /**
   * The `GetConfig` request. Auth `wrq`. Wrapped under `session_key` with the
   * `km43/v1/wrq` label. Read-only, so it carries no counter (P-052). Answered
   * by {@link MessageType.GetConfigResponse}. Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  GetConfig = 0x6,
  /**
   * The answer to {@link MessageType.GetConfig}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  GetConfigResponse = 0x86,
  /**
   * The `SetConfig` request. Auth `signed`. A signed body carrying the client's
   * counter. Every write is one (P-053). Answered by
   * {@link MessageType.SetConfigResponse}. Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  SetConfig = 0x7,
  /**
   * The answer to {@link MessageType.SetConfig}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  SetConfigResponse = 0x87,
  /**
   * The `Command` request. Auth `signed`. A signed body carrying the client's
   * counter. Every write is one (P-053). Answered by
   * {@link MessageType.CommandResponse}. Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  Command = 0x8,
  /**
   * The answer to {@link MessageType.Command}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  CommandResponse = 0x88,
  /**
   * The `Firmware` request. Auth `signed`. A signed body carrying the client's
   * counter. Every write is one (P-053). Answered by
   * {@link MessageType.FirmwareResponse}. Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  Firmware = 0x9,
  /**
   * The answer to {@link MessageType.Firmware}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  FirmwareResponse = 0x89,
  /**
   * The `Time` request. Auth `signed`. A signed body carrying the client's
   * counter. Every write is one (P-053). Answered by
   * {@link MessageType.TimeResponse}. Since 1.0.
   */
  Time = 0xa,
  /**
   * The answer to {@link MessageType.Time}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   */
  TimeResponse = 0x8a,
  /**
   * The `Pair` request. Auth `pair_key`. MAC'd under `pair_key`, derived from
   * the printed secret, because no session exists yet (P-054). Answered by
   * {@link MessageType.PairResponse}. Since 1.0.
   */
  Pair = 0xb,
  /**
   * The answer to {@link MessageType.Pair}. Auth `pair_key`. MAC'd under
   * `pair_key`, derived from the printed secret, because no session exists yet
   * (P-054). Since 1.0.
   */
  PairResponse = 0x8b,
  /**
   * The `Goodbye` request. Auth `wrq`. Wrapped under `session_key` with the
   * `km43/v1/wrq` label. Read-only, so it carries no counter (P-052). Answered
   * by {@link MessageType.GoodbyeResponse}. Since 1.0.
   */
  Goodbye = 0xc,
  /**
   * The answer to {@link MessageType.Goodbye}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   */
  GoodbyeResponse = 0x8c,
  /**
   * The `Inventory` request. Auth `wrq`. Wrapped under `session_key` with the
   * `km43/v1/wrq` label. Read-only, so it carries no counter (P-052). Answered
   * by {@link MessageType.InventoryResponse}. Since 1.0.
   */
  Inventory = 0xd,
  /**
   * The answer to {@link MessageType.Inventory}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   */
  InventoryResponse = 0x8d,
  /**
   * The `Readings` request. Auth `wrq`. Wrapped under `session_key` with the
   * `km43/v1/wrq` label. Read-only, so it carries no counter (P-052). Answered
   * by {@link MessageType.ReadingsResponse}. Since 1.0.
   */
  Readings = 0xe,
  /**
   * The answer to {@link MessageType.Readings}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   */
  ReadingsResponse = 0x8e,
  /**
   * The `Concerns` request. Auth `wrq`. Wrapped under `session_key` with the
   * `km43/v1/wrq` label. Read-only, so it carries no counter (P-052). Answered
   * by {@link MessageType.ConcernsResponse}. Since 1.0.
   */
  Concerns = 0xf,
  /**
   * The answer to {@link MessageType.Concerns}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   */
  ConcernsResponse = 0x8f,
  /**
   * The `History` request. Auth `wrq`. Wrapped under `session_key` with the
   * `km43/v1/wrq` label. Read-only, so it carries no counter (P-052). Answered
   * by {@link MessageType.HistoryResponse}. Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  History = 0x10,
  /**
   * The answer to {@link MessageType.History}. Auth `rsp`. Wrapped under
   * `session_key` with the `km43/v1/rsp` label (P-052). Since 1.0.
   *
   * Reserved: allocated, and not specified yet.
   */
  HistoryResponse = 0x90,
  /**
   * The `Error` message. Auth `rsp_or_bare`. Wrapped with the `km43/v1/rsp`
   * label when the sender holds a session, bare when it does not (P-142). Since
   * 1.0.
   */
  ErrorResponse = 0xff,
}

/**
 * What `Error 0xFF` carries, for a request that never reached its handler. A
 * handler's own refusal is an outcome in its response instead (P-141).
 */
export enum ErrorCode {
  /**
   * Malformed frame. A receiver may also accept it from a bare body. Whether it
   * arrives wrapped is decided by whether the sender holds a session, not by
   * the code (P-142).
   */
  MalformedFrame = 0x1,
  /**
   * Unknown message type. A receiver may also accept it from a bare body.
   * Whether it arrives wrapped is decided by whether the sender holds a
   * session, not by the code (P-142).
   */
  UnknownMessageType = 0x2,
  /**
   * Protocol major mismatch. A receiver may also accept it from a bare body.
   * Whether it arrives wrapped is decided by whether the sender holds a
   * session, not by the code (P-142).
   */
  ProtocolMajorMismatch = 0x3,
  /**
   * Hello required first. A receiver may also accept it from a bare body.
   * Whether it arrives wrapped is decided by whether the sender holds a
   * session, not by the code (P-142).
   */
  HelloRequiredFirst = 0x4,
  /**
   * Payload too large. A receiver may also accept it from a bare body. Whether
   * it arrives wrapped is decided by whether the sender holds a session, not by
   * the code (P-142).
   */
  PayloadTooLarge = 0x5,
  /**
   * Unknown section. A receiver accepts it only inside a MAC'd body, and
   * discards a bare one carrying it (P-051). Whether it arrives wrapped is
   * decided by whether the sender holds a session, not by the code (P-142).
   */
  UnknownSection = 0x6,
  /**
   * Busy — retry. A receiver accepts it only inside a MAC'd body, and discards
   * a bare one carrying it (P-051). Whether it arrives wrapped is decided by
   * whether the sender holds a session, not by the code (P-142).
   */
  BusyRetry = 0x7,
  /**
   * Session table full. A receiver may also accept it from a bare body. Whether
   * it arrives wrapped is decided by whether the sender holds a session, not by
   * the code (P-142).
   */
  SessionTableFull = 0x8,
  /**
   * Session expired. A receiver may also accept it from a bare body. Whether it
   * arrives wrapped is decided by whether the sender holds a session, not by
   * the code (P-142).
   */
  SessionExpired = 0x9,
  /**
   * Bad MAC. A receiver may also accept it from a bare body. Whether it arrives
   * wrapped is decided by whether the sender holds a session, not by the code
   * (P-142).
   */
  BadMAC = 0xa,
  /**
   * Counter not fresh. A receiver accepts it only inside a MAC'd body, and
   * discards a bare one carrying it (P-051). Whether it arrives wrapped is
   * decided by whether the sender holds a session, not by the code (P-142).
   */
  CounterNotFresh = 0xb,
  /**
   * Unknown client. A receiver may also accept it from a bare body. Whether it
   * arrives wrapped is decided by whether the sender holds a session, not by
   * the code (P-142).
   */
  UnknownClient = 0xc,
  /**
   * Stale challenge — reconnect and retry. A receiver may also accept it from a
   * bare body. Whether it arrives wrapped is decided by whether the sender
   * holds a session, not by the code (P-142).
   */
  StaleChallengeReconnectAndRetry = 0xe,
  /**
   * Challenge unavailable. A receiver may also accept it from a bare body.
   * Whether it arrives wrapped is decided by whether the sender holds a
   * session, not by the code (P-142).
   */
  ChallengeUnavailable = 0x12,
}

/** How a `Command 0x88` answered. */
export enum Command {
  /** Acted on. */
  Accepted = 0x1,
  /** Refused, `detail` says why. */
  Rejected = 0x2,
  /** Already seen this `cmd_id`; not acted on twice. */
  Duplicate = 0x3,
  /** The selector is at Off, or the generator is not ours. */
  Inhibited = 0x4,
  /** This client may not do this. */
  Unauthorised = 0x5,
  /** Would have been accepted; nothing was actuated. */
  Shadowed = 0x6,
  /**
   * The `rev` the command was composed under is not current, so `dev` and `cmp`
   * may name something else now (P-166).
   *
   * Reserved: allocated, and not specified yet.
   */
  StaleTopology = 0x7,
  /**
   * The target does not list this `kind` in its `cmds` (P-166).
   *
   * Reserved: allocated, and not specified yet.
   */
  WrongTarget = 0x8,
}

/** How a `Concerns 0x8F` answered. */
export enum Concerns {
  /**
   * The request was answered, in whole or in part; an empty table is this and
   * not outcome 3.
   */
  Ok = 0x1,
  /** `rev` is neither 0 nor the controller's current one (P-146). */
  Superseded = 0x2,
  /** `from` is greater than the largest `cid` the table holds. */
  OutOfRange = 0x3,
}

/**
 * How a `Firmware 0x89` answered. **Reserved** — see
 * [DEFERRED.md](https://github.com/origin89hq/km43/blob/main/docs/protocol/DEFERRED.md).
 */
export enum Firmware {
  /**
   * accepted
   *
   * Reserved: allocated, and not specified yet.
   */
  Accepted = 0x1,
  /**
   * bad_offset
   *
   * Reserved: allocated, and not specified yet.
   */
  BadOffset = 0x2,
  /**
   * bad_signature
   *
   * Reserved: allocated, and not specified yet.
   */
  BadSignature = 0x3,
  /**
   * wrong_target
   *
   * Reserved: allocated, and not specified yet.
   */
  WrongTarget = 0x4,
  /**
   * too_large
   *
   * Reserved: allocated, and not specified yet.
   */
  TooLarge = 0x5,
  /**
   * no_transfer_in_progress
   *
   * Reserved: allocated, and not specified yet.
   */
  NoTransferInProgress = 0x6,
  /**
   * not_owner
   *
   * Reserved: allocated, and not specified yet.
   */
  NotOwner = 0x7,
  /**
   * unauthorised
   *
   * Reserved: allocated, and not specified yet.
   */
  Unauthorised = 0x8,
}

/** How a `History 0x90` answered. */
export enum History {
  /**
   * The request was answered, in whole or in part.
   *
   * Reserved: allocated, and not specified yet.
   */
  Ok = 0x1,
  /**
   * `rev` is neither 0 nor the controller's current one (P-146).
   *
   * Reserved: allocated, and not specified yet.
   */
  Superseded = 0x2,
  /**
   * `sig` does not exist at this `rev`.
   *
   * Reserved: allocated, and not specified yet.
   */
  UnknownSignal = 0x3,
  /**
   * The signal exists and its `shape` is 2 `series`.
   *
   * Reserved: allocated, and not specified yet.
   */
  SeriesNotHistorable = 0x4,
  /**
   * The signal exists, is a scalar, and carries no `hist` key.
   *
   * Reserved: allocated, and not specified yet.
   */
  NoHistory = 0x5,
  /**
   * `from` is past the last row the request resolves to.
   *
   * Reserved: allocated, and not specified yet.
   */
  OutOfRange = 0x6,
}

/** How an `Inventory 0x8D` answered. */
export enum Inventory {
  /** The request was answered, in whole or in part. */
  Ok = 0x1,
  /** `rev` is neither 0 nor the controller's current one (P-146). */
  Superseded = 0x2,
  /** `what` is not in 1..5. */
  UnknownKind = 0x3,
  /** `from` is past the last row the request resolves to. */
  OutOfRange = 0x4,
}

/** How a `Pair 0x8B` answered. */
export enum Pair {
  /**
   * The client is enrolled, and `client_id` is the one allocated to it (P-064).
   */
  Enrolled = 0x1,
  /**
   * No pairing window was open. Checked before the proof, so it costs the
   * controller nothing and does not count as an auth failure (P-066).
   */
  WindowClosed = 0x2,
  /**
   * The proof did not verify. It counts against `MAX_AUTH_FAILURES`, and the
   * challenge is spent all the same (P-061).
   */
  BadProof = 0x3,
  /**
   * Eight distinct labels are enrolled and none matched this one. Nothing is
   * evicted (P-067).
   */
  TableFull = 0x4,
  /**
   * The label matched an occupied row byte for byte, and that row was reused:
   * same `client_id`, counter back to 0 (P-078).
   */
  Reclaimed = 0x5,
}

/** How a `Readings 0x8E` answered. */
export enum Readings {
  /** The request was answered, in whole or in part. */
  Ok = 0x1,
  /** `rev` is neither 0 nor the controller's current one (P-146). */
  Superseded = 0x2,
  /**
   * A `Sel` names a `dev`, `cmp` or `sig` that does not exist at this `rev`.
   */
  UnknownSelector = 0x3,
  /** `from` is past the last row the request resolves to. */
  OutOfRange = 0x4,
}

/** How a `SetConfig 0x87` answered. */
export enum SetConfig {
  /** accepted */
  Accepted = 0x1,
  /** stale_version */
  StaleVersion = 0x2,
  /** invalid */
  Invalid = 0x3,
  /** unauthorised */
  Unauthorised = 0x4,
  /** exceeds_cap */
  ExceedsCap = 0x5,
  /**
   * Correct, and applied at the next `MIN_REV_INTERVAL_MS` boundary rather than
   * now (P-154).
   *
   * Reserved: allocated, and not specified yet.
   */
  Staged = 0x9,
}

/** How a `Time 0x8A` answered. */
export enum Time {
  /** The clock moved, and the `time set` record names who moved it (P-111). */
  Accepted = 0x1,
  /**
   * `at` is past the plausibility window's upper edge. The clock did not move
   * (P-113).
   */
  Rejected = 0x2,
  /** This client's capability mask does not let it set the clock (P-105). */
  Unauthorised = 0x3,
  /**
   * `at` is below the monotonic floor. A person at the panel can override it
   * and the client can send it again (P-114, P-116).
   */
  NeedsButton = 0x4,
}

/** The value of metric `0x0603`: why the controller last started. */
export enum BootReason {
  /**
   * Power-on, power-down or brown-out. The controller reports all three with
   * one flag and cannot tell them apart.
   */
  Power = 0x1,
  /** The independent watchdog fired. */
  Watchdog = 0x2,
  /** A reset the image asked for, with no panic before it. */
  SoftwareReset = 0x4,
  /** The image panicked and reset itself. */
  Panic = 0x5,
  /** The reset pin, with no power flag beside it. */
  PinReset = 0x6,
  /**
   * The option bytes reloaded, which is how the controller swaps its image
   * banks.
   */
  OptionByteReload = 0x7,
  /** The window watchdog fired. */
  WindowWatchdog = 0x8,
  /** An illegal entry into a low-power mode. */
  LowPowerEntry = 0x9,
}

/**
 * The three window sizes. They nest exactly — four quarter-hours to an hour,
 * twenty-four hours to a day — so converting between them has no rounding rule.
 */
export enum Bucket {
  /**
   * Coarsest.
   *
   * Reserved: allocated, and not specified yet.
   */
  Day = 0x1,
  /**
   * Four quarter-hours.
   *
   * Reserved: allocated, and not specified yet.
   */
  Hour = 0x2,
  /**
   * Finest. The three nest exactly, which is why P-194's conversion has no
   * rounding rule.
   *
   * Reserved: allocated, and not specified yet.
   */
  QuarterHour = 0x3,
}

/**
 * What a client says it is when it enrols. It is inside the pair proof, and the
 * capability mask is fixed from it (P-105).
 */
export enum ClientKind {
  /** app */
  App = 0x1,
  /** browser */
  Browser = 0x2,
  /** cloud */
  Cloud = 0x3,
  /** cli */
  Cli = 0x4,
}

/**
 * Where a concern is in its life. Acknowledging is not clearing, and only the
 * condition going away clears it.
 */
export enum ConcernState {
  /**
   * The condition is present.
   *
   * Reserved: allocated, and not specified yet.
   */
  Active = 0x1,
  /**
   * Somebody has read it. The condition is still present.
   *
   * Reserved: allocated, and not specified yet.
   */
  ActiveAcked = 0x2,
  /**
   * The condition is gone; the source's latch is not, and will clear on the
   * source's own terms.
   *
   * Reserved: allocated, and not specified yet.
   */
  LatchedCleared = 0x3,
  /**
   * The condition is gone and the source states it cannot reset the latch yet —
   * the difference between *wait* and *drive out*.
   *
   * Reserved: allocated, and not specified yet.
   */
  ClearingBlocked = 0x4,
  /**
   * Over. Terminal, and the only state a row carries as it leaves the table
   * (P-180).
   *
   * Reserved: allocated, and not specified yet.
   */
  Cleared = 0x5,
}

/**
 * Who is deciding, carried as an ordinary signal so *the BMS is driving the
 * charge voltage and we are not* is a reading rather than an inference.
 */
export enum ControlOwner {
  /**
   * The buttons on the device itself.
   *
   * Reserved: allocated, and not specified yet.
   */
  LocalPanel = 0x1,
  /**
   * Origin 89.
   *
   * Reserved: allocated, and not specified yet.
   */
  ThisController = 0x2,
  /**
   * The battery is deciding.
   *
   * Reserved: allocated, and not specified yet.
   */
  Bms = 0x3,
  /**
   * A Victron GX or ESS assistant.
   *
   * Reserved: allocated, and not specified yet.
   */
  GxEss = 0x4,
  /**
   * A person, through this protocol.
   *
   * Reserved: allocated, and not specified yet.
   */
  RemoteClient = 0x5,
  /**
   * The device's own schedule or logic.
   *
   * Reserved: allocated, and not specified yet.
   */
  DeviceAutomation = 0x6,
}

/**
 * Which way is positive, stated on the row rather than assumed from the
 * quantity.
 */
export enum Direction {
  /**
   * Positive flows into the component.
   *
   * Reserved: allocated, and not specified yet.
   */
  PositiveIsIn = 0x1,
  /**
   * Positive flows out of it.
   *
   * Reserved: allocated, and not specified yet.
   */
  PositiveIsOut = 0x2,
  /**
   * Unsigned; the sign carries no meaning.
   *
   * Reserved: allocated, and not specified yet.
   */
  MagnitudeOnly = 0x3,
}

/** The value of metric `0x0601`: where the auto / off / manual selector is. */
export enum GeneratorSelector {
  /** Behaviours may command the generator. */
  Auto = 0x1,
  /**
   * Never command it, for any reason. A behaviour that needs it reports itself
   * `inhibited`.
   */
  Off = 0x2,
  /** The operator is driving. The controller monitors and logs only. */
  Manual = 0x3,
}

/** The value of metric `0x0501`: what the generator is doing. */
export enum GeneratorState {
  /** No AC and our contact open. Autostart may fire. */
  Stopped = 0x1,
  /** Our contact closed, no AC yet. Gives up after the start window. */
  Starting = 0x2,
  /** AC present with our contact closed. Ours, and ours to stop. */
  Running = 0x3,
  /**
   * AC present with our contact **open** — somebody started it with the fob.
   * Not a fault, and never rendered as one.
   */
  RunningNotOurs = 0x4,
  /** Our command was withdrawn and the AC persists. Notify; never retry. */
  StopNotHonoured = 0x5,
  /**
   * Commanded to run and it did not, as many times as the starter is worth. The
   * contact stays open and nothing here will try again until a person clears it
   * — out of fuel, an oil-alert shutdown and a flat start battery are
   * indistinguishable from the controller, and hammering a start line into any
   * of them is wrong.
   */
  GaveUp = 0x6,
}

/**
 * Whether a bucket is the device's own record or one this controller
 * integrated. Per bucket, because a window can span the day the device stopped
 * supplying one.
 */
export enum HistorySource {
  /**
   * The device's own record, on its own axis.
   *
   * Reserved: allocated, and not specified yet.
   */
  DeviceReported = 0x1,
  /**
   * This controller integrated it, including any bucket it aggregated (P-195).
   *
   * Reserved: allocated, and not specified yet.
   */
  ControllerDerived = 0x2,
}

/**
 * Why a history response is shorter than asked for. Evaluated in order, so a
 * response that hits a seam and then an edge names the seam.
 */
export enum HistoryStopReason {
  /**
   * A `DeviceRow.since` boundary: a different instrument.
   *
   * Reserved: allocated, and not specified yet.
   */
  DeviceReplaced = 0x1,
  /**
   * A `ComponentRow.since` boundary: the same instrument, a different meaning.
   *
   * Reserved: allocated, and not specified yet.
   */
  ComponentReassigned = 0x2,
  /**
   * The store holds nothing here and does not claim how wide the hole is.
   *
   * Reserved: allocated, and not specified yet.
   */
  GapInRecord = 0x3,
  /**
   * Past the newest closed bucket.
   *
   * Reserved: allocated, and not specified yet.
   */
  EndOfRecord = 0x4,
  /**
   * Before the oldest bucket held.
   *
   * Reserved: allocated, and not specified yet.
   */
  OlderThanStore = 0x5,
  /**
   * The response reached its byte or point cap.
   *
   * Reserved: allocated, and not specified yet.
   */
  PageFull = 0x6,
}

/** Which of the five descriptor tables a page is paging through. */
export enum InventoryKind {
  /**
   * `BusRow`.
   *
   * Reserved: allocated, and not specified yet.
   */
  Buses = 0x1,
  /**
   * `DeviceRow`.
   *
   * Reserved: allocated, and not specified yet.
   */
  Devices = 0x2,
  /**
   * `ComponentRow`.
   *
   * Reserved: allocated, and not specified yet.
   */
  Components = 0x3,
  /**
   * `SignalRow`.
   *
   * Reserved: allocated, and not specified yet.
   */
  Signals = 0x4,
  /**
   * `ParamRow`.
   *
   * Reserved: allocated, and not specified yet.
   */
  Parameters = 0x5,
}

/**
 * Whether a device is answering. Separate from any of its signals' validity,
 * and it never moves `rev`.
 */
export enum Presence {
  /**
   * Answering.
   *
   * Reserved: allocated, and not specified yet.
   */
  Online = 0x1,
  /**
   * Answering, with errors or omissions.
   *
   * Reserved: allocated, and not specified yet.
   */
  Degraded = 0x2,
  /**
   * Was seen and has stopped answering.
   *
   * Reserved: allocated, and not specified yet.
   */
  Offline = 0x3,
  /**
   * Configured and has never answered.
   *
   * Reserved: allocated, and not specified yet.
   */
  NeverSeen = 0x4,
}

/** Where a number came from. `0` exactly when there is no number at all. */
export enum Provenance {
  /** There is no number. */
  None = 0x0,
  /** Read directly from an instrument. */
  Measured = 0x1,
  /** Integrated or accumulated by the source, and trustworthy as a total. */
  Counted = 0x2,
  /** This controller computed it from other signals. */
  Derived = 0x3,
  /** Inferred from a proxy — state of charge from terminal voltage. */
  Estimated = 0x4,
  /** The device states it: a limit, or a setpoint it says it is honouring. */
  Reported = 0x5,
  /** What was asked for, never what was observed. */
  Commanded = 0x6,
}

/** How far a reading can be trusted, in one word. */
export enum Quality {
  /** Read directly from an instrument. */
  Measured = 0x1,
  /** Integrated or accumulated, and trustworthy as a total. */
  Counted = 0x2,
  /** Derived from something else, e.g. SoC from terminal voltage. */
  Estimated = 0x3,
  /**
   * Was measured, is no longer current: older than its channel's maximum age,
   * or the same reading for so long that the instrument is presumed hung.
   */
  Stale = 0x4,
  /** No reading. **The value key is omitted entirely**. */
  Absent = 0x5,
}

/**
 * How much a concern matters. The table reserves rows above `warning` so
 * per-cell noise cannot hide a pack fault.
 */
export enum Severity {
  /**
   * Worth recording.
   *
   * Reserved: allocated, and not specified yet.
   */
  Info = 0x1,
  /**
   * Worth looking at.
   *
   * Reserved: allocated, and not specified yet.
   */
  Warning = 0x2,
  /**
   * Something is broken.
   *
   * Reserved: allocated, and not specified yet.
   */
  Fault = 0x3,
  /**
   * A source is refusing to operate to protect itself.
   *
   * Reserved: allocated, and not specified yet.
   */
  Protection = 0x4,
}

/**
 * Whether a signal carries one value or `n` of them. The container only — what
 * one value *is* is the value type below.
 */
export enum Shape {
  /**
   * One value.
   *
   * Reserved: allocated, and not specified yet.
   */
  Scalar = 0x1,
  /**
   * `n` values in one signal, addressed by position.
   *
   * Reserved: allocated, and not specified yet.
   */
  Series = 0x2,
}

/**
 * Which window a value describes. The same quantity at `live` and at `max` are
 * two signals, not one signal read twice.
 */
export enum SignalDomain {
  /**
   * What it is now.
   *
   * Reserved: allocated, and not specified yet.
   */
  Live = 0x1,
  /**
   * Since the device was made.
   *
   * Reserved: allocated, and not specified yet.
   */
  Lifetime = 0x2,
  /**
   * Since somebody last cleared it.
   *
   * Reserved: allocated, and not specified yet.
   */
  SinceReset = 0x3,
  /**
   * Since local midnight.
   *
   * Reserved: allocated, and not specified yet.
   */
  Today = 0x4,
  /**
   * The previous whole day.
   *
   * Reserved: allocated, and not specified yet.
   */
  Yesterday = 0x5,
  /**
   * A ceiling the source states it is honouring.
   *
   * Reserved: allocated, and not specified yet.
   */
  LimitUpper = 0x6,
  /**
   * A floor the source states it is honouring.
   *
   * Reserved: allocated, and not specified yet.
   */
  LimitLower = 0x7,
  /**
   * The largest seen over the domain's window.
   *
   * Reserved: allocated, and not specified yet.
   */
  Max = 0x8,
  /**
   * The smallest seen over the domain's window.
   *
   * Reserved: allocated, and not specified yet.
   */
  Min = 0x9,
}

/** Who set the clock, recorded as `source` in the `time set` event (P-111). */
export enum TimeSource {
  /** A signed `Time` write from an enrolled client. */
  Client = 0x1,
  /** A `TimeOffer` the controller accepted from the comms processor. */
  NtpViaComms = 0x2,
}

/**
 * Why `rev` moved. There is deliberately no *capability changed* value: a
 * signal a unit does not implement is published at validity 4, so it becoming
 * available is a validity change and not a topology change.
 */
export enum TopologyChangeReason {
  /**
   * First inventory after a restart.
   *
   * Reserved: allocated, and not specified yet.
   */
  Boot = 0x1,
  /**
   * An operator wrote topology.
   *
   * Reserved: allocated, and not specified yet.
   */
  ConfigWrite = 0x2,
  /**
   * A module answered and was taken into the tables.
   *
   * Reserved: allocated, and not specified yet.
   */
  SubDeviceAdopted = 0x3,
  /**
   * A module was taken out of them.
   *
   * Reserved: allocated, and not specified yet.
   */
  SubDeviceRemoved = 0x4,
  /**
   * The instrument behind a row changed (P-156).
   *
   * Reserved: allocated, and not specified yet.
   */
  DeviceReplaced = 0x5,
}

/**
 * What a port physically is. `rs485`, `can` and `ip` are the addressed ones,
 * which is what makes `DeviceRow.addr` required on them and meaningless on the
 * rest.
 */
export enum Transport {
  /**
   * A two-wire multidrop serial bus; `addr` is required on it (P-189).
   *
   * Reserved: allocated, and not specified yet.
   */
  Rs485 = 0x1,
  /**
   * CAN, where a device is addressed by node id.
   *
   * Reserved: allocated, and not specified yet.
   */
  Can = 0x2,
  /**
   * Victron's point-to-point serial; one device per port, so no address.
   *
   * Reserved: allocated, and not specified yet.
   */
  VeDirect = 0x3,
  /**
   * The controller's own inputs and outputs.
   *
   * Reserved: allocated, and not specified yet.
   */
  LocalIo = 0x4,
  /**
   * Ethernet or Wi-Fi, addressed by host.
   *
   * Reserved: allocated, and not specified yet.
   */
  Ip = 0x5,
  /**
   * 1-Wire, addressed by ROM id.
   *
   * Reserved: allocated, and not specified yet.
   */
  Onewire = 0x6,
  /**
   * Inside the controller; nothing physical to unplug.
   *
   * Reserved: allocated, and not specified yet.
   */
  Internal = 0x7,
}

/**
 * What a vendor kind is measured in. Standard kinds carry their unit in the
 * metric table; a vendor kind carries it on the row, and needs a number to
 * carry.
 */
export enum Unit {
  /**
   * V.
   *
   * Reserved: allocated, and not specified yet.
   */
  Volt = 0x1,
  /**
   * A.
   *
   * Reserved: allocated, and not specified yet.
   */
  Ampere = 0x2,
  /**
   * W.
   *
   * Reserved: allocated, and not specified yet.
   */
  Watt = 0x3,
  /**
   * Wh.
   *
   * Reserved: allocated, and not specified yet.
   */
  WattHour = 0x4,
  /**
   * Ah.
   *
   * Reserved: allocated, and not specified yet.
   */
  AmpereHour = 0x5,
  /**
   * °C.
   *
   * Reserved: allocated, and not specified yet.
   */
  DegreeCelsius = 0x6,
  /**
   * %.
   *
   * Reserved: allocated, and not specified yet.
   */
  Percent = 0x7,
  /**
   * Hz.
   *
   * Reserved: allocated, and not specified yet.
   */
  Hertz = 0x8,
  /**
   * s.
   *
   * Reserved: allocated, and not specified yet.
   */
  Second = 0x9,
  /**
   * min.
   *
   * Reserved: allocated, and not specified yet.
   */
  Minute = 0xa,
  /**
   * h.
   *
   * Reserved: allocated, and not specified yet.
   */
  Hour = 0xb,
  /**
   * a plain tally.
   *
   * Reserved: allocated, and not specified yet.
   */
  Count = 0xc,
  /**
   * Ω.
   *
   * Reserved: allocated, and not specified yet.
   */
  Ohm = 0xd,
  /**
   * Pa.
   *
   * Reserved: allocated, and not specified yet.
   */
  Pascal = 0xe,
  /**
   * L.
   *
   * Reserved: allocated, and not specified yet.
   */
  Litre = 0xf,
  /**
   * a number with no unit — an enum or a flags word.
   *
   * Reserved: allocated, and not specified yet.
   */
  None = 0x10,
}

/**
 * Whether a number is usable now. Separated from provenance because `counted`
 * **and** `stale` is a real state and one word could not say it.
 */
export enum Validity {
  /** Current. */
  Ok = 0x1,
  /** Was good; the value is the last known and `age` says how old. */
  Stale = 0x2,
  /** The source is up and has not produced a first reading. */
  Initialising = 0x3,
  /**
   * This device does not implement it, including a vendor's in-band absence
   * pattern (P-176).
   */
  Unsupported = 0x4,
  /** The source reports it bad, or the reply did not arrive intact. */
  SensorFault = 0x5,
  /**
   * A number arrived and was refused: impossible here, or outside `i32` at the
   * registry's scale (P-185).
   */
  OutOfRange = 0x6,
  /** The component or device is not present. */
  Absent = 0x7,
  /** The source reported an operating state we have no value for (P-164). */
  UnnamedState = 0x8,
}

/**
 * What a single value is, independent of how many there are. Splitting this
 * from the shape is what lets a series of flags exist: sixteen per-cell
 * balancing bits are one signal, not sixteen.
 */
export enum Vtype {
  /**
   * A quantity that moves in both directions.
   *
   * Reserved: allocated, and not specified yet.
   */
  Gauge = 0x1,
  /**
   * A running total. It never reverses, which is why a coarse history bucket
   * takes the last constituent and not their sum (P-195).
   *
   * Reserved: allocated, and not specified yet.
   */
  Counter = 0x2,
  /**
   * One member of the space named by `esp`.
   *
   * Reserved: allocated, and not specified yet.
   */
  Enum = 0x3,
  /**
   * A bitmask over the space named by `esp`; member m is bit m − 1 (P-186).
   *
   * Reserved: allocated, and not specified yet.
   */
  Flags = 0x4,
}

/**
 * Returned in the Hello response. A bit set means the controller can do the
 * thing; a client must not assume an unset bit is a failure, only an absence.
 */
export enum CapabilityBit {
  /** event log readable */
  EventLogReadable = 0x0,
  /** configuration writable */
  ConfigurationWritable = 0x1,
  /**
   * commands accepted
   *
   * Reserved: allocated, and not specified yet.
   */
  CommandsAccepted = 0x2,
  /**
   * firmware update accepted
   *
   * Reserved: allocated, and not specified yet.
   */
  FirmwareUpdateAccepted = 0x3,
  /** clock settable by client */
  ClockSettableByClient = 0x4,
  /** counted state of charge available */
  CountedStateOfChargeAvailable = 0x5,
  /** AC metering on the generator */
  ACMeteringOnTheGenerator = 0x6,
  /** any behaviour is in shadow mode */
  AnyBehaviourIsInShadowMode = 0x7,
}

/**
 * **Reserved, not specified.** No actuation until a controller is granted
 * authority over an output — see
 * [DEFERRED.md](https://github.com/origin89hq/km43/blob/main/docs/protocol/DEFERRED.md).
 * The space is allocated now so that nothing squats on it in the meantime.
 */
export enum CommandKind {
  /**
   * start generator
   *
   * Reserved: allocated, and not specified yet.
   */
  StartGenerator = 0x101,
  /**
   * stop generator
   *
   * Reserved: allocated, and not specified yet.
   */
  StopGenerator = 0x102,
  /**
   * run exercise cycle now
   *
   * Reserved: allocated, and not specified yet.
   */
  RunExerciseCycleNow = 0x103,
  /**
   * set output
   *
   * Reserved: allocated, and not specified yet.
   */
  SetOutput = 0x201,
  /**
   * acknowledge concern
   *
   * Reserved: allocated, and not specified yet.
   */
  AcknowledgeConcern = 0x203,
  /**
   * clear override
   *
   * Reserved: allocated, and not specified yet.
   */
  ClearOverride = 0x301,
}

/**
 * Which part of the configuration a `GetConfig` or `SetConfig` names in its
 * `section` key.
 */
export enum ConfigSection {
  /**
   * identity and site
   *
   * Reserved: allocated, and not specified yet.
   */
  IdentityAndSite = 0x1,
  /**
   * channels
   *
   * Reserved: allocated, and not specified yet.
   */
  Channels = 0x2,
  /**
   * buses and devices
   *
   * Reserved: allocated, and not specified yet.
   */
  BusesAndDevices = 0x3,
  /**
   * generator behaviour
   *
   * Reserved: allocated, and not specified yet.
   */
  GeneratorBehaviour = 0x10,
  /**
   * frost behaviour
   *
   * Reserved: allocated, and not specified yet.
   */
  FrostBehaviour = 0x11,
  /**
   * schedule behaviour
   *
   * Reserved: allocated, and not specified yet.
   */
  ScheduleBehaviour = 0x12,
  /**
   * load-shed behaviour
   *
   * Reserved: allocated, and not specified yet.
   */
  LoadShedBehaviour = 0x13,
  /**
   * network
   *
   * Reserved: allocated, and not specified yet.
   */
  Network = 0x20,
  /**
   * cloud
   *
   * Reserved: allocated, and not specified yet.
   */
  Cloud = 0x21,
}

/**
 * Errors on the link between the controller and its comms processor, numbered
 * from 256 so a client can tell *the link failed* from *your request failed*.
 */
export enum LinkErrorCode {
  /**
   * Unknown link-local opcode, or one sent from the wrong side. It never
   * appears in a client-facing frame (L-180).
   */
  WrongSide = 0x100,
  /**
   * Link-local type on a client transport. It reaches the client whose frame
   * raised it (L-180).
   */
  LinkTypeOnClientTransport = 0x101,
  /**
   * Client frame before LinkUp completed. It reaches the client whose frame
   * raised it (L-180).
   */
  BeforeLinkUp = 0x102,
  /**
   * Unknown connection handle. It reaches the client whose frame raised it
   * (L-180).
   */
  UnknownHandle = 0x103,
  /**
   * Connection table full. It never appears in a client-facing frame (L-180).
   */
  ConnectionTableFull = 0x104,
  /**
   * Link protocol major mismatch. It never appears in a client-facing frame
   * (L-180).
   */
  LinkMajorMismatch = 0x105,
  /**
   * Too many outstanding link-local requests. It never appears in a
   * client-facing frame (L-180).
   */
  TooManyOutstanding = 0x106,
  /**
   * Link-local type with a non-zero session. It never appears in a
   * client-facing frame (L-180).
   */
  NonZeroSession = 0x107,
  /**
   * No authorisation matches this image. It never appears in a client-facing
   * frame (L-180).
   */
  NoAuthorisation = 0x108,
}

/**
 * A per-client bitfield, fixed at enrolment from `client_kind` and stored in
 * FRAM beside that client's counter. **P-105 in
 * [PROTOCOL.md](https://github.com/origin89hq/km43/blob/main/docs/PROTOCOL.md)
 * is the rule** — where the mask comes from, why `client_kind` is a sound input
 * where `transport` is not, that no message raises or lowers one, and what each
 * refusal is answered with. This file allocates the bits and the row each
 * `client_kind` is handed.
 */
export const ClientCapability = {
  /** The client may write configuration at all. */
  WRITE_CONFIG: 1 << 0,
  /**
   * The client may write the **network** (`0x0020`) and **cloud** (`0x0021`)
   * sections.
   */
  WRITE_NETWORK_AND_CLOUD: 1 << 1,
  /** The client may send `Command 0x08`. */
  SEND_COMMAND: 1 << 2,
  /** The client may set the clock with `Time 0x0A`. */
  SET_CLOCK: 1 << 3,
  /** The client may push firmware with `Firmware 0x09`. */
  PUSH_FIRMWARE: 1 << 4,
} as const;

/**
 * Every metric carries a **unit** and a **scale**, and the value on the wire is
 * an integer. There is no FPU on the target, and a scaled integer cannot
 * disagree with itself the way a float rounded by two languages can.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const MetricKind = {
  /** DC voltage. Unit `V`, `value = raw × 10^-3`. */
  DC_VOLTAGE: 0x0101,
  /** DC current (+ into the component). Unit `A`, `value = raw × 10^-3`. */
  DC_CURRENT: 0x0102,
  /** DC power (signed). Unit `W`, `value = raw × 10^-1`. */
  DC_POWER: 0x0103,
  /** State of charge. Unit `%`, `value = raw × 10^-1`. */
  STATE_OF_CHARGE: 0x0104,
  /** AC voltage. Unit `V`, `value = raw × 10^-1`. */
  AC_VOLTAGE: 0x0201,
  /** AC current. Unit `A`, `value = raw × 10^-3`. */
  AC_CURRENT: 0x0202,
  /** AC power. Unit `W`, `value = raw × 10^-1`. */
  AC_POWER: 0x0203,
  /** AC frequency. Unit `Hz`, `value = raw × 10^-2`. */
  AC_FREQUENCY: 0x0204,
  /** AC energy. Unit `Wh`. */
  AC_ENERGY: 0x0205,
  /**
   * AC energy imported. Unit `Wh`.
   *
   * Reserved: allocated, and not specified yet.
   */
  AC_ENERGY_IMPORTED: 0x0206,
  /**
   * AC energy exported. Unit `Wh`.
   *
   * Reserved: allocated, and not specified yet.
   */
  AC_ENERGY_EXPORTED: 0x0207,
  /** Temperature. Unit `°C`, `value = raw × 10^-1`. */
  TEMPERATURE: 0x0302,
  /** Tank level. Unit `%`, `value = raw × 10^-1`. */
  TANK_LEVEL: 0x0401,
  /** Tank sender current. Unit `A`, `value = raw × 10^-6`. */
  TANK_SENDER_CURRENT: 0x0402,
  /** Generator state (enum, see below). No unit. */
  GENERATOR_STATE: 0x0501,
  /** Generator run hours. Unit `h`, `value = raw × 10^-2`. */
  GENERATOR_RUN_HOURS: 0x0502,
  /** Generator starts since commissioning. Unit `count`. */
  GENERATOR_STARTS_SINCE_COMMISSIONING: 0x0503,
  /** Run contact commanded (bool). No unit. */
  RUN_CONTACT_COMMANDED: 0x0504,
  /** Generator selector position (enum, see below). No unit. */
  GENERATOR_SELECTOR_POSITION: 0x0601,
  /** Uptime since boot. Unit `s`. */
  UPTIME_SINCE_BOOT: 0x0602,
  /** Last boot reason (enum). No unit. */
  LAST_BOOT_REASON: 0x0603,
  /** Log ring utilisation. Unit `%`, `value = raw × 10^-1`. */
  LOG_RING_UTILISATION: 0x0604,
  /**
   * Time in bulk. Unit `min`.
   *
   * Reserved: allocated, and not specified yet.
   */
  TIME_IN_BULK: 0x0701,
  /**
   * Time in absorption. Unit `min`.
   *
   * Reserved: allocated, and not specified yet.
   */
  TIME_IN_ABSORPTION: 0x0702,
  /**
   * Time in float. Unit `min`.
   *
   * Reserved: allocated, and not specified yet.
   */
  TIME_IN_FLOAT: 0x0703,
} as const;

/**
 * What an `Event` or a `LogEntry` records, in its `kind` key.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const EventKind = {
  /**
   * Signal validity changed. Class A: never dropped, not from the log and not
   * from a queue.
   */
  SIGNAL_VALIDITY_CHANGED: 0x0102,
  /**
   * Generator state changed. Class A: never dropped, not from the log and not
   * from a queue.
   *
   * Reserved: allocated, and not specified yet.
   */
  GENERATOR_STATE_CHANGED: 0x0201,
  /**
   * Generator command withdrawn. Class A: never dropped, not from the log and
   * not from a queue.
   *
   * Reserved: allocated, and not specified yet.
   */
  GENERATOR_COMMAND_WITHDRAWN: 0x0202,
  /**
   * Generator stop not honoured. Class A: never dropped, not from the log and
   * not from a queue.
   *
   * Reserved: allocated, and not specified yet.
   */
  GENERATOR_STOP_NOT_HONOURED: 0x0203,
  /**
   * Behaviour decision (shadow or applied). Class A: never dropped, not from
   * the log and not from a queue.
   *
   * Reserved: allocated, and not specified yet.
   */
  BEHAVIOUR_DECISION: 0x0301,
  /**
   * Behaviour inhibited. Class A: never dropped, not from the log and not from
   * a queue.
   *
   * Reserved: allocated, and not specified yet.
   */
  BEHAVIOUR_INHIBITED: 0x0302,
  /**
   * Output changed. Class A: never dropped, not from the log and not from a
   * queue.
   *
   * Reserved: allocated, and not specified yet.
   */
  OUTPUT_CHANGED: 0x0401,
  /**
   * Concern raised. Class A: never dropped, not from the log and not from a
   * queue.
   */
  CONCERN_RAISED: 0x0501,
  /**
   * Concern changed. Class A: never dropped, not from the log and not from a
   * queue.
   */
  CONCERN_CHANGED: 0x0502,
  /** Boot. Class A: never dropped, not from the log and not from a queue. */
  BOOT: 0x0601,
  /**
   * Config changed. Class A: never dropped, not from the log and not from a
   * queue.
   *
   * Reserved: allocated, and not specified yet.
   */
  CONFIG_CHANGED: 0x0602,
  /**
   * Client enrolled. Class A: never dropped, not from the log and not from a
   * queue.
   *
   * Reserved: allocated, and not specified yet.
   */
  CLIENT_ENROLLED: 0x0603,
  /**
   * Time set. Class A: never dropped, not from the log and not from a queue.
   */
  TIME_SET: 0x0604,
  /**
   * Records dropped. Class A: never dropped, not from the log and not from a
   * queue.
   *
   * Reserved: allocated, and not specified yet.
   */
  RECORDS_DROPPED: 0x0701,
  /**
   * Record failed CRC. Class A: never dropped, not from the log and not from a
   * queue.
   */
  RECORD_FAILED_CRC: 0x0702,
  /**
   * Comms link lost. Class A: never dropped, not from the log and not from a
   * queue.
   */
  COMMS_LINK_LOST: 0x0801,
  /**
   * Comms power cycled. Class A: never dropped, not from the log and not from a
   * queue.
   */
  COMMS_POWER_CYCLED: 0x0802,
  /**
   * Comms unrecoverable. Class A: never dropped, not from the log and not from
   * a queue.
   */
  COMMS_UNRECOVERABLE: 0x0803,
  /**
   * Sessions shed for backpressure. Class A: never dropped, not from the log
   * and not from a queue.
   */
  SESSIONS_SHED_FOR_BACKPRESSURE: 0x0804,
  /**
   * Comms boot noise. Class A: never dropped, not from the log and not from a
   * queue.
   */
  COMMS_BOOT_NOISE: 0x0805,
  /**
   * Topology changed. Class A: never dropped, not from the log and not from a
   * queue.
   */
  TOPOLOGY_CHANGED: 0x0901,
  /**
   * Device presence changed. Class A: never dropped, not from the log and not
   * from a queue.
   */
  DEVICE_PRESENCE_CHANGED: 0x0902,
} as const;

/**
 * What a component is. Open: a role nobody has allocated renders under its
 * number rather than blanking the row around it.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const ComponentRole = {
  /**
   * pv array
   *
   * Reserved: allocated, and not specified yet.
   */
  PV_ARRAY: 0x0001,
  /**
   * mppt tracker
   *
   * Reserved: allocated, and not specified yet.
   */
  MPPT_TRACKER: 0x0002,
  /**
   * battery bank
   *
   * Reserved: allocated, and not specified yet.
   */
  BATTERY_BANK: 0x0003,
  /**
   * battery pack
   *
   * Reserved: allocated, and not specified yet.
   */
  BATTERY_PACK: 0x0004,
  /**
   * heater
   *
   * Reserved: allocated, and not specified yet.
   */
  HEATER: 0x0005,
  /**
   * contactor
   *
   * Reserved: allocated, and not specified yet.
   */
  CONTACTOR: 0x0006,
  /**
   * fet
   *
   * Reserved: allocated, and not specified yet.
   */
  FET: 0x0007,
  /**
   * ac input
   *
   * Reserved: allocated, and not specified yet.
   */
  AC_INPUT: 0x0008,
  /**
   * ac output
   *
   * Reserved: allocated, and not specified yet.
   */
  AC_OUTPUT: 0x0009,
  /**
   * phase
   *
   * Reserved: allocated, and not specified yet.
   */
  PHASE: 0x000a,
  /**
   * line pair
   *
   * Reserved: allocated, and not specified yet.
   */
  LINE_PAIR: 0x000b,
  /**
   * dc output
   *
   * Reserved: allocated, and not specified yet.
   */
  DC_OUTPUT: 0x000c,
  /**
   * load output
   *
   * Reserved: allocated, and not specified yet.
   */
  LOAD_OUTPUT: 0x000d,
  /**
   * start battery
   *
   * Reserved: allocated, and not specified yet.
   */
  START_BATTERY: 0x000e,
  /**
   * meter
   *
   * Reserved: allocated, and not specified yet.
   */
  METER: 0x000f,
  /**
   * circuit
   *
   * Reserved: allocated, and not specified yet.
   */
  CIRCUIT: 0x0010,
  /**
   * merged circuit
   *
   * Reserved: allocated, and not specified yet.
   */
  MERGED_CIRCUIT: 0x0011,
  /**
   * transfer relay
   *
   * Reserved: allocated, and not specified yet.
   */
  TRANSFER_RELAY: 0x0012,
  /**
   * inverter
   *
   * Reserved: allocated, and not specified yet.
   */
  INVERTER: 0x0013,
  /**
   * charger
   *
   * Reserved: allocated, and not specified yet.
   */
  CHARGER: 0x0014,
  /**
   * probe
   *
   * Reserved: allocated, and not specified yet.
   */
  PROBE: 0x0015,
  /**
   * tank
   *
   * Reserved: allocated, and not specified yet.
   */
  TANK: 0x0016,
  /**
   * cell
   *
   * Reserved: allocated, and not specified yet.
   */
  CELL: 0x0017,
  /**
   * relay
   *
   * Reserved: allocated, and not specified yet.
   */
  RELAY: 0x0018,
  /**
   * generator
   *
   * Reserved: allocated, and not specified yet.
   */
  GENERATOR: 0x0019,
} as const;

/**
 * A normalized thing that has gone wrong. Open, so a condition nobody has
 * allocated still renders as a sentence somebody can act on.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const Condition = {
  /**
   * over voltage
   *
   * Reserved: allocated, and not specified yet.
   */
  OVER_VOLTAGE: 0x0001,
  /**
   * under voltage
   *
   * Reserved: allocated, and not specified yet.
   */
  UNDER_VOLTAGE: 0x0002,
  /**
   * over temperature
   *
   * Reserved: allocated, and not specified yet.
   */
  OVER_TEMPERATURE: 0x0003,
  /**
   * under temperature
   *
   * Reserved: allocated, and not specified yet.
   */
  UNDER_TEMPERATURE: 0x0004,
  /**
   * charge over current
   *
   * Reserved: allocated, and not specified yet.
   */
  CHARGE_OVER_CURRENT: 0x0005,
  /**
   * discharge over current
   *
   * Reserved: allocated, and not specified yet.
   */
  DISCHARGE_OVER_CURRENT: 0x0006,
  /**
   * short circuit
   *
   * Reserved: allocated, and not specified yet.
   */
  SHORT_CIRCUIT: 0x0007,
  /**
   * overload
   *
   * Reserved: allocated, and not specified yet.
   */
  OVERLOAD: 0x0008,
  /**
   * cell imbalance
   *
   * Reserved: allocated, and not specified yet.
   */
  CELL_IMBALANCE: 0x0009,
  /**
   * low state of charge
   *
   * Reserved: allocated, and not specified yet.
   */
  LOW_STATE_OF_CHARGE: 0x000a,
  /**
   * charge inhibited
   *
   * Reserved: allocated, and not specified yet.
   */
  CHARGE_INHIBITED: 0x000b,
  /**
   * discharge inhibited
   *
   * Reserved: allocated, and not specified yet.
   */
  DISCHARGE_INHIBITED: 0x000c,
  /**
   * unnamed state
   *
   * Reserved: allocated, and not specified yet.
   */
  UNNAMED_STATE: 0x000d,
  /**
   * registration refused
   *
   * Reserved: allocated, and not specified yet.
   */
  REGISTRATION_REFUSED: 0x000e,
  /**
   * series too long
   *
   * Reserved: allocated, and not specified yet.
   */
  SERIES_TOO_LONG: 0x000f,
  /**
   * inventory full
   *
   * Reserved: allocated, and not specified yet.
   */
  INVENTORY_FULL: 0x0010,
  /**
   * bay flapping
   *
   * Reserved: allocated, and not specified yet.
   */
  BAY_FLAPPING: 0x0011,
  /**
   * counter write failed
   *
   * Reserved: allocated, and not specified yet.
   */
  COUNTER_WRITE_FAILED: 0x0012,
  /**
   * epoch write failed
   *
   * Reserved: allocated, and not specified yet.
   */
  EPOCH_WRITE_FAILED: 0x0013,
  /**
   * clock stepped
   *
   * Reserved: allocated, and not specified yet.
   */
  CLOCK_STEPPED: 0x0014,
  /**
   * floor overridden
   *
   * Reserved: allocated, and not specified yet.
   */
  FLOOR_OVERRIDDEN: 0x0015,
} as const;

/**
 * What a whole enclosure is. Open, on the same terms.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const DeviceRole = {
  /**
   * solar charger
   *
   * Reserved: allocated, and not specified yet.
   */
  SOLAR_CHARGER: 0x0001,
  /**
   * inverter
   *
   * Reserved: allocated, and not specified yet.
   */
  INVERTER: 0x0002,
  /**
   * inverter charger
   *
   * Reserved: allocated, and not specified yet.
   */
  INVERTER_CHARGER: 0x0003,
  /**
   * bms
   *
   * Reserved: allocated, and not specified yet.
   */
  BMS: 0x0004,
  /**
   * energy meter
   *
   * Reserved: allocated, and not specified yet.
   */
  ENERGY_METER: 0x0005,
  /**
   * shunt
   *
   * Reserved: allocated, and not specified yet.
   */
  SHUNT: 0x0006,
  /**
   * sensor
   *
   * Reserved: allocated, and not specified yet.
   */
  SENSOR: 0x0007,
  /**
   * power module
   *
   * Reserved: allocated, and not specified yet.
   */
  POWER_MODULE: 0x0008,
  /**
   * controller
   *
   * Reserved: allocated, and not specified yet.
   */
  CONTROLLER: 0x0009,
  /**
   * battery monitor
   *
   * Reserved: allocated, and not specified yet.
   */
  BATTERY_MONITOR: 0x000a,
  /**
   * temperature sensor
   *
   * Reserved: allocated, and not specified yet.
   */
  TEMPERATURE_SENSOR: 0x000b,
} as const;

/**
 * A protocol dialect the controller can speak. A dialect is distinct when its
 * framing or register model differs, not when a vendor ships a second model.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const Dialect = {
  /**
   * no protocol
   *
   * Reserved: allocated, and not specified yet.
   */
  NO_PROTOCOL: 0x0001,
  /**
   * pzem dc
   *
   * Reserved: allocated, and not specified yet.
   */
  PZEM_DC: 0x0002,
  /**
   * epever b
   *
   * Reserved: allocated, and not specified yet.
   */
  EPEVER_B: 0x0003,
  /**
   * victron mppt rs hex
   *
   * Reserved: allocated, and not specified yet.
   */
  VICTRON_MPPT_RS_HEX: 0x0004,
  /**
   * victron gx modbus vebus
   *
   * Reserved: allocated, and not specified yet.
   */
  VICTRON_GX_MODBUS_VEBUS: 0x0005,
  /**
   * eg4 lifepower4 serial
   *
   * Reserved: allocated, and not specified yet.
   */
  EG4_LIFEPOWER4_SERIAL: 0x0006,
  /**
   * morningstar sunsaver duo
   *
   * Reserved: allocated, and not specified yet.
   */
  MORNINGSTAR_SUNSAVER_DUO: 0x0007,
  /**
   * emporia vue3 esphome i2c
   *
   * Reserved: allocated, and not specified yet.
   */
  EMPORIA_VUE3_ESPHOME_I2C: 0x0008,
  /**
   * ecoflow power kits
   *
   * Reserved: allocated, and not specified yet.
   */
  ECOFLOW_POWER_KITS: 0x0009,
} as const;

/**
 * The spaces a `SignalRow` can point `esp` at. This is the registry of
 * registries, and it is what lets a client learn a value is a charge stage from
 * the descriptor.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const EnumSpace = {
  /**
   * presence
   *
   * Reserved: allocated, and not specified yet.
   */
  PRESENCE: 0x0001,
  /**
   * control owner
   *
   * Reserved: allocated, and not specified yet.
   */
  CONTROL_OWNER: 0x0002,
  /**
   * generator state
   *
   * Reserved: allocated, and not specified yet.
   */
  GENERATOR_STATE: 0x0003,
  /**
   * generator selector
   *
   * Reserved: allocated, and not specified yet.
   */
  GENERATOR_SELECTOR: 0x0004,
  /**
   * boot reason
   *
   * Reserved: allocated, and not specified yet.
   */
  BOOT_REASON: 0x0005,
  /**
   * charge stage
   *
   * Reserved: allocated, and not specified yet.
   */
  CHARGE_STAGE: 0x0006,
  /**
   * balancing
   *
   * Reserved: allocated, and not specified yet.
   */
  BALANCING: 0x0007,
} as const;

/**
 * Where a quantity is measured. Never a charge stage — a stage duration is a
 * quantity and lives in the metric table.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const MeasurementPoint = {
  /**
   * line to neutral
   *
   * Reserved: allocated, and not specified yet.
   */
  LINE_TO_NEUTRAL: 0x0001,
  /**
   * line to line
   *
   * Reserved: allocated, and not specified yet.
   */
  LINE_TO_LINE: 0x0002,
  /**
   * terminal
   *
   * Reserved: allocated, and not specified yet.
   */
  TERMINAL: 0x0003,
  /**
   * cell
   *
   * Reserved: allocated, and not specified yet.
   */
  CELL: 0x0004,
  /**
   * internal
   *
   * Reserved: allocated, and not specified yet.
   */
  INTERNAL: 0x0005,
  /**
   * ambient
   *
   * Reserved: allocated, and not specified yet.
   */
  AMBIENT: 0x0006,
  /**
   * heatsink
   *
   * Reserved: allocated, and not specified yet.
   */
  HEATSINK: 0x0007,
  /**
   * case
   *
   * Reserved: allocated, and not specified yet.
   */
  CASE: 0x0008,
  /**
   * inlet
   *
   * Reserved: allocated, and not specified yet.
   */
  INLET: 0x0009,
  /**
   * outlet
   *
   * Reserved: allocated, and not specified yet.
   */
  OUTLET: 0x000a,
  /**
   * transformer
   *
   * Reserved: allocated, and not specified yet.
   */
  TRANSFORMER: 0x000b,
} as const;

/**
 * A product this controller has a driver for. Open, and a vendor range is
 * expected to carry most of it.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const Product = {
  /**
   * origin 89 controller
   *
   * Reserved: allocated, and not specified yet.
   */
  ORIGIN_89_CONTROLLER: 0x0001,
  /**
   * pzem 003
   *
   * Reserved: allocated, and not specified yet.
   */
  PZEM_003: 0x0002,
  /**
   * pzem 017
   *
   * Reserved: allocated, and not specified yet.
   */
  PZEM_017: 0x0003,
  /**
   * epever tracer b
   *
   * Reserved: allocated, and not specified yet.
   */
  EPEVER_TRACER_B: 0x0004,
  /**
   * victron mppt rs
   *
   * Reserved: allocated, and not specified yet.
   */
  VICTRON_MPPT_RS: 0x0005,
  /**
   * victron multiplus
   *
   * Reserved: allocated, and not specified yet.
   */
  VICTRON_MULTIPLUS: 0x0006,
  /**
   * eg4 lifepower4
   *
   * Reserved: allocated, and not specified yet.
   */
  EG4_LIFEPOWER4: 0x0007,
  /**
   * morningstar sunsaver duo
   *
   * Reserved: allocated, and not specified yet.
   */
  MORNINGSTAR_SUNSAVER_DUO: 0x0008,
  /**
   * emporia vue 3
   *
   * Reserved: allocated, and not specified yet.
   */
  EMPORIA_VUE_3: 0x0009,
  /**
   * ecoflow power kit
   *
   * Reserved: allocated, and not specified yet.
   */
  ECOFLOW_POWER_KIT: 0x000a,
} as const;

/**
 * One namespace per vendor, so two drivers cannot both pick 7 for a vendor kind
 * or a raw condition code.
 *
 * Open: a device may emit a value this table does not name, and a client shows
 * that one carrier as unrecognised rather than blanking the message around it.
 */
export const VendorNamespace = {
  /**
   * victron
   *
   * Reserved: allocated, and not specified yet.
   */
  VICTRON: 0x0001,
  /**
   * epever
   *
   * Reserved: allocated, and not specified yet.
   */
  EPEVER: 0x0002,
  /**
   * pzem
   *
   * Reserved: allocated, and not specified yet.
   */
  PZEM: 0x0003,
  /**
   * eg4
   *
   * Reserved: allocated, and not specified yet.
   */
  EG4: 0x0004,
  /**
   * morningstar
   *
   * Reserved: allocated, and not specified yet.
   */
  MORNINGSTAR: 0x0005,
  /**
   * emporia
   *
   * Reserved: allocated, and not specified yet.
   */
  EMPORIA: 0x0006,
  /**
   * ecoflow
   *
   * Reserved: allocated, and not specified yet.
   */
  ECOFLOW: 0x0007,
  /**
   * magnum
   *
   * Reserved: allocated, and not specified yet.
   */
  MAGNUM: 0x0008,
  /**
   * xantrex
   *
   * Reserved: allocated, and not specified yet.
   */
  XANTREX: 0x0009,
} as const;

/**
 * The unit and scale of every metric kind, keyed by kind: `value = raw ×
 * 10^scale`.
 */
export const metricUnits: Record<number, readonly [string, number]> = {
  0x0101: ["V", -3],
  0x0102: ["A", -3],
  0x0103: ["W", -1],
  0x0104: ["%", -1],
  0x0105: ["°C", -1],
  0x0110: ["V", -3],
  0x0111: ["A", -3],
  0x0112: ["W", -1],
  0x0120: ["A", -3],
  0x0121: ["W", -1],
  0x0130: ["V", -3],
  0x0201: ["V", -1],
  0x0202: ["A", -3],
  0x0203: ["W", -1],
  0x0204: ["Hz", -2],
  0x0205: ["Wh", 0],
  0x0206: ["Wh", 0],
  0x0207: ["Wh", 0],
  0x0301: ["°C", -1],
  0x0302: ["°C", -1],
  0x0401: ["%", -1],
  0x0402: ["A", -6],
  0x0501: ["—", 0],
  0x0502: ["h", -2],
  0x0503: ["count", 0],
  0x0504: ["—", 0],
  0x0601: ["—", 0],
  0x0602: ["s", 0],
  0x0603: ["—", 0],
  0x0604: ["%", -1],
  0x0701: ["min", 0],
  0x0702: ["min", 0],
  0x0703: ["min", 0],
};

/**
 * The public equipment dataset's word for a reading: a metric kind over a
 * signal domain, at a place. An undefined place matches any; the domain never
 * does, so a limit or a period counter cannot borrow a live reading's word.
 */
export interface DatasetMetric {
  /** A {@link MetricKind} value. */
  readonly kind: number;
  /** A {@link SignalDomain} value, matched exactly. */
  readonly domain: number;
  /** A {@link ComponentRole} value, or undefined to match any role. */
  readonly role?: number;
  /** A {@link MeasurementPoint} value, or undefined to match any point. */
  readonly point?: number;
  /** The dataset's word, such as `pv-voltage`. */
  readonly name: string;
}

/** Every dataset word a metric carries, most specific row first. */
export const datasetMetrics: readonly DatasetMetric[] = [
  { kind: 0x0101, domain: 0x01, role: 0x0001, name: "pv-voltage" },
  { kind: 0x0101, domain: 0x01, role: 0x0002, name: "pv-voltage" },
  { kind: 0x0101, domain: 0x01, role: 0x0003, name: "battery-voltage" },
  { kind: 0x0101, domain: 0x01, role: 0x0004, name: "battery-voltage" },
  { kind: 0x0101, domain: 0x01, role: 0x000d, name: "load-voltage" },
  { kind: 0x0102, domain: 0x01, role: 0x0001, name: "pv-current" },
  { kind: 0x0102, domain: 0x01, role: 0x0002, name: "pv-current" },
  { kind: 0x0102, domain: 0x01, role: 0x0003, name: "battery-current" },
  { kind: 0x0102, domain: 0x01, role: 0x0004, name: "battery-current" },
  { kind: 0x0102, domain: 0x01, role: 0x000d, name: "load-current" },
  { kind: 0x0103, domain: 0x01, role: 0x0001, name: "pv-power" },
  { kind: 0x0103, domain: 0x01, role: 0x0002, name: "pv-power" },
  { kind: 0x0103, domain: 0x01, role: 0x0003, name: "battery-power" },
  { kind: 0x0103, domain: 0x01, role: 0x0004, name: "battery-power" },
  { kind: 0x0103, domain: 0x01, role: 0x000d, name: "load-power" },
  { kind: 0x0302, domain: 0x01, role: 0x0003, name: "battery-temperature" },
  { kind: 0x0302, domain: 0x01, role: 0x0004, name: "battery-temperature" },
  { kind: 0x0302, domain: 0x01, role: 0x0017, name: "battery-temperature" },
  { kind: 0x0104, domain: 0x01, name: "state-of-charge" },
  { kind: 0x0201, domain: 0x01, name: "ac-voltage" },
  { kind: 0x0202, domain: 0x01, name: "ac-current" },
  { kind: 0x0203, domain: 0x01, name: "ac-power" },
  { kind: 0x0204, domain: 0x01, name: "ac-frequency" },
  { kind: 0x0205, domain: 0x02, name: "ac-energy-total" },
  { kind: 0x0205, domain: 0x04, name: "ac-energy-today" },
  { kind: 0x0302, domain: 0x01, name: "temperature" },
  { kind: 0x0401, domain: 0x01, name: "tank-level" },
  { kind: 0x0501, domain: 0x01, name: "generator-run-state" },
  { kind: 0x0502, domain: 0x02, name: "generator-run-hours" },
  { kind: 0x0602, domain: 0x03, name: "uptime" },
];

/** Dataset words no metric carries, each with why. */
export const datasetAbsent: Readonly<Record<string, string>> = {
  "ac-apparent-power": "no metric kind",
  "ac-power-factor": "no metric kind",
  "charge-stage": "the charge stage enum space has no members yet (#3)",
  "consumed-amp-hours": "no DC charge counter kind (#2)",
  "cycle-count": "no metric kind",
  "humidity": "no metric kind",
  "link-downlink": "no metric kind",
  "link-latency": "no metric kind",
  "link-online": "link state is presence and the comms link events, not a metric",
  "link-signal-quality": "no metric kind; the comms processor's radio is not a reading the controller carries",
  "link-uplink": "no metric kind",
  "pressure": "no metric kind",
  "pv-energy-today": "no DC energy kind (#2)",
  "pv-energy-total": "no DC energy kind (#2)",
  "pv-irradiance": "no metric kind",
  "state-of-health": "no metric kind",
  "switch-state": "the only switch metric is the generator run contact command, an echo of a command rather than a measured state",
  "tank-volume": "the protocol carries a tank level in percent, never a volume",
  "time-to-go": "no metric kind",
};

/**
 * The dataset's word for a reading, or undefined when it has none. The first
 * matching row of {@link datasetMetrics} wins, which is why it is ordered most
 * specific first.
 */
export function datasetName(
  kind: number,
  domain: number,
  role?: number,
  point?: number,
): string | undefined {
  return datasetMetrics.find(
    (m) =>
      m.kind === kind &&
      m.domain === domain &&
      (m.role === undefined || m.role === role) &&
      (m.point === undefined || m.point === point),
  )?.name;
}
