// Generated by `cargo xtask registry` from crates/km43/protocol.toml.
// Do not edit. A number lives in one place or two people allocate it twice.
// registry-digest: 80419f7044d57bcf

export enum MessageType {
  Discover = 0x0,
  DiscoverResponse = 0x80,
  Hello = 0x1,
  HelloResponse = 0x81,
  Subscribe = 0x3,
  SubscribeResponse = 0x83,
  EventResponse = 0x4,
  ReadLog = 0x5,
  ReadLogResponse = 0x85,
  GetConfig = 0x6,
  GetConfigResponse = 0x86,
  SetConfig = 0x7,
  SetConfigResponse = 0x87,
  Command = 0x8,
  CommandResponse = 0x88,
  Firmware = 0x9,
  FirmwareResponse = 0x89,
  Time = 0xa,
  TimeResponse = 0x8a,
  Pair = 0xb,
  PairResponse = 0x8b,
  Goodbye = 0xc,
  GoodbyeResponse = 0x8c,
  Inventory = 0xd,
  InventoryResponse = 0x8d,
  Readings = 0xe,
  ReadingsResponse = 0x8e,
  Concerns = 0xf,
  ConcernsResponse = 0x8f,
  History = 0x10,
  HistoryResponse = 0x90,
  ErrorResponse = 0xff,
}

export enum ErrorCode {
  MalformedFrame = 0x1,
  UnknownMessageType = 0x2,
  ProtocolMajorMismatch = 0x3,
  HelloRequiredFirst = 0x4,
  PayloadTooLarge = 0x5,
  UnknownSection = 0x6,
  BusyRetry = 0x7,
  SessionTableFull = 0x8,
  SessionExpired = 0x9,
  BadMAC = 0xa,
  CounterNotFresh = 0xb,
  UnknownClient = 0xc,
  StaleChallengeReconnectAndRetry = 0xe,
}

export enum Command {
  Accepted = 0x1,
  Rejected = 0x2,
  Duplicate = 0x3,
  Inhibited = 0x4,
  Unauthorised = 0x5,
  Shadowed = 0x6,
  StaleTopology = 0x7,
  WrongTarget = 0x8,
}

export enum Concerns {
  Ok = 0x1,
  Superseded = 0x2,
  OutOfRange = 0x3,
}

export enum Firmware {
  Accepted = 0x1,
  BadOffset = 0x2,
  BadSignature = 0x3,
  WrongTarget = 0x4,
  TooLarge = 0x5,
  NoTransferInProgress = 0x6,
  NotOwner = 0x7,
  Unauthorised = 0x8,
}

export enum History {
  Ok = 0x1,
  Superseded = 0x2,
  UnknownSignal = 0x3,
  SeriesNotHistorable = 0x4,
  NoHistory = 0x5,
  OutOfRange = 0x6,
}

export enum Inventory {
  Ok = 0x1,
  Superseded = 0x2,
  UnknownKind = 0x3,
  OutOfRange = 0x4,
}

export enum Pair {
  Enrolled = 0x1,
  WindowClosed = 0x2,
  BadProof = 0x3,
  TableFull = 0x4,
  Reclaimed = 0x5,
}

export enum Readings {
  Ok = 0x1,
  Superseded = 0x2,
  UnknownSelector = 0x3,
  OutOfRange = 0x4,
}

export enum SetConfig {
  Accepted = 0x1,
  StaleVersion = 0x2,
  Invalid = 0x3,
  Unauthorised = 0x4,
  ExceedsCap = 0x5,
  Staged = 0x9,
}

export enum Time {
  Accepted = 0x1,
  Rejected = 0x2,
  Unauthorised = 0x3,
  NeedsButton = 0x4,
}

export enum BootReason {
  PowerOn = 0x1,
  Watchdog = 0x2,
  BrownOut = 0x3,
  SoftwareReset = 0x4,
  Panic = 0x5,
}

export enum Bucket {
  Day = 0x1,
  Hour = 0x2,
  QuarterHour = 0x3,
}

export enum ClientKind {
  App = 0x1,
  Browser = 0x2,
  Cloud = 0x3,
  Cli = 0x4,
}

export enum ConcernState {
  Active = 0x1,
  ActiveAcked = 0x2,
  LatchedCleared = 0x3,
  ClearingBlocked = 0x4,
  Cleared = 0x5,
}

export enum ControlOwner {
  LocalPanel = 0x1,
  ThisController = 0x2,
  Bms = 0x3,
  GxEss = 0x4,
  RemoteClient = 0x5,
  DeviceAutomation = 0x6,
}

export enum Direction {
  PositiveIsIn = 0x1,
  PositiveIsOut = 0x2,
  MagnitudeOnly = 0x3,
}

export enum GeneratorSelector {
  Auto = 0x1,
  Off = 0x2,
  Manual = 0x3,
}

export enum GeneratorState {
  Stopped = 0x1,
  Starting = 0x2,
  Running = 0x3,
  RunningNotOurs = 0x4,
  StopNotHonoured = 0x5,
  GaveUp = 0x6,
}

export enum HistorySource {
  DeviceReported = 0x1,
  ControllerDerived = 0x2,
}

export enum HistoryStopReason {
  DeviceReplaced = 0x1,
  ComponentReassigned = 0x2,
  GapInRecord = 0x3,
  EndOfRecord = 0x4,
  OlderThanStore = 0x5,
  PageFull = 0x6,
}

export enum InventoryKind {
  Buses = 0x1,
  Devices = 0x2,
  Components = 0x3,
  Signals = 0x4,
  Parameters = 0x5,
}

export enum Presence {
  Online = 0x1,
  Degraded = 0x2,
  Offline = 0x3,
  NeverSeen = 0x4,
}

export enum Provenance {
  None = 0x0,
  Measured = 0x1,
  Counted = 0x2,
  Derived = 0x3,
  Estimated = 0x4,
  Reported = 0x5,
  Commanded = 0x6,
}

export enum Quality {
  Measured = 0x1,
  Counted = 0x2,
  Estimated = 0x3,
  Stale = 0x4,
  Absent = 0x5,
}

export enum Severity {
  Info = 0x1,
  Warning = 0x2,
  Fault = 0x3,
  Protection = 0x4,
}

export enum Shape {
  Scalar = 0x1,
  Series = 0x2,
}

export enum SignalDomain {
  Live = 0x1,
  Lifetime = 0x2,
  SinceReset = 0x3,
  Today = 0x4,
  Yesterday = 0x5,
  LimitUpper = 0x6,
  LimitLower = 0x7,
  Max = 0x8,
  Min = 0x9,
}

export enum TimeSource {
  Client = 0x1,
  NtpViaComms = 0x2,
}

export enum TopologyChangeReason {
  Boot = 0x1,
  ConfigWrite = 0x2,
  SubDeviceAdopted = 0x3,
  SubDeviceRemoved = 0x4,
  DeviceReplaced = 0x5,
}

export enum Transport {
  Rs485 = 0x1,
  Can = 0x2,
  VeDirect = 0x3,
  LocalIo = 0x4,
  Ip = 0x5,
  Onewire = 0x6,
  Internal = 0x7,
}

export enum Unit {
  Volt = 0x1,
  Ampere = 0x2,
  Watt = 0x3,
  WattHour = 0x4,
  AmpereHour = 0x5,
  DegreeCelsius = 0x6,
  Percent = 0x7,
  Hertz = 0x8,
  Second = 0x9,
  Minute = 0xa,
  Hour = 0xb,
  Count = 0xc,
  Ohm = 0xd,
  Pascal = 0xe,
  Litre = 0xf,
  None = 0x10,
}

export enum Validity {
  Ok = 0x1,
  Stale = 0x2,
  Initialising = 0x3,
  Unsupported = 0x4,
  SensorFault = 0x5,
  OutOfRange = 0x6,
  Absent = 0x7,
  UnnamedState = 0x8,
}

export enum Vtype {
  Gauge = 0x1,
  Counter = 0x2,
  Enum = 0x3,
  Flags = 0x4,
}

export enum CapabilityBit {
  EventLogReadable = 0x0,
  ConfigurationWritable = 0x1,
  CommandsAccepted = 0x2,
  FirmwareUpdateAccepted = 0x3,
  ClockSettableByClient = 0x4,
  CountedStateOfChargeAvailable = 0x5,
  ACMeteringOnTheGenerator = 0x6,
  AnyBehaviourIsInShadowMode = 0x7,
}

export enum CommandKind {
  StartGenerator = 0x101,
  StopGenerator = 0x102,
  RunExerciseCycleNow = 0x103,
  SetOutput = 0x201,
  AcknowledgeConcern = 0x203,
  ClearOverride = 0x301,
}

export enum ConfigSection {
  IdentityAndSite = 0x1,
  Channels = 0x2,
  BusesAndDevices = 0x3,
  GeneratorBehaviour = 0x10,
  FrostBehaviour = 0x11,
  ScheduleBehaviour = 0x12,
  LoadShedBehaviour = 0x13,
  Network = 0x20,
  Cloud = 0x21,
}

export enum LinkErrorCode {
  WrongSide = 0x100,
  LinkTypeOnClientTransport = 0x101,
  BeforeLinkUp = 0x102,
  UnknownHandle = 0x103,
  ConnectionTableFull = 0x104,
  LinkMajorMismatch = 0x105,
  TooManyOutstanding = 0x106,
  NonZeroSession = 0x107,
  NoAuthorisation = 0x108,
}

export const ClientCapability = {
  WRITE_CONFIG: 1 << 0,
  WRITE_NETWORK_AND_CLOUD: 1 << 1,
  SEND_COMMAND: 1 << 2,
  SET_CLOCK: 1 << 3,
  PUSH_FIRMWARE: 1 << 4,
} as const;

// Open sets: a device may emit a value this table does not name, and a
// client shows that one carrier as unrecognised rather than blanking the
// message around it.
export const MetricKind = {
  DC_VOLTAGE: 0x0101,
  DC_CURRENT: 0x0102,
  DC_POWER: 0x0103,
  STATE_OF_CHARGE: 0x0104,
  AC_VOLTAGE: 0x0201,
  AC_CURRENT: 0x0202,
  AC_POWER: 0x0203,
  AC_FREQUENCY: 0x0204,
  AC_ENERGY: 0x0205,
  AC_ENERGY_IMPORTED: 0x0206,
  AC_ENERGY_EXPORTED: 0x0207,
  TEMPERATURE: 0x0302,
  TANK_LEVEL: 0x0401,
  TANK_SENDER_CURRENT: 0x0402,
  GENERATOR_STATE: 0x0501,
  GENERATOR_RUN_HOURS: 0x0502,
  GENERATOR_STARTS_SINCE_COMMISSIONING: 0x0503,
  RUN_CONTACT_COMMANDED: 0x0504,
  GENERATOR_SELECTOR_POSITION: 0x0601,
  UPTIME_SINCE_BOOT: 0x0602,
  LAST_BOOT_REASON: 0x0603,
  LOG_RING_UTILISATION: 0x0604,
  TIME_IN_BULK: 0x0701,
  TIME_IN_ABSORPTION: 0x0702,
  TIME_IN_FLOAT: 0x0703,
} as const;

export const EventKind = {
  SIGNAL_VALIDITY_CHANGED: 0x0102,
  GENERATOR_STATE_CHANGED: 0x0201,
  GENERATOR_COMMAND_WITHDRAWN: 0x0202,
  GENERATOR_STOP_NOT_HONOURED: 0x0203,
  BEHAVIOUR_DECISION: 0x0301,
  BEHAVIOUR_INHIBITED: 0x0302,
  OUTPUT_CHANGED: 0x0401,
  CONCERN_RAISED: 0x0501,
  CONCERN_CHANGED: 0x0502,
  BOOT: 0x0601,
  CONFIG_CHANGED: 0x0602,
  CLIENT_ENROLLED: 0x0603,
  TIME_SET: 0x0604,
  RECORDS_DROPPED: 0x0701,
  RECORD_FAILED_CRC: 0x0702,
  COMMS_LINK_LOST: 0x0801,
  COMMS_POWER_CYCLED: 0x0802,
  COMMS_UNRECOVERABLE: 0x0803,
  SESSIONS_SHED_FOR_BACKPRESSURE: 0x0804,
  TOPOLOGY_CHANGED: 0x0901,
  DEVICE_PRESENCE_CHANGED: 0x0902,
} as const;

export const ComponentRole = {
  PV_ARRAY: 0x0001,
  MPPT_TRACKER: 0x0002,
  BATTERY_BANK: 0x0003,
  BATTERY_PACK: 0x0004,
  HEATER: 0x0005,
  CONTACTOR: 0x0006,
  FET: 0x0007,
  AC_INPUT: 0x0008,
  AC_OUTPUT: 0x0009,
  PHASE: 0x000a,
  LINE_PAIR: 0x000b,
  DC_OUTPUT: 0x000c,
  LOAD_OUTPUT: 0x000d,
  START_BATTERY: 0x000e,
  METER: 0x000f,
  CIRCUIT: 0x0010,
  MERGED_CIRCUIT: 0x0011,
  TRANSFER_RELAY: 0x0012,
  INVERTER: 0x0013,
  CHARGER: 0x0014,
  PROBE: 0x0015,
  TANK: 0x0016,
  CELL: 0x0017,
  RELAY: 0x0018,
  GENERATOR: 0x0019,
} as const;

export const Condition = {
  OVER_VOLTAGE: 0x0001,
  UNDER_VOLTAGE: 0x0002,
  OVER_TEMPERATURE: 0x0003,
  UNDER_TEMPERATURE: 0x0004,
  CHARGE_OVER_CURRENT: 0x0005,
  DISCHARGE_OVER_CURRENT: 0x0006,
  SHORT_CIRCUIT: 0x0007,
  OVERLOAD: 0x0008,
  CELL_IMBALANCE: 0x0009,
  LOW_STATE_OF_CHARGE: 0x000a,
  CHARGE_INHIBITED: 0x000b,
  DISCHARGE_INHIBITED: 0x000c,
  UNNAMED_STATE: 0x000d,
  REGISTRATION_REFUSED: 0x000e,
  SERIES_TOO_LONG: 0x000f,
  INVENTORY_FULL: 0x0010,
  BAY_FLAPPING: 0x0011,
  COUNTER_WRITE_FAILED: 0x0012,
  EPOCH_WRITE_FAILED: 0x0013,
  CLOCK_STEPPED: 0x0014,
  FLOOR_OVERRIDDEN: 0x0015,
} as const;

export const DeviceRole = {
  SOLAR_CHARGER: 0x0001,
  INVERTER: 0x0002,
  INVERTER_CHARGER: 0x0003,
  BMS: 0x0004,
  ENERGY_METER: 0x0005,
  SHUNT: 0x0006,
  SENSOR: 0x0007,
  POWER_MODULE: 0x0008,
  CONTROLLER: 0x0009,
  BATTERY_MONITOR: 0x000a,
  TEMPERATURE_SENSOR: 0x000b,
} as const;

export const Dialect = {
  NO_PROTOCOL: 0x0001,
  PZEM_DC: 0x0002,
  EPEVER_B: 0x0003,
  VICTRON_MPPT_RS_HEX: 0x0004,
  VICTRON_GX_MODBUS_VEBUS: 0x0005,
  EG4_LIFEPOWER4_SERIAL: 0x0006,
  MORNINGSTAR_SUNSAVER_DUO: 0x0007,
  EMPORIA_VUE3_ESPHOME_I2C: 0x0008,
  ECOFLOW_POWER_KITS: 0x0009,
} as const;

export const EnumSpace = {
  PRESENCE: 0x0001,
  CONTROL_OWNER: 0x0002,
  GENERATOR_STATE: 0x0003,
  GENERATOR_SELECTOR: 0x0004,
  BOOT_REASON: 0x0005,
  CHARGE_STAGE: 0x0006,
  BALANCING: 0x0007,
} as const;

export const MeasurementPoint = {
  LINE_TO_NEUTRAL: 0x0001,
  LINE_TO_LINE: 0x0002,
  TERMINAL: 0x0003,
  CELL: 0x0004,
  INTERNAL: 0x0005,
  AMBIENT: 0x0006,
  HEATSINK: 0x0007,
  CASE: 0x0008,
  INLET: 0x0009,
  OUTLET: 0x000a,
  TRANSFORMER: 0x000b,
} as const;

export const Product = {
  ORIGIN_89_CONTROLLER: 0x0001,
  PZEM_003: 0x0002,
  PZEM_017: 0x0003,
  EPEVER_TRACER_B: 0x0004,
  VICTRON_MPPT_RS: 0x0005,
  VICTRON_MULTIPLUS: 0x0006,
  EG4_LIFEPOWER4: 0x0007,
  MORNINGSTAR_SUNSAVER_DUO: 0x0008,
  EMPORIA_VUE_3: 0x0009,
  ECOFLOW_POWER_KIT: 0x000a,
} as const;

export const VendorNamespace = {
  VICTRON: 0x0001,
  EPEVER: 0x0002,
  PZEM: 0x0003,
  EG4: 0x0004,
  MORNINGSTAR: 0x0005,
  EMPORIA: 0x0006,
  ECOFLOW: 0x0007,
  MAGNUM: 0x0008,
  XANTREX: 0x0009,
} as const;

export const metricUnits: Record<number, readonly [string, number]> = {
  0x0101: ["V", -3],
  0x0102: ["A", -3],
  0x0103: ["W", -1],
  0x0104: ["%", -1],
  0x0105: ["°C", -1],
  0x0110: ["V", -3],
  0x0111: ["A", -3],
  0x0112: ["W", -1],
  0x0120: ["A", -3],
  0x0121: ["W", -1],
  0x0130: ["V", -3],
  0x0201: ["V", -1],
  0x0202: ["A", -3],
  0x0203: ["W", -1],
  0x0204: ["Hz", -2],
  0x0205: ["Wh", 0],
  0x0206: ["Wh", 0],
  0x0207: ["Wh", 0],
  0x0301: ["°C", -1],
  0x0302: ["°C", -1],
  0x0401: ["%", -1],
  0x0402: ["A", -6],
  0x0501: ["—", 0],
  0x0502: ["h", -2],
  0x0503: ["count", 0],
  0x0504: ["—", 0],
  0x0601: ["—", 0],
  0x0602: ["s", 0],
  0x0603: ["—", 0],
  0x0604: ["%", -1],
  0x0701: ["min", 0],
  0x0702: ["min", 0],
  0x0703: ["min", 0],
};

// The public equipment dataset's word for a reading: a metric kind at a
// place. An undefined place matches any; rows are most specific first.
export interface DatasetMetric {
  readonly kind: number;
  readonly role?: number;
  readonly point?: number;
  readonly domain?: number;
  readonly name: string;
}

export const datasetMetrics: readonly DatasetMetric[] = [
  { kind: 0x0101, role: 0x0001, name: "pv-voltage" },
  { kind: 0x0101, role: 0x0002, name: "pv-voltage" },
  { kind: 0x0101, role: 0x0003, name: "battery-voltage" },
  { kind: 0x0101, role: 0x0004, name: "battery-voltage" },
  { kind: 0x0101, role: 0x000d, name: "load-voltage" },
  { kind: 0x0102, role: 0x0001, name: "pv-current" },
  { kind: 0x0102, role: 0x0002, name: "pv-current" },
  { kind: 0x0102, role: 0x0003, name: "battery-current" },
  { kind: 0x0102, role: 0x0004, name: "battery-current" },
  { kind: 0x0102, role: 0x000d, name: "load-current" },
  { kind: 0x0103, role: 0x0001, name: "pv-power" },
  { kind: 0x0103, role: 0x0002, name: "pv-power" },
  { kind: 0x0103, role: 0x0003, name: "battery-power" },
  { kind: 0x0103, role: 0x0004, name: "battery-power" },
  { kind: 0x0103, role: 0x000d, name: "load-power" },
  { kind: 0x0302, role: 0x0003, name: "battery-temperature" },
  { kind: 0x0302, role: 0x0004, name: "battery-temperature" },
  { kind: 0x0302, role: 0x0017, name: "battery-temperature" },
  { kind: 0x0205, domain: 0x02, name: "ac-energy-total" },
  { kind: 0x0205, domain: 0x04, name: "ac-energy-today" },
  { kind: 0x0104, name: "state-of-charge" },
  { kind: 0x0201, name: "ac-voltage" },
  { kind: 0x0202, name: "ac-current" },
  { kind: 0x0203, name: "ac-power" },
  { kind: 0x0204, name: "ac-frequency" },
  { kind: 0x0302, name: "temperature" },
  { kind: 0x0401, name: "tank-level" },
  { kind: 0x0501, name: "generator-run-state" },
  { kind: 0x0502, name: "generator-run-hours" },
  { kind: 0x0602, name: "uptime" },
];

// Dataset words no metric carries, each with why.
export const datasetAbsent: Readonly<Record<string, string>> = {
  "ac-apparent-power": "no metric kind",
  "ac-power-factor": "no metric kind",
  "charge-stage": "the charge stage enum space has no members yet (#3)",
  "consumed-amp-hours": "no DC charge counter kind (#2)",
  "cycle-count": "no metric kind",
  "humidity": "no metric kind",
  "link-downlink": "no metric kind",
  "link-latency": "no metric kind",
  "link-online": "link state is presence and the comms link events, not a metric",
  "link-signal-quality": "no metric kind; the comms processor's radio is not a reading the controller carries",
  "link-uplink": "no metric kind",
  "pressure": "no metric kind",
  "pv-energy-today": "no DC energy kind (#2)",
  "pv-energy-total": "no DC energy kind (#2)",
  "pv-irradiance": "no metric kind",
  "state-of-health": "no metric kind",
  "switch-state": "the only switch metric is the generator run contact command (0x0504), an echo of a command rather than a measured state",
  "tank-volume": "the protocol carries a tank level in percent, never a volume",
  "time-to-go": "no metric kind",
};

export function datasetName(
  kind: number,
  role?: number,
  point?: number,
  domain?: number,
): string | undefined {
  return datasetMetrics.find(
    (m) =>
      m.kind === kind &&
      (m.role === undefined || m.role === role) &&
      (m.point === undefined || m.point === point) &&
      (m.domain === undefined || m.domain === domain),
  )?.name;
}
