//! Generates the constants for both implementations from the registry.
//!
//! Some spaces are open sets and the rest are closed, and that difference decides
//! the shape: a closed space becomes an enum whose `TryFrom` refuses an unknown
//! value, an open one becomes a newtype with named constants that carries a
//! value nobody has allocated. Getting that backwards means either a snapshot
//! blanked because somebody hung a vendor meter on the bus, or a controller
//! acting on a discriminant it cannot read.
//!
//! A space is open by being in `[[open_registries.*]]`, which is a fact about
//! where it is written rather than a flag read somewhere else. The form before
//! this was a list of names in `meta.skip_unknown` consulted at exactly two
//! hardcoded call sites, so a name added to it did nothing at all and no build
//! could go red about it — the space stayed closed while the file read as though
//! a decision had been made.

use anyhow::{Context as _, Result};
use std::fmt::Write as _;
use std::path::Path;

use crate::codegen::{Codegen, heading_for};
use crate::registry::{Auth, EventClass, Message, Registry, Status};

const HEADER: &str = "Generated by `cargo xtask registry` from crates/km43/protocol.toml.\n\
                      Do not edit. A number lives in one place or two people allocate it twice.";

pub struct Bindings {
    registry: Registry,
    prose: RegistryDoc,
}

impl Bindings {
    /// The line `km43/build.rs` looks for. Both languages use `//`, so
    /// one marker serves both.
    pub const DIGEST_MARKER: &'static str = "// registry-digest: ";

    pub fn load(root: &Path) -> Result<Self> {
        let path = root.join(Codegen::PATH);
        Ok(Self {
            registry: Registry::load(root)?,
            prose: RegistryDoc(
                std::fs::read_to_string(&path)
                    .with_context(|| format!("reading {}", path.display()))?,
            ),
        })
    }

    /// The generated files that no longer match the registry.
    pub fn stale(&self, root: &Path) -> Result<Vec<String>> {
        Ok(self
            .targets()?
            .into_iter()
            .filter(|(path, body)| {
                std::fs::read_to_string(root.join(path)).is_ok_and(|c| &c != body)
            })
            .map(|(path, _)| path.to_owned())
            .collect())
    }

    fn targets(&self) -> Result<Vec<(&'static str, String)>> {
        Ok(vec![
            ("crates/km43/src/generated.rs", self.rust()?),
            ("packages/km43/src/generated.ts", self.typescript()?),
        ])
    }

    pub fn write(&self, root: &Path) -> Result<()> {
        for (path, body) in self.targets()? {
            let full = root.join(path);
            if let Some(dir) = full.parent() {
                std::fs::create_dir_all(dir)?;
            }
            let changed = std::fs::read_to_string(&full).is_ok_and(|c| c == body);
            std::fs::write(&full, body)?;
            if !changed {
                println!("wrote {path}");
            }
        }
        Ok(())
    }

    fn is_open(&self, space: &str) -> bool {
        self.registry.meta.skip_unknown.iter().any(|s| s == space)
    }

    /// The transport constants: BLE identifiers, where the WebSocket is found,
    /// and the limits both share.
    fn rust_transport(&self, o: &mut String) {
        for (name, uuid, doc) in self.registry.ble.uuids() {
            let _ = writeln!(o, "/// {doc}\npub const {name}: &str = {uuid:?};\n");
        }
        for (name, value, doc) in self.registry.ble.flags() {
            let _ = writeln!(o, "/// {doc}\npub const {name}: u8 = {value};\n");
        }
        let (name, port, doc) = self.registry.websocket.port();
        let _ = writeln!(o, "/// {doc}\npub const {name}: u16 = {port};\n");
        for (name, text, doc) in self.registry.websocket.texts() {
            let _ = writeln!(o, "/// {doc}\npub const {name}: &str = {text:?};\n");
        }

        for limit in self.registry.transport_limits() {
            let _ = writeln!(
                o,
                "/// {}\npub const {}: {} = {};\n",
                limit.doc, limit.name, limit.rust_type, limit.value
            );
        }
    }

    fn rust(&self) -> Result<String> {
        let mut o = String::new();
        for line in HEADER.lines() {
            let _ = writeln!(o, "// {line}");
        }
        let _ = writeln!(o, "{}{}\n", Self::DIGEST_MARKER, self.registry.digest);

        self.rust_transport(&mut o);

        closed_enum(&mut o, "u8", &self.message_space()?);
        closed_enum(&mut o, "u8", &self.link_message_space());
        o.push_str(&self.link_directions());
        closed_enum(&mut o, "u16", &self.error_space()?);
        for space in self.enum_spaces()? {
            closed_enum(&mut o, "u8", &space);
        }
        for space in self.code_spaces()? {
            closed_enum(&mut o, "u16", &space);
        }
        for space in self.link_spaces() {
            closed_enum(&mut o, "u8", &space);
        }

        o.push_str(&self.rust_error_sealed());
        o.push_str(&self.rust_event_class());
        o.push_str(&self.rust_link_and_capability()?);

        o.push_str(&self.rust_open_sets()?);
        Ok(o)
    }

    /// Every message's request and response constants.
    fn message_space(&self) -> Result<Space> {
        Ok(Space {
            name: "MessageType".to_owned(),
            doc: self.prose.summary("## Message types")?,
            members: self
                .registry
                .messages
                .iter()
                .filter(|m| !m.status.is_gone())
                .flat_map(message_members)
                .flatten()
                .collect(),
        })
    }

    /// `Error 0xFF`'s codes, each saying whether a receiver may accept it bare.
    fn error_space(&self) -> Result<Space> {
        Ok(Space {
            name: "ErrorCode".to_owned(),
            doc: self.prose.summary("## Error codes")?,
            members: self
                .registry
                .errors
                .iter()
                .filter(|e| e.status == Status::Live)
                .map(|e| Member {
                    name: variant(&e.meaning),
                    number: e.code,
                    doc: error_doc(&e.meaning, e.sealed),
                })
                .collect(),
        })
    }

    /// The closed `u8` spaces a client sees: every outcome, then every enum.
    fn enum_spaces(&self) -> Result<Vec<Space>> {
        self.registry
            .outcomes
            .iter()
            .chain(&self.registry.enums)
            .map(|(space, entries)| {
                Ok(Space {
                    name: variant(space),
                    doc: self.prose.summary(&heading_for(space))?,
                    members: outcome_members(entries),
                })
            })
            .collect()
    }

    /// The closed `u16` spaces: config sections, command kinds and the rest.
    fn code_spaces(&self) -> Result<Vec<Space>> {
        self.registry
            .codes
            .iter()
            .map(|(space, entries)| {
                Ok(Space {
                    name: variant(space),
                    doc: self.prose.summary(&heading_for(space))?,
                    members: entries
                        .iter()
                        .filter(|e| e.status.is_some_and(|s| !s.is_gone()))
                        .filter_map(|e| {
                            e.number.map(|n| Member {
                                name: variant(&e.name),
                                number: n,
                                doc: with_caveat(&named(&e.name), e.status),
                            })
                        })
                        .collect(),
                })
            })
            .collect()
    }

    /// The UART's opcodes. No REGISTRY.md section describes them, because a
    /// client never sees one; the words come from the same rows LINK.md's table
    /// is checked against.
    fn link_message_space(&self) -> Space {
        let members = self
            .registry
            .link_messages
            .iter()
            .flat_map(|m| {
                let name = variant(&m.name);
                // The direction column says who starts the exchange, so the
                // acknowledgement travels the other way (`linklocal::permitted`).
                let (request, ack) = match m.direction {
                    crate::registry::LinkDirection::Either => (
                        "Either side may send it.",
                        "Sent back by whichever side received the request.",
                    ),
                    crate::registry::LinkDirection::CommsToController => (
                        "Only the comms processor sends it; the controller's is refused (L-001).",
                        "Only the controller sends it, in answer; the comms processor's is \
                         refused (L-001).",
                    ),
                    crate::registry::LinkDirection::ControllerToComms => (
                        "Only the controller sends it; the comms processor's is refused (L-001).",
                        "Only the comms processor sends it, in answer; the controller's is \
                         refused (L-001).",
                    ),
                };
                [
                    Member {
                        name: name.clone(),
                        number: m.request.0,
                        doc: format!(
                            "The `{}` request. {request} Answered by \
                             {{@link LinkMessageType.{name}Ack}}.",
                            m.name
                        ),
                    },
                    Member {
                        name: format!("{name}Ack"),
                        number: m.response.0,
                        doc: format!("The answer to {{@link LinkMessageType.{name}}}. {ack}"),
                    },
                ]
            })
            .collect();
        Space {
            name: "LinkMessageType".to_owned(),
            doc: format!(
                "A message on the UART between the controller and its comms processor, \
                 specified in [LINK.md]({}docs/protocol/LINK.md). A link-local opcode \
                 arriving on a client transport is a protocol error.",
                RegistryDoc::REPOSITORY
            ),
            members,
        }
    }

    /// The outcome and enum spaces only the UART carries, documented from their
    /// rows for the reason [`Self::link_message_space`] is.
    fn link_spaces(&self) -> Vec<Space> {
        let outcomes = self.registry.link_outcomes.iter().map(|(space, entries)| {
            (
                format!("What the link-local `{}` request answered.", variant(space)),
                space,
                entries,
            )
        });
        let enums = self.registry.link_enums.iter().map(|(space, entries)| {
            (
                format!("A link-local {} value.", space.replace('_', " ")),
                space,
                entries,
            )
        });
        outcomes
            .chain(enums)
            .map(|(what, space, entries)| Space {
                name: variant(space),
                doc: format!(
                    "{what} Allocated in `protocol.toml`, specified in \
                     [LINK.md]({}docs/protocol/LINK.md), and never on a client transport.",
                    RegistryDoc::REPOSITORY
                ),
                members: outcome_members(entries),
            })
            .collect()
    }

    /// The link-local codes, each saying whether a client can ever see it.
    fn link_error_space(&self) -> Result<Space> {
        Ok(Space {
            name: "LinkErrorCode".to_owned(),
            doc: self.prose.summary("## Link-local error codes")?,
            members: self
                .registry
                .link_errors
                .iter()
                .filter(|e| e.status == Status::Live)
                .map(|e| Member {
                    name: variant(&e.name),
                    number: e.code,
                    doc: format!(
                        "{} {}",
                        sentence(&e.meaning),
                        if e.reaches_client {
                            "It reaches the client whose frame raised it (L-180)."
                        } else {
                            "It never appears in a client-facing frame (L-180)."
                        }
                    ),
                })
                .collect(),
        })
    }

    /// The per-client mask's bits. The number is the bit, not the mask.
    fn capability_space(&self) -> Result<Space> {
        Ok(Space {
            name: "ClientCapability".to_owned(),
            doc: self.prose.summary("## Client capability mask")?,
            members: self
                .registry
                .client_capability
                .iter()
                .filter(|c| c.status == Some(Status::Live))
                .filter_map(|c| {
                    Some(Member {
                        name: screaming(c.name.as_ref()?),
                        number: u16::from(c.bit?),
                        doc: format!("The client may {}.", c.may.trim_end_matches('.')),
                    })
                })
                .collect(),
        })
    }

    fn metric_space(&self) -> Result<Space> {
        Ok(Space {
            name: "MetricKind".to_owned(),
            doc: open(&self.prose.summary("## Metric kinds")?),
            members: self
                .registry
                .metrics
                .iter()
                .filter(|m| !m.status.is_gone())
                .map(|m| Member {
                    name: screaming(&m.name),
                    number: m.kind,
                    doc: with_caveat(&metric_doc(&m.name, &m.unit, m.scale), Some(m.status)),
                })
                .collect(),
        })
    }

    fn event_space(&self) -> Result<Space> {
        Ok(Space {
            name: "EventKind".to_owned(),
            doc: open(&self.prose.summary("## Event kinds")?),
            members: self
                .registry
                .events
                .iter()
                .filter(|e| !e.status.is_gone())
                .map(|e| Member {
                    name: screaming(&e.name),
                    number: e.kind,
                    doc: with_caveat(
                        &format!(
                            "{} {}",
                            sentence(&capital(&e.name)),
                            match e.class {
                                EventClass::A =>
                                    "Class A: never dropped, not from the log and \
                                                  not from a queue.",
                                EventClass::B =>
                                    "Class B: dropped first under pressure, and \
                                                  every drop is counted.",
                            }
                        ),
                        Some(e.status),
                    ),
                })
                .collect(),
        })
    }

    /// Every other open space, by being in the table that means open. Metrics
    /// and events have builders of their own because `metrics` and `events` are
    /// top-level tables with shapes of their own — a metric carries a unit and a
    /// scale, an event carries a class — and neither fits the plain
    /// number-and-name row these have.
    fn open_registry_spaces(&self) -> Result<Vec<Space>> {
        self.registry
            .open_registries
            .iter()
            .map(|(space, rows)| {
                Ok(Space {
                    name: variant(space),
                    doc: open(&self.prose.summary(&heading_for(space))?),
                    members: rows
                        .iter()
                        .filter(|r| r.status.is_some_and(|s| !s.is_gone()))
                        .filter_map(|r| {
                            r.number.map(|n| Member {
                                name: screaming(&r.name),
                                number: n,
                                doc: with_caveat(&named(&r.name), r.status),
                            })
                        })
                        .collect(),
                })
            })
            .collect()
    }

    /// The open spaces and the unit table. Split out for the reason the
    /// lint gives: `rust` was over a hundred lines and every one of these is a
    /// self-contained emission.
    fn rust_open_sets(&self) -> Result<String> {
        let mut o = String::new();
        open_newtype(&mut o, &self.metric_space()?, self.is_open("metric_kind"));
        open_newtype(&mut o, &self.event_space()?, self.is_open("event_kind"));
        for space in self.open_registry_spaces()? {
            open_newtype(&mut o, &space, true);
        }

        o.push_str(&self.rust_enum_space_members());

        o.push_str(
            "/// Every metric with the unit and scale it is read in:\n\
             /// `value = raw * 10^scale`. Sorted, so a lookup can bisect.\n\
             pub const METRIC_UNITS: &[(u16, &str, i8)] = &[\n",
        );
        let mut metrics: Vec<_> = self.registry.metrics.iter().collect();
        metrics.sort_by_key(|m| m.kind);
        for m in metrics {
            let _ = writeln!(o, "    ({:#06x}, \"{}\", {}),", m.kind, m.unit, m.scale);
        }
        o.push_str(
            "];\n\n\
             impl MetricKind {\n    \
                 /// The unit and scale this kind is read in, or `None` for a kind this\n    \
                 /// build has never heard of. Not a guess: a reading scaled by the wrong\n    \
                 /// power of ten looks like a real one.\n    \
                 #[must_use]\n    \
                 pub fn unit_and_scale(self) -> Option<(&'static str, i8)> {\n        \
                     METRIC_UNITS\n            \
                         .binary_search_by_key(&self.0, |&(k, _, _)| k)\n            \
                         .ok()\n            \
                         .and_then(|i| METRIC_UNITS.get(i))\n            \
                         .map(|&(_, u, s)| (u, s))\n    \
                 }\n\
             }\n",
        );
        o.push_str(&self.rust_dataset());
        Ok(o)
    }

    /// The public equipment dataset's word for a reading, as a table a lookup
    /// walks first match wins, which is why the registry hands the rows over
    /// most specific first.
    fn rust_dataset(&self) -> String {
        let place = |name: &str, number: Option<u16>| {
            number.map_or_else(|| "None".to_owned(), |n| format!("Some({name}({n:#06x}))"))
        };
        let mut o = String::new();
        o.push_str(
            "\n/// The public equipment dataset's word for a reading: a metric kind over a\n\
             /// signal domain, at a place. A `None` place matches any; the domain never\n\
             /// does, so a limit or a period counter cannot borrow a live reading's word.\n\
             /// Rows are most specific first, so the first match is the one to take.\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             #[cfg_attr(feature = \"defmt\", derive(defmt::Format))]\n\
             pub struct DatasetMetric {\n    \
                 /// The metric kind the reading is.\n    \
                 pub kind: MetricKind,\n    \
                 /// The signal domain, matched exactly.\n    \
                 pub domain: SignalDomain,\n    \
                 /// The component role, or `None` to match any role.\n    \
                 pub role: Option<ComponentRole>,\n    \
                 /// The measurement point, or `None` to match any point.\n    \
                 pub point: Option<MeasurementPoint>,\n    \
                 /// The dataset's word, such as `pv-voltage`.\n    \
                 pub name: &'static str,\n\
             }\n\n\
             /// Every dataset word a metric carries, most specific row first.\n\
             pub const DATASET_METRICS: &[DatasetMetric] = &[\n",
        );
        for c in &self.registry.crosswalk.carried {
            let domain = format!("SignalDomain::{}", variant(&self.domain_name(c.domain)));
            let _ = writeln!(
                o,
                "    DatasetMetric {{\n        kind: MetricKind({:#06x}),\n        domain: {domain},\n        role: {},\n        point: {},\n        name: {:?},\n    }},",
                c.kind,
                place("ComponentRole", c.role),
                place("MeasurementPoint", c.point),
                c.name
            );
        }
        o.push_str(
            "];\n\n/// Dataset words no metric carries, each with why.\n\
             pub const DATASET_ABSENT: &[(&str, &str)] = &[\n",
        );
        for (name, why) in &self.registry.crosswalk.absent {
            // What rustfmt would do with the line, done here so the generated file is
            // already formatted: a tuple within its `fn_call_width` of 60 stays on one
            // line, and a wider one is broken one element per line.
            // `{:?}` on a `str` is a Rust string literal: quotes, backslashes and
            // control characters escaped, so the text a consumer reads is the text
            // in `protocol.toml` and not what the compiler made of a stray `\t`.
            let tuple = format!("({name:?}, {why:?})");
            if tuple.len() <= 60 {
                let _ = writeln!(o, "    {tuple},");
            } else {
                let _ = writeln!(o, "    (\n        {name:?},\n        {why:?},\n    ),");
            }
        }
        o.push_str(
            "];\n\nimpl MetricKind {\n    \
                 /// The dataset's word for this kind over a domain at a place, or `None`\n    \
                 /// when it has none.\n    \
                 #[must_use]\n    \
                 pub fn dataset_name(\n        \
                     self,\n        \
                     domain: SignalDomain,\n        \
                     role: Option<ComponentRole>,\n        \
                     point: Option<MeasurementPoint>,\n    \
                 ) -> Option<&'static str> {\n        \
                     DATASET_METRICS\n            \
                         .iter()\n            \
                         .find(|m| {\n                \
                             m.kind == self\n                    \
                                 && m.domain == domain\n                    \
                                 && m.role.is_none_or(|r| Some(r) == role)\n                    \
                                 && m.point.is_none_or(|p| Some(p) == point)\n            \
                         })\n            \
                         .map(|m| m.name)\n    \
                 }\n\
             }\n",
        );
        o
    }

    /// What each enum space contains, so a controller can ask rather than match.
    ///
    /// The join is by name — `enum_space` "generator state" against
    /// `[[enums.generator_state]]` — and it is done here, once, instead of in
    /// every reader. A space with no member table gets **no row**, which is what
    /// lets the generated `EnumSpace::members` answer `None` and a caller tell *this set
    /// names nothing yet* from *that value is not in it*. The two need telling
    /// apart: the first is a commissioning error and the second is a device
    /// running firmware newer than this build.
    fn rust_enum_space_members(&self) -> String {
        let mut rows: Vec<(u16, Vec<u8>)> = Vec::new();
        for space in self
            .registry
            .open_registries
            .get("enum_space")
            .map(Vec::as_slice)
            .unwrap_or_default()
        {
            let (Some(number), Some(members)) = (
                space.number,
                self.registry.enums.get(&space.name.replace(' ', "_")),
            ) else {
                continue;
            };
            let mut values: Vec<u8> = members
                .iter()
                .filter(|m| !m.status.is_gone())
                .map(|m| m.value)
                .collect();
            values.sort_unstable();
            if !values.is_empty() {
                rows.push((number, values));
            }
        }
        rows.sort_by_key(|&(space, _)| space);

        let mut o = String::from(
            "/// What every enum space contains, by the registry's own tables. Sorted on\n\
             /// both axes, so a lookup can bisect. A space with no members is absent here\n\
             /// rather than present and empty.\n\
             pub const ENUM_SPACE_MEMBERS: &[(u16, &[i32])] = &[\n",
        );
        for (space, values) in rows {
            let list: Vec<String> = values.iter().map(u8::to_string).collect();
            let _ = writeln!(o, "    ({space:#06x}, &[{}]),", list.join(", "));
        }
        o.push_str(
            "];\n\n\
             impl EnumSpace {\n    \
             /// The values this build can name in this space, or `None` where it names\n    \
             /// none at all.\n    \
             ///\n    \
             /// The `None` is the case worth having: a space allocated with no members\n    \
             /// can never name one of its own values, so a signal drawn from it reads\n    \
             /// `unnamed_state` at every poll. That is a registry entry half written,\n    \
             /// and it is a different thing from a device reporting a state this build\n    \
             /// has not heard of.\n    \
             #[must_use]\n    \
             pub fn members(self) -> Option<&'static [i32]> {\n        \
             let at = ENUM_SPACE_MEMBERS\n            \
             .binary_search_by_key(&self.0, |&(space, _)| space)\n            \
             .ok()?;\n        \
             ENUM_SPACE_MEMBERS.get(at).map(|&(_, members)| members)\n    \
             }\n\n    \
             /// Whether this build can name `value` as a member of this space.\n    \
             ///\n    \
             /// False for a space that names nothing, which is deliberate: the caller\n    \
             /// that needs to tell the two apart asks [`Self::members`].\n    \
             #[must_use]\n    \
             pub fn names(self, value: i32) -> bool {\n        \
             self.members()\n            \
             .is_some_and(|members| members.binary_search(&value).is_ok())\n    \
             }\n\
             }\n\n",
        );
        o
    }

    /// The receiver's sealed column, which is registry data and belongs in one
    /// place. `rust` was 126 lines with this inlined, and the lint describing
    /// the fix is the lint that fired.
    fn rust_event_class(&self) -> String {
        let mut o = String::new();
        o.push_str(
            "/// Which records survive a controller under pressure.\n\
             ///\n\
             /// The registry's class column, and the two words are defined there\n\
             /// normatively rather than in a design document — a column with no\n\
             /// definition beside it is one every implementation fills in for itself,\n\
             /// and the two answers it picks between are *keep this alarm* and *drop\n\
             /// it*. A controller that ranks a value change above an alarm raised\n\
             /// loses the alarm on the busiest day, which is the day it mattered.\n\
             /// Sorted, so a lookup can bisect.\n\
             pub const EVENT_IS_CLASS_A: &[(u16, bool)] = &[\n",
        );
        let mut kinds: Vec<_> = self
            .registry
            .events
            .iter()
            .filter(|e| !e.status.is_gone())
            .collect();
        kinds.sort_by_key(|e| e.kind);
        for e in kinds {
            let _ = writeln!(o, "    ({}, {}),", e.kind, matches!(e.class, EventClass::A));
        }
        o.push_str(
            "];\n\n\
             impl EventKind {\n    \
                 /// Whether this record is never dropped — not from the log, and not\n    \
                 /// from a queue.\n    \
                 ///\n    \
                 /// `None` for a kind this build has never heard of. Not `false`: a\n    \
                 /// controller that treated an unknown record as droppable would shed\n    \
                 /// exactly the records a newer firmware added because they mattered.\n    \
                 #[must_use]\n    \
                 pub fn is_class_a(self) -> Option<bool> {\n        \
                     EVENT_IS_CLASS_A\n            \
                         .binary_search_by_key(&self.0, |&(k, _)| k)\n            \
                         .ok()\n            \
                         .and_then(|i| EVENT_IS_CLASS_A.get(i))\n            \
                         .map(|&(_, a)| a)\n    \
                 }\n\
             }\n\n",
        );
        o
    }

    fn rust_error_sealed(&self) -> String {
        let mut o = String::new();
        o.push_str(
            "/// Whether a receiver may read this code out of a **bare** body.\n\
             ///\n\
             /// The registry's sealed column, which is the receiver's check and never\n\
             /// the sender's: P-142 decides the shape by whether the *sender* holds\n\
             /// a session, so a rule read off this column would be one the cases\n\
             /// with no session cannot obey. What it says is what a receiver will\n\
             /// accept, and a bare body carrying a code marked here is discarded\n\
             /// under P-051 rather than acted on. Sorted, so a lookup can bisect.\n\
             pub const ERROR_NEEDS_A_SEAL: &[(u16, bool)] = &[\n",
        );
        let mut coded: Vec<_> = self
            .registry
            .errors
            .iter()
            .filter(|e| e.status == Status::Live)
            .collect();
        coded.sort_by_key(|e| e.code);
        for e in coded {
            let _ = writeln!(o, "    ({}, {}),", e.code, e.sealed);
        }
        o.push_str(
            "];\n\n\
             impl ErrorCode {\n    \
                 /// Whether a receiver refuses to read this code out of a bare body.\n    \
                 #[must_use]\n    \
                 pub fn needs_a_seal(self) -> bool {\n        \
                     ERROR_NEEDS_A_SEAL\n            \
                         .binary_search_by_key(&(self as u16), |&(c, _)| c)\n            \
                         .ok()\n            .and_then(|i| ERROR_NEEDS_A_SEAL.get(i))\n            .is_some_and(|&(_, m)| m)\n    \
                 }\n\
             }\n\n",
        );

        o
    }

    /// The two spaces a client needs to act on but must not confuse with the
    /// client-facing ones: link-local errors, and the per-client mask.
    fn rust_link_and_capability(&self) -> Result<String> {
        let mut o = String::new();
        closed_enum(&mut o, "u16", &self.link_error_space()?);

        o.push_str(
            "/// A code off the wire, kept in the space it came from.\n\
             ///\n\
             /// Widening `ErrorCode` to hold the link-local range would make a\n\
             /// routing fault in the comms processor look like the client's own\n\
             /// request failing, and the two want different retries.\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             #[cfg_attr(feature = \"defmt\", derive(defmt::Format))]\n\
             pub enum Incoming {\n    \
                 /// A code from the client-facing space.\n    \
                 Client(ErrorCode),\n    \
                 /// A code from the link-local space.\n    \
                 LinkLocal(LinkErrorCode),\n    \
                 /// A code this build allocates in neither space, carried as sent.\n    \
                 Unknown(u16),\n\
             }\n\n\
             impl From<u16> for Incoming {\n    \
                 fn from(v: u16) -> Self {\n        \
                     ErrorCode::try_from(v).map_or_else(\n            \
                         |()| LinkErrorCode::try_from(v).map_or(Self::Unknown(v), Self::LinkLocal),\n            \
                         Self::Client,\n        \
                     )\n    \
                 }\n\
             }\n\n",
        );

        let bits = self.capability_space()?;
        if !bits.members.is_empty() {
            rust_doc(
                &mut o,
                "",
                &format!(
                    "{}\n\nNot a wire discriminant: an unallocated bit is a capability \
                     nobody has defined yet, not a value to reject.",
                    bits.doc
                ),
            );
            o.push_str(
                "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
                 #[cfg_attr(feature = \"defmt\", derive(defmt::Format))]\n\
                 pub struct ClientCapability(pub u16);\n\n\
                 impl ClientCapability {\n",
            );
            for bit in &bits.members {
                rust_doc(&mut o, "    ", &bit.doc);
                let _ = writeln!(
                    o,
                    "    pub const {}: Self = Self(1 << {});",
                    bit.name, bit.number
                );
            }
            o.push_str(
                "\n    /// Whether this mask holds every bit of `want`.\n    \
                 #[must_use]\n    \
                 pub fn allows(self, want: Self) -> bool {\n        \
                     self.0 & want.0 == want.0\n    \
                 }\n",
            );
            o.push_str(&self.granted(bits.members.len()));
            o.push_str("}\n\n");
        }
        Ok(o)
    }

    /// Which side may send each link-local request, from the `direction`
    /// column that until now only ever reached a table in the document.
    ///
    /// L-001 refuses the other side with the same code as an unknown opcode:
    /// from the receiver's side a message it has no business acting on is one
    /// mistake, not two, and neither firmware has to decide which kind of wrong
    /// it is looking at.
    fn link_directions(&self) -> String {
        let mut o = String::from(
            "/// Which side starts a link-local exchange.\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             #[cfg_attr(feature = \"defmt\", derive(defmt::Format))]\n\
             pub enum LinkDirection {\n    \
                 /// Either side may start it.\n    \
                 Either,\n    \
                 /// The comms processor sends the request; the controller acknowledges.\n    \
                 CommsToController,\n    \
                 /// The controller sends the request; the comms processor acknowledges.\n    \
                 ControllerToComms,\n\
             }\n\n\
             impl LinkMessageType {\n    \
                 /// Which side starts this exchange. A request and its acknowledgement\n    \
                 /// give the same answer; the acknowledgement travels the other way.\n    \
                 ///\n    \
                 /// Left unformatted for the reason `ClientCapability::granted` is:\n    \
                 /// a pattern list long enough to wrap comes back from `cargo fmt`\n    \
                 /// in a shape this generator does not emit, and then `cargo fmt`\n    \
                 /// and `cargo xtask check` cannot both be green.\n    \
                 #[rustfmt::skip]\n    \
                 #[must_use]\n    \
                 pub const fn direction(self) -> LinkDirection {\n        \
                 match self {\n",
        );
        let mut arms: Vec<(&str, Vec<String>)> = Vec::new();
        for m in &self.registry.link_messages {
            let side = match m.direction {
                crate::registry::LinkDirection::Either => "Either",
                crate::registry::LinkDirection::CommsToController => "CommsToController",
                crate::registry::LinkDirection::ControllerToComms => "ControllerToComms",
            };
            let name = variant(&m.name);
            let patterns = [
                format!("LinkMessageType::{name}"),
                format!("LinkMessageType::{name}Ack"),
            ];
            match arms.iter_mut().find(|(seen, _)| *seen == side) {
                Some((_, into)) => into.extend(patterns),
                None => arms.push((side, patterns.to_vec())),
            }
        }
        for (side, patterns) in &arms {
            for (n, pattern) in patterns.iter().enumerate() {
                let lead = if n == 0 {
                    "            "
                } else {
                    "            | "
                };
                let _ = writeln!(o, "{lead}{pattern}");
            }
            let _ = writeln!(o, "            => LinkDirection::{side},");
        }
        o.push_str("        }\n    }\n}\n\n");
        o
    }

    /// The mask each role is handed, folded out of the
    /// same `granted_to` lists that render the grid in REGISTRY.md.
    ///
    /// A grant list, so a role allocated later and mentioned by no row
    /// comes out holding nothing. Folded the other way it would come out holding
    /// everything, and the bit it would arrive with is firmware push.
    ///
    /// Emitted rather than written by hand in the controller, because a mask
    /// kept in two places is a cloud client the document says cannot push
    /// firmware and the controller lets. The bits are in the order of the
    /// constants directly above, lowest first.
    fn granted(&self, width: usize) -> String {
        let Some(kinds) = self.registry.enums.get("role") else {
            return String::new();
        };
        let mut o = String::from(
            "\n    /// The mask this role is handed.\n    \
             ///\n    \
             /// A slot's mask is its role's and nothing else: no message\n    \
             /// raises one and no message lowers one.\n    \
             ///\n    \
             /// Left unformatted: a kind list long enough to wrap would be\n    \
             /// rewritten by `cargo fmt` into something this generator does not\n    \
             /// emit, after which `cargo fmt` and `cargo xtask check` cannot\n    \
             /// both be green and the fix is not obvious from either.\n    \
             #[rustfmt::skip]\n    \
             #[must_use]\n    \
             pub const fn granted(role: Role) -> Self {\n        \
             match role {\n",
        );
        // Kinds that come out with the same mask share an arm, in first-seen
        // order. Three arms with identical bodies is what a reader has to
        // compare by eye to notice that only one of the four is restricted.
        let mut arms: Vec<(u16, Vec<String>)> = Vec::new();
        for kind in kinds.iter().filter(|k| k.status != Status::Withdrawn) {
            let mask = self
                .registry
                .client_capability
                .iter()
                .filter(|c| c.status == Some(Status::Live))
                .filter(|c| c.granted_to.contains(&kind.name))
                .filter_map(|c| c.bit)
                .filter_map(|bit| 1u16.checked_shl(u32::from(bit)))
                .fold(0u16, |mask, bit| mask | bit);
            let pattern = format!("Role::{}", variant(&kind.name));
            match arms.iter_mut().find(|(seen, _)| *seen == mask) {
                Some((_, patterns)) => patterns.push(pattern),
                None => arms.push((mask, vec![pattern])),
            }
        }
        for (mask, patterns) in &arms {
            let _ = writeln!(
                o,
                "            {} => Self(0b{}),",
                patterns.join(" | "),
                nibbles(*mask, width)
            );
        }
        o.push_str("        }\n    }\n");
        o
    }

    /// The TypeScript bindings, with a doc comment on every export and member.
    ///
    /// The npm package is all a consumer has, and it used to carry numbers
    /// with no word of what they mean: `Concerns.OutOfRange = 0x3` sent a
    /// reader to REGISTRY.md to learn which response carries it. The words
    /// come from where the registry's own document takes them, a row's columns
    /// and the paragraph REGISTRY.md opens each space with, so they cannot say
    /// something the registry does not.
    fn typescript(&self) -> Result<String> {
        let mut o = String::new();
        for line in HEADER.lines() {
            let _ = writeln!(o, "// {line}");
        }
        let _ = writeln!(o, "{}{}\n", Self::DIGEST_MARKER, self.registry.digest);

        for (name, uuid, doc) in self.registry.ble.uuids() {
            let _ = writeln!(o, "/** {doc} */\nexport const {name} = {uuid:?};\n");
        }
        for (name, value, doc) in self.registry.ble.flags() {
            let _ = writeln!(o, "/** {doc} */\nexport const {name} = {value};\n");
        }
        let (name, port, doc) = self.registry.websocket.port();
        let _ = writeln!(o, "/** {doc} */\nexport const {name} = {port};\n");
        for (name, text, doc) in self.registry.websocket.texts() {
            let _ = writeln!(o, "/** {doc} */\nexport const {name} = {text:?};\n");
        }

        for limit in self.registry.transport_limits() {
            let _ = writeln!(
                o,
                "/** {} */\nexport const {} = {};\n",
                limit.doc, limit.name, limit.value
            );
        }

        ts_enum(&mut o, &self.message_space()?);
        ts_enum(&mut o, &self.error_space()?);
        for space in self.enum_spaces()? {
            ts_enum(&mut o, &space);
        }
        for space in self.code_spaces()? {
            ts_enum(&mut o, &space);
        }

        ts_enum(&mut o, &self.link_error_space()?);
        let bits = self.capability_space()?;
        if !bits.members.is_empty() {
            ts_doc(&mut o, "", &bits.doc);
            o.push_str("export const ClientCapability = {\n");
            for bit in &bits.members {
                ts_doc(&mut o, "  ", &bit.doc);
                let _ = writeln!(o, "  {}: 1 << {},", bit.name, bit.number);
            }
            o.push_str("} as const;\n\n");
        }
        o.push_str(&self.ts_open_sets()?);
        Ok(o)
    }

    /// The open spaces and the unit table, for the same reason `rust_open_sets`
    /// exists.
    fn ts_open_sets(&self) -> Result<String> {
        let mut o = String::new();
        ts_const_map(&mut o, &self.metric_space()?);
        ts_const_map(&mut o, &self.event_space()?);
        for space in self.open_registry_spaces()? {
            ts_const_map(&mut o, &space);
        }

        ts_doc(
            &mut o,
            "",
            "The unit and scale of every metric kind, keyed by kind: \
             `value = raw × 10^scale`.",
        );
        o.push_str("export const metricUnits: Record<number, readonly [string, number]> = {\n");
        for m in &self.registry.metrics {
            let _ = writeln!(o, "  {:#06x}: [\"{}\", {}],", m.kind, m.unit, m.scale);
        }
        o.push_str("};\n");
        o.push_str(&self.ts_dataset());
        Ok(o)
    }

    /// The name the registry gives a signal domain value, for the generated
    /// variant. A value the crosswalk resolved always exists, so an unknown one
    /// renders as its number and fails to compile rather than passing silently.
    fn domain_name(&self, value: u8) -> String {
        self.registry
            .enums
            .get("signal_domain")
            .and_then(|rows| rows.iter().find(|r| r.value == value))
            .map_or_else(|| value.to_string(), |r| r.name.clone())
    }

    /// The same crosswalk for a client, most specific row first.
    fn ts_dataset(&self) -> String {
        let mut o = String::new();
        o.push_str(
            "\n/**\n \
             * The public equipment dataset's word for a reading: a metric kind over a\n \
             * signal domain, at a place. An undefined place matches any; the domain never\n \
             * does, so a limit or a period counter cannot borrow a live reading's word.\n \
             */\n\
             export interface DatasetMetric {\n  \
                 /** A {@link MetricKind} value. */\n  \
                 readonly kind: number;\n  \
                 /** A {@link SignalDomain} value, matched exactly. */\n  \
                 readonly domain: number;\n  \
                 /** A {@link ComponentRole} value, or undefined to match any role. */\n  \
                 readonly role?: number;\n  \
                 /** A {@link MeasurementPoint} value, or undefined to match any point. */\n  \
                 readonly point?: number;\n  \
                 /** The dataset's word, such as `pv-voltage`. */\n  \
                 readonly name: string;\n\
             }\n\n\
             /** Every dataset word a metric carries, most specific row first. */\n\
             export const datasetMetrics: readonly DatasetMetric[] = [\n",
        );
        for c in &self.registry.crosswalk.carried {
            let mut row = format!("  {{ kind: {:#06x}, domain: {:#04x}", c.kind, c.domain);
            if let Some(role) = c.role {
                let _ = write!(row, ", role: {role:#06x}");
            }
            if let Some(point) = c.point {
                let _ = write!(row, ", point: {point:#06x}");
            }
            let _ = writeln!(o, "{row}, name: {} }},", js(&c.name));
        }
        o.push_str(
            "];\n\n/** Dataset words no metric carries, each with why. */\n\
             export const datasetAbsent: Readonly<Record<string, string>> = {\n",
        );
        for (name, why) in &self.registry.crosswalk.absent {
            let _ = writeln!(o, "  {}: {},", js(name), js(why));
        }
        o.push_str(
            "};\n\n\
             /**\n \
             * The dataset's word for a reading, or undefined when it has none. The first\n \
             * matching row of {@link datasetMetrics} wins, which is why it is ordered most\n \
             * specific first.\n \
             */\n\
             export function datasetName(\n  \
                 kind: number,\n  \
                 domain: number,\n  \
                 role?: number,\n  \
                 point?: number,\n\
             ): string | undefined {\n  \
                 return datasetMetrics.find(\n    \
                     (m) =>\n      \
                         m.kind === kind &&\n      \
                         m.domain === domain &&\n      \
                         (m.role === undefined || m.role === role) &&\n      \
                         (m.point === undefined || m.point === point),\n  \
                 )?.name;\n\
             }\n",
        );
        o
    }
}

/// The paragraph every open space's doc ends with.
const OPEN: &str = "Open: a device may emit a value this table does not name, and a client \
                    shows that one carrier as unrecognised rather than blanking the message \
                    around it.";

/// REGISTRY.md, read for the paragraph each space opens with.
struct RegistryDoc(String);

impl RegistryDoc {
    /// Where a relative link in REGISTRY.md points once it is out of the repository.
    const REPOSITORY: &'static str = "https://github.com/origin89hq/km43/blob/main/";

    /// The first paragraph under `heading`, which is where REGISTRY.md says what
    /// a space is before it argues about it.
    ///
    /// A section that opens straight into its table is refused rather than
    /// emitted bare: that is the undocumented export the bindings exist to stop
    /// shipping, and the fix is a sentence in REGISTRY.md that both readers get.
    fn summary(&self, heading: &str) -> Result<String> {
        let mut lines = self
            .0
            .lines()
            .skip_while(|l| *l != heading && !l.starts_with(&format!("{heading} ")));
        lines
            .next()
            .with_context(|| format!("{} has no {heading:?} section", Codegen::PATH))?;
        let paragraph: Vec<&str> = lines
            .skip_while(|l| l.trim().is_empty())
            .take_while(|l| !l.trim().is_empty())
            .collect();
        match paragraph.first() {
            Some(first) if !first.starts_with('|') && !first.starts_with('#') => {
                Ok(Self::absolute_links(&paragraph.join("\n")))
            }
            _ => anyhow::bail!(
                "{heading:?} in {} opens with no paragraph, so the TypeScript export it \
                 generates would ship undocumented. Write the sentence that says what the \
                 space is above its table.",
                Codegen::PATH
            ),
        }
    }

    /// Relative Markdown links, rewritten to the repository: they resolve against
    /// `docs/protocol/` in REGISTRY.md and against nothing in the npm package.
    fn absolute_links(text: &str) -> String {
        let mut out = String::with_capacity(text.len());
        let mut rest = text;
        while let Some(at) = rest.find("](") {
            let (head, tail) = rest.split_at(at + 2);
            out.push_str(head);
            rest = tail;
            if rest.starts_with("http") || rest.starts_with('#') {
                continue;
            }
            out.push_str(Self::REPOSITORY);
            match rest.strip_prefix("../") {
                Some(up) => {
                    out.push_str("docs/");
                    rest = up;
                }
                None => out.push_str("docs/protocol/"),
            }
        }
        out.push_str(rest);
        out
    }
}

/// An open space's summary with the paragraph that says it is open.
fn open(summary: &str) -> String {
    format!("{summary}\n\n{OPEN}")
}

/// One generated space: its type name, what it is, and its members.
///
/// Built once and rendered by both languages. When each emitter took its words
/// from the registry on its own, the TypeScript had them and the Rust had bare
/// numbers, and nothing noticed.
struct Space {
    name: String,
    doc: String,
    members: Vec<Member>,
}

/// One generated constant: its name, its number, and what it means.
struct Member {
    name: String,
    number: u16,
    doc: String,
}

/// The doc of a row with no meaning column: its registry name, as code. Bare,
/// `refused_busy` reads to rustdoc's pedantic lint as an identifier somebody
/// forgot to quote, and to a person as the same.
fn named(name: &str) -> String {
    format!("`{name}`")
}

/// An outcome or enum row's meaning, or its name where it has none.
fn outcome_members(entries: &[crate::registry::Outcome]) -> Vec<Member> {
    entries
        .iter()
        .filter(|e| !e.status.is_gone())
        .map(|e| Member {
            name: variant(&e.name),
            number: u16::from(e.value),
            doc: with_caveat(
                &e.meaning
                    .as_deref()
                    .map_or_else(|| named(&e.name), sentence),
                Some(e.status),
            ),
        })
        .collect()
}

/// A message's request and response constants, each saying how it is
/// authenticated and which constant answers it.
fn message_members(m: &Message) -> [Option<Member>; 2] {
    let name = variant(&m.name);
    let auth =
        |a: Option<Auth>| a.map_or_else(String::new, |a| format!(" Auth `{a}`. {}", a.summary()));
    let tail = format!(" Since {}.", m.since);
    let request = m.request.map(|r| {
        let answered = m.response.map_or_else(String::new, |_| {
            format!(" Answered by {{@link MessageType.{name}Response}}.")
        });
        Member {
            name: name.clone(),
            number: r.0,
            doc: with_caveat(
                &format!(
                    "The `{}` request.{}{answered}{tail}",
                    m.name,
                    auth(m.auth_request)
                ),
                Some(m.status),
            ),
        }
    });
    let response = m.response.map(|r| {
        let what = if m.request.is_some() {
            format!("The answer to {{@link MessageType.{name}}}.")
        } else {
            format!("The `{}` message.", m.name)
        };
        Member {
            name: format!("{name}Response"),
            number: r.0,
            doc: with_caveat(
                &format!("{what}{}{tail}", auth(m.auth_response)),
                Some(m.status),
            ),
        }
    });
    [request, response]
}

/// An error code's meaning and what the sealed column says about it.
///
/// The column is the receiver's check, never the sender's: P-142 wraps an
/// `Error` whenever the sender holds a session, whatever the code. Reading it
/// as *this code travels bare* would tell a client to reject a valid wrapped
/// error, or a controller to send an unauthenticated one inside a session.
fn error_doc(meaning: &str, sealed: bool) -> String {
    let rule = if sealed {
        "A receiver accepts it only inside a sealed body, and discards a bare one \
         carrying it (P-051)."
    } else {
        "A receiver may also accept it from a bare body."
    };
    format!(
        "{} {rule} Whether it arrives sealed is decided by whether the sender holds \
         a session, not by the code (P-142).",
        sentence(meaning)
    )
}

/// What a metric kind is read in. `—` is the registry's word for a value that
/// is not a quantity, such as a state drawn from an enum space.
fn metric_doc(name: &str, unit: &str, scale: i8) -> String {
    let name = sentence(&capital(name));
    match (unit, scale) {
        ("—", _) => format!("{name} No unit."),
        (unit, 0) => format!("{name} Unit `{unit}`."),
        (unit, scale) => format!("{name} Unit `{unit}`, `value = raw × 10^{scale}`."),
    }
}

/// A row's text with its status caveat as a second paragraph, when it has one.
fn with_caveat(text: &str, status: Option<Status>) -> String {
    match status.and_then(Status::caveat) {
        Some(caveat) => format!("{text}\n\n{caveat}"),
        None => text.to_owned(),
    }
}

/// Registry text as a sentence. `meaning` columns are written as table cells,
/// without a closing full stop.
fn sentence(text: &str) -> String {
    let text = text.trim_end();
    if text.ends_with('.') {
        text.to_owned()
    } else {
        format!("{text}.")
    }
}

fn capital(text: &str) -> String {
    let mut c = text.chars();
    c.next().map_or_else(String::new, |f| {
        f.to_uppercase().collect::<String>() + c.as_str()
    })
}

/// A `/** */` comment, wrapped to 80 columns, one paragraph per blank line.
///
/// Registry text can carry a `*/`, which would end the comment and hand the
/// rest of the row to the compiler, and an `@`, which `TSDoc` reads as a tag.
/// Both are escaped; the generator's own `{@link}` is put back.
fn ts_doc(o: &mut String, indent: &str, text: &str) {
    let text = text
        .replace("*/", "*\\/")
        .replace('@', "\\@")
        .replace("{\\@link ", "{@link ");
    let width = 80usize.saturating_sub(indent.len() + 3);
    let paragraphs = wrap(&text, width);
    if let [only] = paragraphs.as_slice()
        && let [line] = only.as_slice()
        && columns(line) + 4 <= width
    {
        let _ = writeln!(o, "{indent}/** {line} */");
        return;
    }
    let _ = writeln!(o, "{indent}/**");
    for (n, lines) in paragraphs.iter().enumerate() {
        if n > 0 {
            let _ = writeln!(o, "{indent} *");
        }
        for line in lines {
            let _ = writeln!(o, "{indent} * {line}");
        }
    }
    let _ = writeln!(o, "{indent} */");
}

/// A `///` comment, wrapped to 80 columns, one paragraph per blank line.
///
/// Each line carries its own `///`, so a newline in registry text cannot hand
/// the rest of the row to the compiler the way `*/` could in TypeScript. What
/// it can do is be read as rustdoc markup; [`rust_markdown`] disarms that.
/// Empty text writes nothing, so `missing_docs` sees the gap.
fn rust_doc(o: &mut String, indent: &str, text: &str) {
    let width = 80usize.saturating_sub(indent.len() + 4);
    for (n, lines) in wrap(&rust_markdown(text), width).iter().enumerate() {
        if n > 0 {
            let _ = writeln!(o, "{indent}///");
        }
        for line in lines {
            let _ = writeln!(o, "{indent}/// {line}");
        }
    }
}

/// Registry text as rustdoc Markdown.
///
/// Rustdoc reads a stray `[word]` as an intra-doc link and `<word>` as an HTML
/// tag, and under `-D warnings` a broken one of either fails `just doc`, so
/// both are escaped outside code spans; a Markdown link is kept. The
/// generator's own `{@link A.B}` becomes the rustdoc link ``[`A::B`]``.
fn rust_markdown(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut code = false;
    let mut rest = text;
    while let Some(c) = rest.chars().next() {
        let after = rest.get(c.len_utf8()..).unwrap_or_default();
        match c {
            '`' => code = !code,
            '{' if !code && rest.starts_with("{@link ") => {
                if let Some((target, tail)) =
                    after.strip_prefix("@link ").and_then(|t| t.split_once('}'))
                {
                    let _ = write!(out, "[`{}`]", target.replace('.', "::"));
                    rest = tail;
                    continue;
                }
            }
            '[' if !code => {
                if let Some(end) = markdown_link_end(rest) {
                    let (link, tail) = rest.split_at(end);
                    out.push_str(link);
                    rest = tail;
                    continue;
                }
                out.push('\\');
            }
            ']' | '<' | '>' if !code => out.push('\\'),
            _ => {}
        }
        out.push(c);
        rest = after;
    }
    out
}

/// The byte length of the Markdown link `text` opens with, if it opens with one.
fn markdown_link_end(text: &str) -> Option<usize> {
    let close = text.find("](")?;
    let label = text.get(1..close)?;
    if label.contains(['[', ']', '\n']) {
        return None;
    }
    let url = text.get(close + 2..)?;
    let end = url.find(')')?;
    if url.get(..end)?.contains(char::is_whitespace) {
        return None;
    }
    Some(close + 2 + end + 1)
}

/// Text in paragraphs of lines no wider than `width`, split on blank lines.
fn wrap(text: &str, width: usize) -> Vec<Vec<String>> {
    text.split("\n\n")
        .map(|p| {
            let mut lines: Vec<String> = Vec::new();
            for word in words_of(p) {
                match lines.last_mut() {
                    Some(line) if columns(line) + 1 + columns(&word) <= width => {
                        line.push(' ');
                        line.push_str(&word);
                    }
                    _ => lines.push(word),
                }
            }
            lines
        })
        .filter(|lines| !lines.is_empty())
        .collect()
}

/// A closed space: an unknown value is a parse error, never a fallback.
fn closed_enum(o: &mut String, repr: &str, space: &Space) {
    if space.members.is_empty() {
        return;
    }
    let name = &space.name;
    rust_doc(o, "", &space.doc);
    let _ = writeln!(o, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
    let _ = writeln!(
        o,
        r#"#[cfg_attr(feature = "defmt", derive(defmt::Format))]"#
    );
    let _ = writeln!(o, "#[repr({repr})]");
    let _ = writeln!(o, "pub enum {name} {{");
    for m in &space.members {
        rust_doc(o, "    ", &m.doc);
        let _ = writeln!(o, "    {} = {:#x},", m.name, m.number);
    }
    let _ = writeln!(o, "}}\n");
    let _ = writeln!(o, "impl TryFrom<{repr}> for {name} {{");
    let _ = writeln!(o, "    type Error = ();\n");
    let _ = writeln!(
        o,
        "    fn try_from(v: {repr}) -> Result<Self, Self::Error> {{"
    );
    let _ = writeln!(o, "        match v {{");
    for m in &space.members {
        let _ = writeln!(o, "            {:#x} => Ok(Self::{}),", m.number, m.name);
    }
    let _ = writeln!(o, "            _ => Err(()),\n        }}\n    }}\n}}\n");
}

/// An open space: the value is carried whether or not it is named.
fn open_newtype(o: &mut String, space: &Space, open: bool) {
    if !open {
        return;
    }
    let name = &space.name;
    rust_doc(o, "", &space.doc);
    let _ = writeln!(o, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
    let _ = writeln!(
        o,
        r#"#[cfg_attr(feature = "defmt", derive(defmt::Format))]"#
    );
    let _ = writeln!(o, "pub struct {name}(pub u16);\n");
    let _ = writeln!(o, "impl {name} {{");
    for m in &space.members {
        rust_doc(o, "    ", &m.doc);
        let _ = writeln!(
            o,
            "    pub const {}: Self = Self({:#06x});",
            m.name, m.number
        );
    }
    let _ = writeln!(o, "}}\n");
}

fn ts_enum(o: &mut String, space: &Space) {
    if space.members.is_empty() {
        return;
    }
    ts_doc(o, "", &space.doc);
    let _ = writeln!(o, "export enum {} {{", space.name);
    for m in &space.members {
        ts_doc(o, "  ", &m.doc);
        let _ = writeln!(o, "  {} = {:#x},", m.name, m.number);
    }
    let _ = writeln!(o, "}}\n");
}

fn ts_const_map(o: &mut String, space: &Space) {
    ts_doc(o, "", &space.doc);
    let _ = writeln!(o, "export const {} = {{", space.name);
    for m in &space.members {
        ts_doc(o, "  ", &m.doc);
        let _ = writeln!(o, "  {}: {:#06x},", m.name, m.number);
    }
    let _ = writeln!(o, "}} as const;\n");
}

/// The words a doc comment wraps between. `{@link X}` is one: `TSDoc` reads an
/// inline tag split across two lines, but a reader grepping for it does not.
fn words_of(paragraph: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for word in paragraph.split_whitespace() {
        match out.last_mut() {
            Some(last) if last.ends_with("{@link") => {
                last.push(' ');
                last.push_str(word);
            }
            _ => out.push(word.to_owned()),
        }
    }
    out
}

/// Width as a reader sees it: `—` is three bytes and one column.
fn columns(text: &str) -> usize {
    text.chars().count()
}

/// `battery voltage` becomes `BatteryVoltage`, which is what a Rust variant and
/// a TypeScript member both want.
///
/// A parenthetical is a note rather than part of the name — `battery current
/// (+ charge, − discharge)` is `BatteryCurrent` — and everything that is not a
/// letter or a digit is a separator.
fn variant(s: &str) -> String {
    words(s)
        .map(|w| {
            // Only the first letter is touched: `ReadLog` is already the name
            // somebody wrote, and lowercasing the rest gives `Readlog`.
            let mut c = w.chars();
            c.next().map_or_else(String::new, |f| {
                f.to_ascii_uppercase().to_string() + c.as_str()
            })
        })
        .collect()
}

/// The same name as a constant: `battery voltage` becomes `BATTERY_VOLTAGE`.
fn screaming(s: &str) -> String {
    words(s)
        .map(str::to_ascii_uppercase)
        .collect::<Vec<_>>()
        .join("_")
}

fn words(s: &str) -> impl Iterator<Item = &str> {
    s.split_once('(')
        .map_or(s, |(before, _)| before)
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty())
}

/// A JavaScript string literal for `s`: a JSON string is one, with quotes,
/// backslashes and control characters escaped.
fn js(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".to_owned())
}

/// A mask in binary, `width` digits wide and grouped in fours from the right,
/// the way clippy's `unreadable_literal` wants a literal of five digits or more.
fn nibbles(mask: u16, width: usize) -> String {
    let digits = format!("{mask:0width$b}");
    let mut out = String::with_capacity(digits.len() + digits.len() / 4);
    for (index, digit) in digits.chars().enumerate() {
        if index > 0 && (digits.len() - index) % 4 == 0 {
            out.push('_');
        }
        out.push(digit);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A mask of eight bits or more comes out grouped, or clippy's pedantic
    /// `unreadable_literal` fires on the generated file and the gate is red.
    #[test]
    fn a_wide_mask_is_grouped_in_fours_from_the_right() {
        assert_eq!(nibbles(0b0111_1101, 8), "0111_1101");
        assert_eq!(nibbles(0b1_0000_0001, 9), "1_0000_0001");
    }

    /// Four digits or fewer need no separator, and an empty mask keeps its width.
    #[test]
    fn a_narrow_or_empty_mask_is_left_alone() {
        assert_eq!(nibbles(0b101, 4), "0101");
        assert_eq!(nibbles(0, 8), "0000_0000");
        assert_eq!(nibbles(0, 1), "0");
    }

    fn space(name: &str, doc: &str, members: &[(&str, u16, &str)]) -> Space {
        Space {
            name: name.to_owned(),
            doc: doc.to_owned(),
            members: members
                .iter()
                .map(|&(name, number, doc)| Member {
                    name: name.to_owned(),
                    number,
                    doc: doc.to_owned(),
                })
                .collect(),
        }
    }

    /// Open and closed are different shapes in the generated code, and the difference is
    /// what a decoder does with a number nobody has allocated: a newtype carries it, an
    /// enum refuses the message around it.
    ///
    /// Written against the emitter rather than against a second copy of the rule, because
    /// the rule this replaced — a list of space names read in one place — could be wrong
    /// in the file and right in every test that quoted it.
    #[test]
    fn an_open_space_emits_a_newtype_and_a_closed_one_emits_an_enum() {
        let mut open = String::new();
        open_newtype(
            &mut open,
            &space(
                "ComponentRole",
                "Roles.",
                &[("PV_ARRAY", 0x0001, "`pv array`")],
            ),
            true,
        );
        assert!(
            open.contains("pub struct ComponentRole(pub u16);"),
            "an open space is a newtype over the full width, so a vendor value survives"
        );
        assert!(
            open.contains("pub const PV_ARRAY: Self = Self(0x0001);"),
            "and the names it does know are constants on it"
        );

        let mut closed = String::new();
        closed_enum(
            &mut closed,
            "u8",
            &space("Severity", "Bands.", &[("Warning", 2, "`warning`")]),
        );
        assert!(
            closed.contains("enum Severity"),
            "a closed space is an enum, so an unallocated value is a parse error"
        );
        assert!(!closed.contains("pub struct Severity"), "and never both");
    }

    /// `open` is not a flag that can be set in one file and read in another. This is the
    /// property the whole change exists for: there is no second place to keep in sync.
    #[test]
    fn an_open_space_declares_itself_by_the_table_it_is_in() {
        let mut nothing = String::new();
        open_newtype(
            &mut nothing,
            &space(
                "MetricKind",
                "Kinds.",
                &[("BATTERY_VOLTAGE", 0x0101, "Volts.")],
            ),
            false,
        );
        assert!(
            nothing.is_empty(),
            "the two top-level tables are still gated, and that gate is now checked at load"
        );
    }

    /// `ErrorCode::BadMac` used to reach rustdoc as a bare number. The enum and
    /// every variant now carry their words, directly above the item they
    /// describe, and a reserved row keeps its caveat as a second paragraph.
    #[test]
    fn a_closed_enum_documents_itself_and_every_variant() {
        let mut o = String::new();
        closed_enum(
            &mut o,
            "u16",
            &space(
                "ErrorCode",
                "Carried in `Error 0xFF`.",
                &[
                    ("BadMac", 0x2, "Bad MAC."),
                    (
                        "Later",
                        0x9,
                        "`later`\n\nReserved: allocated, and not specified yet.",
                    ),
                ],
            ),
        );
        assert!(
            o.starts_with("/// Carried in `Error 0xFF`.\n#[derive("),
            "the space's doc sits on the enum: {o}"
        );
        assert!(o.contains("    /// Bad MAC.\n    BadMac = 0x2,\n"), "{o}");
        assert!(
            o.contains(
                "    /// `later`\n    ///\n    /// Reserved: allocated, and not specified yet.\n    Later = 0x9,\n"
            ),
            "{o}"
        );
        assert!(
            !o.contains("impl TryFrom<u16> for ErrorCode {\n    ///"),
            "a trait impl needs no doc and gets none: {o}"
        );
    }

    /// An open space's constants are documented as the enum's variants are, and
    /// the struct says the space is open.
    #[test]
    fn an_open_newtype_documents_itself_and_every_constant() {
        let mut o = String::new();
        open_newtype(
            &mut o,
            &space(
                "MetricKind",
                &open("What a reading is."),
                &[(
                    "DC_VOLTAGE",
                    0x0101,
                    "DC voltage. Unit `V`, `value = raw × 10^-3`.",
                )],
            ),
            true,
        );
        assert!(
            o.starts_with("/// What a reading is.\n///\n/// Open: a device may emit"),
            "{o}"
        );
        assert!(
            o.contains(
                "    /// DC voltage. Unit `V`, `value = raw × 10^-3`.\n    pub const DC_VOLTAGE: Self = Self(0x0101);\n"
            ),
            "{o}"
        );
    }

    /// An empty space emits nothing rather than an enum with no variants, and a
    /// member with no words gets no `///` at all, so `missing_docs` reports it
    /// instead of a blank comment passing for one.
    #[test]
    fn nothing_to_say_writes_no_comment() {
        let mut empty = String::new();
        closed_enum(&mut empty, "u8", &space("Nothing", "Doc.", &[]));
        assert!(empty.is_empty(), "{empty}");

        let mut bare = String::new();
        rust_doc(&mut bare, "    ", "");
        rust_doc(&mut bare, "    ", " \n\n ");
        assert!(bare.is_empty(), "{bare:?}");
    }

    /// Both bindings render one [`Space`], so they say the same words about one
    /// number. Stripped of comment markers, rewrapped, and with each language's
    /// link spelling mapped back, the two comments are the same text.
    #[test]
    fn the_rust_and_typescript_comments_carry_the_same_words() {
        let doc = "The `Hello` request. Auth `handshake`. Carries a Noise handshake \
                   message, authenticated by the handshake itself (P-054, P-057). \
                   Answered by {@link MessageType.HelloResponse}. Since 1.0.\n\n\
                   Reserved: allocated, and not specified yet.";
        let words = |text: &str, strip: &[&str]| -> Vec<String> {
            text.lines()
                .map(|l| {
                    strip
                        .iter()
                        .fold(l.trim(), |l, s| l.trim_start_matches(s).trim())
                })
                .flat_map(str::split_whitespace)
                .map(|w| {
                    w.replace(
                        "[`MessageType::HelloResponse`]",
                        "{@link MessageType.HelloResponse}",
                    )
                })
                .collect::<Vec<_>>()
                .join(" ")
                .replace("{@link MessageType.HelloResponse}", "LINK")
                .split_whitespace()
                .map(str::to_owned)
                .collect()
        };
        let mut rust = String::new();
        rust_doc(&mut rust, "    ", doc);
        let mut ts = String::new();
        ts_doc(&mut ts, "  ", doc);
        let rust = words(&rust, &["///"]);
        let ts = words(&ts, &["/**", "*/", "*"]);
        assert_eq!(rust, ts);
        assert!(rust.contains(&"LINK.".to_owned()), "{rust:?}");
        assert_eq!(rust.first().map(String::as_str), Some("The"));
    }

    /// The direction column says who starts a link exchange, so the answer
    /// comes back the other way. The first draft of these docs reused the
    /// request's sender for its `Ack` and told a reader the comms processor
    /// sends `ClientConnectedAck`, the frame `linklocal::permitted` refuses from
    /// it.
    #[test]
    fn a_link_acknowledgement_is_documented_as_sent_by_the_other_side() {
        let root = crate::check::repo_root().expect("a repo to read the registry from");
        let space = Bindings::load(&root)
            .expect("the registry and REGISTRY.md load")
            .link_message_space();
        let doc = |name: &str| {
            space
                .members
                .iter()
                .find(|m| m.name == name)
                .map_or_else(|| panic!("{name} is a link message"), |m| m.doc.clone())
        };
        assert!(
            doc("ClientConnected").contains("Only the comms processor sends it;"),
            "{}",
            doc("ClientConnected")
        );
        assert!(
            doc("ClientConnectedAck").contains("Only the controller sends it, in answer;"),
            "{}",
            doc("ClientConnectedAck")
        );
        assert!(
            doc("LinkUpAck").contains("whichever side received the request"),
            "{}",
            doc("LinkUpAck")
        );
    }

    /// Rustdoc reads a stray `[x]` as an intra-doc link and `<x>` as an HTML
    /// tag, and `just doc` denies both when they do not resolve. Registry text
    /// holding either must come out escaped, while a real Markdown link, a code
    /// span and the generator's own `{@link}` come out working.
    #[test]
    fn registry_text_cannot_open_a_link_or_a_tag_in_rustdoc() {
        assert_eq!(
            rust_markdown("a [note] and <b>"),
            "a \\[note\\] and \\<b\\>"
        );
        assert_eq!(
            rust_markdown("see [LINK.md](https://example.com/LINK.md)."),
            "see [LINK.md](https://example.com/LINK.md)."
        );
        assert_eq!(rust_markdown("`[u8; 4] <T>` stays"), "`[u8; 4] <T>` stays");
        assert_eq!(
            rust_markdown("Answered by {@link MessageType.HelloResponse}."),
            "Answered by [`MessageType::HelloResponse`]."
        );
        assert_eq!(rust_markdown("[unclosed](no end"), "\\[unclosed\\](no end");
        assert_eq!(rust_markdown("{@link unterminated"), "{@link unterminated");
        assert_eq!(rust_markdown(""), "");
    }

    /// Each comment line carries its own `///`, so a newline in registry text
    /// cannot leave a line of it outside the comment where the compiler would
    /// read it as code. Lines stay inside 80 columns, `—` counted as one.
    #[test]
    fn every_line_of_a_rust_doc_is_a_comment_inside_eighty_columns() {
        let mut o = String::new();
        let text = format!(
            "{}\npub fn injected() {{}}\n\nReserved: allocated, and not specified yet.",
            "word — ".repeat(30)
        );
        rust_doc(&mut o, "    ", &text);
        for line in o.lines() {
            assert!(line.starts_with("    ///"), "{line:?} escaped the comment");
            assert!(
                line.chars().count() <= 80,
                "{line:?} is wider than 80 columns"
            );
        }
        assert!(
            o.contains("\n    ///\n    /// Reserved"),
            "paragraphs stay apart: {o}"
        );
    }

    const DOC: &str = "# Registry\n\
        \n\
        ## Quality — `u8`\n\
        \n\
        How far a reading can be trusted, see [Cargo.toml](../Cargo.toml)\n\
        and [main.rs](main.rs).\n\
        \n\
        A second paragraph that argues about it.\n\
        \n\
        | Value | Name |\n\
        |---|---|\n\
        \n\
        ## Pair outcomes — `u8`\n\
        \n\
        | Value | Name |\n\
        |---|---|\n";

    /// The summary is the first paragraph and only that: the argument after it
    /// belongs to REGISTRY.md, and a heading carrying its width still matches.
    #[test]
    fn a_summary_is_the_first_paragraph_under_its_heading() {
        let doc = RegistryDoc(DOC.to_owned());
        let summary = doc
            .summary("## Quality")
            .expect("Quality opens with a paragraph");
        assert!(summary.starts_with("How far a reading can be trusted"));
        assert!(
            !summary.contains("second paragraph"),
            "the argument that follows is not the summary: {summary}"
        );
    }

    /// A section that opens straight into its table used to generate a bare
    /// enum. Now it stops the generator, naming the section to write.
    #[test]
    fn a_section_that_opens_with_its_table_is_refused() {
        let doc = RegistryDoc(DOC.to_owned());
        let err = doc
            .summary("## Pair outcomes")
            .expect_err("a table is not a summary")
            .to_string();
        assert!(err.contains("Pair outcomes"), "{err}");
    }

    /// A space whose heading is missing is not a space with an empty summary.
    #[test]
    fn a_heading_that_is_not_there_is_refused() {
        let doc = RegistryDoc(DOC.to_owned());
        assert!(doc.summary("## Time outcomes").is_err());
        assert!(
            doc.summary("## Qual").is_err(),
            "a prefix of a heading is not the heading"
        );
    }

    /// A link to `LINK.md` resolves against `docs/protocol/` in the repository
    /// and against nothing in the npm package, so it is made absolute. A link
    /// that already is, or that points into the page, is left alone.
    #[test]
    fn relative_links_are_made_absolute_and_absolute_ones_are_left() {
        let base = RegistryDoc::REPOSITORY;
        assert_eq!(
            RegistryDoc::absolute_links("[main.rs](main.rs) and [P](../Cargo.toml)"),
            format!("[main.rs]({base}docs/protocol/main.rs) and [P]({base}docs/Cargo.toml)")
        );
        let untouched = "[x](https://example.com/a.md) [y](#units) plain text";
        assert_eq!(RegistryDoc::absolute_links(untouched), untouched);
        assert_eq!(RegistryDoc::absolute_links(""), "");
    }

    /// A short doc stays on one line; a long one wraps inside 80 columns with
    /// paragraphs kept apart, counting `—` as the one column it takes.
    #[test]
    fn a_doc_comment_wraps_to_eighty_columns() {
        let mut short = String::new();
        ts_doc(&mut short, "  ", "Acted on.");
        assert_eq!(short, "  /** Acted on. */\n");

        let mut long = String::new();
        let text = format!(
            "{}\n\nReserved: allocated, and not specified yet.",
            "word — ".repeat(30)
        );
        ts_doc(&mut long, "  ", &text);
        assert!(
            long.starts_with("  /**\n") && long.ends_with("  */\n"),
            "{long}"
        );
        assert!(
            long.contains("\n   *\n   * Reserved"),
            "paragraphs stay apart: {long}"
        );
        for line in long.lines() {
            assert!(
                line.chars().count() <= 80,
                "{line:?} is wider than 80 columns"
            );
        }
    }

    /// A `*/` in a meaning would close the comment and hand the rest of the row
    /// to the TypeScript compiler; an `@` would be read as a `TSDoc` tag. The
    /// generator's own `{@link}` has to survive the escaping.
    #[test]
    fn registry_text_cannot_close_the_comment_or_open_a_tag() {
        let mut o = String::new();
        ts_doc(
            &mut o,
            "",
            "Ends */ early, mails @someone, see {@link MessageType.Hello}.",
        );
        assert!(o.contains("Ends *\\/ early"), "{o}");
        assert!(o.contains("\\@someone"), "{o}");
        assert!(o.contains("{@link MessageType.Hello}"), "{o}");
        assert_eq!(o.matches("*/").count(), 1, "only the closing one: {o}");
    }

    /// `{@link X}` wraps as one word, so it is never split across two lines.
    #[test]
    fn a_link_tag_is_never_split_across_lines() {
        assert_eq!(
            words_of("Answered by {@link MessageType.HelloResponse}. Since 1.0."),
            [
                "Answered",
                "by",
                "{@link MessageType.HelloResponse}.",
                "Since",
                "1.0."
            ]
        );
        assert!(words_of("  ").is_empty());
    }

    /// `—` is the registry's word for a value that is no quantity, and a scale
    /// of 0 has no formula worth printing.
    #[test]
    fn a_metric_says_its_unit_and_scale_only_where_it_has_them() {
        assert_eq!(
            metric_doc("DC voltage", "V", -3),
            "DC voltage. Unit `V`, `value = raw × 10^-3`."
        );
        assert_eq!(metric_doc("AC energy", "Wh", 0), "AC energy. Unit `Wh`.");
        assert_eq!(
            metric_doc("last boot reason", "—", 0),
            "Last boot reason. No unit."
        );
    }

    /// The sealed column says what a receiver accepts bare. It was once rendered
    /// as *a receiver reads it out of a bare body*, which a client could take
    /// as licence to reject the wrapped form P-142 requires inside a session.
    #[test]
    fn an_error_code_never_says_it_travels_bare() {
        let bare = error_doc("Session expired", false);
        assert!(
            bare.starts_with("Session expired. A receiver may also accept it"),
            "{bare}"
        );
        assert!(bare.contains("(P-142)"), "{bare}");

        let sealed = error_doc("Unknown section", true);
        assert!(
            sealed.contains("discards a bare one carrying it (P-051)"),
            "{sealed}"
        );
        assert!(sealed.contains("(P-142)"), "{sealed}");

        assert!(error_doc("", false).starts_with(". A receiver"));
    }

    /// A reserved number is in the bindings because a peer may send it, and
    /// without the caveat it reads as specified.
    #[test]
    fn a_reserved_row_says_so_and_a_live_one_does_not() {
        assert_eq!(with_caveat("Acted on.", Some(Status::Live)), "Acted on.");
        assert_eq!(with_caveat("pv array", None), "pv array");
        assert_eq!(
            with_caveat("accepted", Some(Status::Reserved)),
            "accepted\n\nReserved: allocated, and not specified yet."
        );
    }

    /// Each half of a message points at the other, and a message with no
    /// request, `Event`, does not claim to answer one.
    #[test]
    fn a_message_links_its_request_and_response() {
        let hello = Message {
            name: "Hello".to_owned(),
            request: Some(crate::registry::Opcode(0x01)),
            response: Some(crate::registry::Opcode(0x81)),
            auth_request: Some(Auth::Handshake),
            auth_response: Some(Auth::Handshake),
            status: Status::Live,
            since: crate::registry::Version { major: 1, minor: 0 },
        };
        let [Some(request), Some(response)] = message_members(&hello) else {
            panic!("Hello has both halves");
        };
        assert!(
            request.doc.contains("{@link MessageType.HelloResponse}"),
            "{}",
            request.doc
        );
        assert!(request.doc.contains("Auth `handshake`"), "{}", request.doc);
        assert!(
            response.doc.contains("{@link MessageType.Hello}"),
            "{}",
            response.doc
        );

        let event = Message {
            name: "Event".to_owned(),
            request: None,
            response: Some(crate::registry::Opcode(0x04)),
            auth_request: None,
            auth_response: Some(Auth::Sealed),
            ..hello
        };
        let [None, Some(only)] = message_members(&event) else {
            panic!("Event is a response with no request");
        };
        assert!(!only.doc.contains("{@link"), "{}", only.doc);
    }
}
