//! Generates the constants for both implementations from the registry.
//!
//! Some spaces are open sets and the rest are closed, and that difference decides
//! the shape: a closed space becomes an enum whose `TryFrom` refuses an unknown
//! value, an open one becomes a newtype with named constants that carries a
//! value nobody has allocated. Getting that backwards means either a snapshot
//! blanked because somebody hung a vendor meter on the bus, or a controller
//! acting on a discriminant it cannot read.
//!
//! A space is open by being in `[[open_registries.*]]`, which is a fact about
//! where it is written rather than a flag read somewhere else. The form before
//! this was a list of names in `meta.skip_unknown` consulted at exactly two
//! hardcoded call sites, so a name added to it did nothing at all and no build
//! could go red about it — the space stayed closed while the file read as though
//! a decision had been made.

use anyhow::Result;
use std::fmt::Write as _;
use std::path::Path;

use crate::registry::{EventClass, Registry, Status};

const HEADER: &str = "Generated by `cargo xtask registry` from crates/km43/protocol.toml.\n\
                      Do not edit. A number lives in one place or two people allocate it twice.";

pub struct Bindings {
    registry: Registry,
}

impl Bindings {
    /// The line `km43/build.rs` looks for. Both languages use `//`, so
    /// one marker serves both.
    pub const DIGEST_MARKER: &'static str = "// registry-digest: ";

    pub fn load(root: &Path) -> Result<Self> {
        Ok(Self {
            registry: Registry::load(root)?,
        })
    }

    /// The generated files that no longer match the registry.
    pub fn stale(&self, root: &Path) -> Vec<String> {
        self.targets()
            .into_iter()
            .filter(|(path, body)| {
                std::fs::read_to_string(root.join(path)).is_ok_and(|c| &c != body)
            })
            .map(|(path, _)| path.to_owned())
            .collect()
    }

    fn targets(&self) -> Vec<(&'static str, String)> {
        vec![
            ("crates/km43/src/generated.rs", self.rust()),
            ("packages/km43/src/generated.ts", self.typescript()),
        ]
    }

    pub fn write(&self, root: &Path) -> Result<()> {
        for (path, body) in self.targets() {
            let full = root.join(path);
            if let Some(dir) = full.parent() {
                std::fs::create_dir_all(dir)?;
            }
            let changed = std::fs::read_to_string(&full).is_ok_and(|c| c == body);
            std::fs::write(&full, body)?;
            if !changed {
                println!("wrote {path}");
            }
        }
        Ok(())
    }

    fn is_open(&self, space: &str) -> bool {
        self.registry.meta.skip_unknown.iter().any(|s| s == space)
    }

    fn rust(&self) -> String {
        let mut o = String::new();
        for line in HEADER.lines() {
            let _ = writeln!(o, "// {line}");
        }
        let _ = writeln!(o, "{}{}\n", Self::DIGEST_MARKER, self.registry.digest);

        closed_enum(
            &mut o,
            "MessageType",
            "u8",
            self.registry
                .messages
                .iter()
                .filter(|m| !m.status.is_gone())
                .flat_map(|m| {
                    [
                        m.request.map(|r| (variant(&m.name), r.0)),
                        m.response
                            .map(|r| (format!("{}Response", variant(&m.name)), r.0)),
                    ]
                })
                .flatten(),
        );

        closed_enum(
            &mut o,
            "LinkMessageType",
            "u8",
            self.registry.link_messages.iter().flat_map(|m| {
                [
                    (variant(&m.name), m.request.0),
                    (format!("{}Ack", variant(&m.name)), m.response.0),
                ]
            }),
        );
        o.push_str(&self.link_directions());

        closed_enum(
            &mut o,
            "ErrorCode",
            "u16",
            self.registry
                .errors
                .iter()
                .filter(|e| e.status == Status::Live)
                .map(|e| (variant(&e.meaning), e.code)),
        );

        for (space, entries) in self.registry.outcomes.iter().chain(&self.registry.enums) {
            closed_enum(
                &mut o,
                &variant(space),
                "u8",
                entries
                    .iter()
                    .filter(|e| !e.status.is_gone())
                    .map(|e| (variant(&e.name), u16::from(e.value))),
            );
        }

        for (space, entries) in &self.registry.codes {
            closed_enum(
                &mut o,
                &variant(space),
                "u16",
                entries
                    .iter()
                    .filter(|e| e.status.is_some_and(|s| !s.is_gone()))
                    .filter_map(|e| e.number.map(|n| (variant(&e.name), n))),
            );
        }

        for (space, entries) in self
            .registry
            .link_outcomes
            .iter()
            .chain(&self.registry.link_enums)
        {
            closed_enum(
                &mut o,
                &variant(space),
                "u8",
                entries
                    .iter()
                    .filter(|e| !e.status.is_gone())
                    .map(|e| (variant(&e.name), u16::from(e.value))),
            );
        }

        o.push_str(&self.rust_error_macd());
        o.push_str(&self.rust_event_class());
        o.push_str(&self.rust_link_and_capability());

        o.push_str(&self.rust_open_sets());
        o
    }

    /// The two open spaces and the unit table. Split out for the reason the
    /// lint gives: `rust` was over a hundred lines and every one of these is a
    /// self-contained emission.
    fn rust_open_sets(&self) -> String {
        let mut o = String::new();
        open_newtype(
            &mut o,
            "MetricKind",
            self.registry
                .metrics
                .iter()
                .filter(|m| !m.status.is_gone())
                .map(|m| (m.name.clone(), m.kind)),
            self.is_open("metric_kind"),
        );
        open_newtype(
            &mut o,
            "EventKind",
            self.registry
                .events
                .iter()
                .filter(|e| !e.status.is_gone())
                .map(|e| (e.name.clone(), e.kind)),
            self.is_open("event_kind"),
        );

        // Every other open space, by being in the table that means open. The two above
        // are named literals because `metrics` and `events` are top-level tables with
        // shapes of their own — a metric carries a unit and a scale, an event carries a
        // class — and neither fits the plain number-and-name row these have.
        for (space, rows) in &self.registry.open_registries {
            open_newtype(
                &mut o,
                &variant(space),
                rows.iter()
                    .filter(|r| r.status.is_some_and(|s| !s.is_gone()))
                    .filter_map(|r| r.number.map(|n| (r.name.clone(), n))),
                true,
            );
        }

        o.push_str(&self.rust_enum_space_members());

        o.push_str(
            "/// Every metric with the unit and scale it is read in:\n\
             /// `value = raw * 10^scale`. Sorted, so a lookup can bisect.\n\
             pub const METRIC_UNITS: &[(u16, &str, i8)] = &[\n",
        );
        let mut metrics: Vec<_> = self.registry.metrics.iter().collect();
        metrics.sort_by_key(|m| m.kind);
        for m in metrics {
            let _ = writeln!(o, "    ({:#06x}, \"{}\", {}),", m.kind, m.unit, m.scale);
        }
        o.push_str("];\n\nimpl MetricKind {\n    #[must_use]\n    pub fn unit_and_scale(self) -> Option<(&'static str, i8)> {\n        METRIC_UNITS\n            .binary_search_by_key(&self.0, |&(k, _, _)| k)\n            .ok()\n            .and_then(|i| METRIC_UNITS.get(i))\n            .map(|&(_, u, s)| (u, s))\n    }\n}\n");
        o.push_str(&self.rust_dataset());
        o
    }

    /// The public equipment dataset's word for a reading, as a table a lookup
    /// walks first match wins, which is why the registry hands the rows over
    /// most specific first.
    fn rust_dataset(&self) -> String {
        let place = |name: &str, number: Option<u16>| {
            number.map_or_else(|| "None".to_owned(), |n| format!("Some({name}({n:#06x}))"))
        };
        let mut o = String::new();
        o.push_str(
            "\n/// The public equipment dataset's word for a reading: a metric kind over a\n\
             /// signal domain, at a place. A `None` place matches any; the domain never\n\
             /// does, so a limit or a period counter cannot borrow a live reading's word.\n\
             /// Rows are most specific first, so the first match is the one to take.\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             #[cfg_attr(feature = \"defmt\", derive(defmt::Format))]\n\
             pub struct DatasetMetric {\n    \
                 pub kind: MetricKind,\n    \
                 pub domain: SignalDomain,\n    \
                 pub role: Option<ComponentRole>,\n    \
                 pub point: Option<MeasurementPoint>,\n    \
                 pub name: &'static str,\n\
             }\n\n\
             pub const DATASET_METRICS: &[DatasetMetric] = &[\n",
        );
        for c in &self.registry.crosswalk.carried {
            let domain = format!("SignalDomain::{}", variant(&self.domain_name(c.domain)));
            let _ = writeln!(
                o,
                "    DatasetMetric {{\n        kind: MetricKind({:#06x}),\n        domain: {domain},\n        role: {},\n        point: {},\n        name: {:?},\n    }},",
                c.kind,
                place("ComponentRole", c.role),
                place("MeasurementPoint", c.point),
                c.name
            );
        }
        o.push_str(
            "];\n\n/// Dataset words no metric carries, each with why.\n\
             pub const DATASET_ABSENT: &[(&str, &str)] = &[\n",
        );
        for (name, why) in &self.registry.crosswalk.absent {
            // What rustfmt would do with the line, done here so the generated file is
            // already formatted: a tuple within its `fn_call_width` of 60 stays on one
            // line, and a wider one is broken one element per line.
            // `{:?}` on a `str` is a Rust string literal: quotes, backslashes and
            // control characters escaped, so the text a consumer reads is the text
            // in `protocol.toml` and not what the compiler made of a stray `\t`.
            let tuple = format!("({name:?}, {why:?})");
            if tuple.len() <= 60 {
                let _ = writeln!(o, "    {tuple},");
            } else {
                let _ = writeln!(o, "    (\n        {name:?},\n        {why:?},\n    ),");
            }
        }
        o.push_str(
            "];\n\nimpl MetricKind {\n    \
                 /// The dataset's word for this kind over a domain at a place, or `None`\n    \
                 /// when it has none.\n    \
                 #[must_use]\n    \
                 pub fn dataset_name(\n        \
                     self,\n        \
                     domain: SignalDomain,\n        \
                     role: Option<ComponentRole>,\n        \
                     point: Option<MeasurementPoint>,\n    \
                 ) -> Option<&'static str> {\n        \
                     DATASET_METRICS\n            \
                         .iter()\n            \
                         .find(|m| {\n                \
                             m.kind == self\n                    \
                                 && m.domain == domain\n                    \
                                 && m.role.is_none_or(|r| Some(r) == role)\n                    \
                                 && m.point.is_none_or(|p| Some(p) == point)\n            \
                         })\n            \
                         .map(|m| m.name)\n    \
                 }\n\
             }\n",
        );
        o
    }

    /// What each enum space contains, so a controller can ask rather than match.
    ///
    /// The join is by name — `enum_space` "generator state" against
    /// `[[enums.generator_state]]` — and it is done here, once, instead of in
    /// every reader. A space with no member table gets **no row**, which is what
    /// lets the generated `EnumSpace::members` answer `None` and a caller tell *this set
    /// names nothing yet* from *that value is not in it*. The two need telling
    /// apart: the first is a commissioning error and the second is a device
    /// running firmware newer than this build.
    fn rust_enum_space_members(&self) -> String {
        let mut rows: Vec<(u16, Vec<u8>)> = Vec::new();
        for space in self
            .registry
            .open_registries
            .get("enum_space")
            .map(Vec::as_slice)
            .unwrap_or_default()
        {
            let (Some(number), Some(members)) = (
                space.number,
                self.registry.enums.get(&space.name.replace(' ', "_")),
            ) else {
                continue;
            };
            let mut values: Vec<u8> = members
                .iter()
                .filter(|m| !m.status.is_gone())
                .map(|m| m.value)
                .collect();
            values.sort_unstable();
            if !values.is_empty() {
                rows.push((number, values));
            }
        }
        rows.sort_by_key(|&(space, _)| space);

        let mut o = String::from(
            "/// What every enum space contains, by the registry's own tables. Sorted on\n\
             /// both axes, so a lookup can bisect. A space with no members is absent here\n\
             /// rather than present and empty.\n\
             pub const ENUM_SPACE_MEMBERS: &[(u16, &[i32])] = &[\n",
        );
        for (space, values) in rows {
            let list: Vec<String> = values.iter().map(u8::to_string).collect();
            let _ = writeln!(o, "    ({space:#06x}, &[{}]),", list.join(", "));
        }
        o.push_str(
            "];\n\n\
             impl EnumSpace {\n    \
             /// The values this build can name in this space, or `None` where it names\n    \
             /// none at all.\n    \
             ///\n    \
             /// The `None` is the case worth having: a space allocated with no members\n    \
             /// can never name one of its own values, so a signal drawn from it reads\n    \
             /// `unnamed_state` at every poll. That is a registry entry half written,\n    \
             /// and it is a different thing from a device reporting a state this build\n    \
             /// has not heard of.\n    \
             #[must_use]\n    \
             pub fn members(self) -> Option<&'static [i32]> {\n        \
             let at = ENUM_SPACE_MEMBERS\n            \
             .binary_search_by_key(&self.0, |&(space, _)| space)\n            \
             .ok()?;\n        \
             ENUM_SPACE_MEMBERS.get(at).map(|&(_, members)| members)\n    \
             }\n\n    \
             /// Whether this build can name `value` as a member of this space.\n    \
             ///\n    \
             /// False for a space that names nothing, which is deliberate: the caller\n    \
             /// that needs to tell the two apart asks [`Self::members`].\n    \
             #[must_use]\n    \
             pub fn names(self, value: i32) -> bool {\n        \
             self.members()\n            \
             .is_some_and(|members| members.binary_search(&value).is_ok())\n    \
             }\n\
             }\n\n",
        );
        o
    }

    /// The receiver's MAC'd column, which is registry data and belongs in one
    /// place. `rust` was 126 lines with this inlined, and the lint describing
    /// the fix is the lint that fired.
    fn rust_event_class(&self) -> String {
        let mut o = String::new();
        o.push_str(
            "/// Which records survive a controller under pressure.\n\
             ///\n\
             /// The registry's class column, and the two words are defined there\n\
             /// normatively rather than in a design document — a column with no\n\
             /// definition beside it is one every implementation fills in for itself,\n\
             /// and the two answers it picks between are *keep this alarm* and *drop\n\
             /// it*. A controller that ranks a value change above an alarm raised\n\
             /// loses the alarm on the busiest day, which is the day it mattered.\n\
             /// Sorted, so a lookup can bisect.\n\
             pub const EVENT_IS_CLASS_A: &[(u16, bool)] = &[\n",
        );
        let mut kinds: Vec<_> = self
            .registry
            .events
            .iter()
            .filter(|e| !e.status.is_gone())
            .collect();
        kinds.sort_by_key(|e| e.kind);
        for e in kinds {
            let _ = writeln!(o, "    ({}, {}),", e.kind, matches!(e.class, EventClass::A));
        }
        o.push_str(
            "];\n\n\
             impl EventKind {\n    \
                 /// Whether this record is never dropped — not from the log, and not\n    \
                 /// from a queue.\n    \
                 ///\n    \
                 /// `None` for a kind this build has never heard of. Not `false`: a\n    \
                 /// controller that treated an unknown record as droppable would shed\n    \
                 /// exactly the records a newer firmware added because they mattered.\n    \
                 #[must_use]\n    \
                 pub fn is_class_a(self) -> Option<bool> {\n        \
                     EVENT_IS_CLASS_A\n            \
                         .binary_search_by_key(&self.0, |&(k, _)| k)\n            \
                         .ok()\n            \
                         .and_then(|i| EVENT_IS_CLASS_A.get(i))\n            \
                         .map(|&(_, a)| a)\n    \
                 }\n\
             }\n\n",
        );
        o
    }

    fn rust_error_macd(&self) -> String {
        let mut o = String::new();
        o.push_str(
            "/// Whether a receiver may read this code out of a **bare** body.\n\
             ///\n\
             /// The registry's MAC'd column, which is the receiver's check and never\n\
             /// the sender's: P-142 decides the shape by whether the *sender* holds\n\
             /// a session, so a rule read off this column would be one the cases\n\
             /// with no session cannot obey. What it says is what a receiver will\n\
             /// accept, and a bare body carrying a code marked here is discarded\n\
             /// under P-051 rather than acted on. Sorted, so a lookup can bisect.\n\
             pub const ERROR_NEEDS_A_MAC: &[(u16, bool)] = &[\n",
        );
        let mut coded: Vec<_> = self
            .registry
            .errors
            .iter()
            .filter(|e| e.status == Status::Live)
            .collect();
        coded.sort_by_key(|e| e.code);
        for e in coded {
            let _ = writeln!(o, "    ({}, {}),", e.code, e.macd);
        }
        o.push_str(
            "];\n\n\
             impl ErrorCode {\n    \
                 /// Whether a receiver refuses to read this code out of a bare body.\n    \
                 #[must_use]\n    \
                 pub fn needs_a_mac(self) -> bool {\n        \
                     ERROR_NEEDS_A_MAC\n            \
                         .binary_search_by_key(&(self as u16), |&(c, _)| c)\n            \
                         .ok()\n            .and_then(|i| ERROR_NEEDS_A_MAC.get(i))\n            .is_some_and(|&(_, m)| m)\n    \
                 }\n\
             }\n\n",
        );

        o
    }

    /// The two spaces a client needs to act on but must not confuse with the
    /// client-facing ones: link-local errors, and the per-client mask.
    fn rust_link_and_capability(&self) -> String {
        let mut o = String::new();
        closed_enum(
            &mut o,
            "LinkErrorCode",
            "u16",
            self.registry
                .link_errors
                .iter()
                .filter(|e| e.status == Status::Live)
                .map(|e| (variant(&e.name), e.code)),
        );

        o.push_str(
            "/// A code off the wire, kept in the space it came from.\n\
             ///\n\
             /// Widening `ErrorCode` to hold the link-local range would make a\n\
             /// routing fault in the comms processor look like the client's own\n\
             /// request failing, and the two want different retries.\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             #[cfg_attr(feature = \"defmt\", derive(defmt::Format))]\n\
             pub enum Incoming {\n    \
                 Client(ErrorCode),\n    \
                 LinkLocal(LinkErrorCode),\n    \
                 Unknown(u16),\n\
             }\n\n\
             impl From<u16> for Incoming {\n    \
                 fn from(v: u16) -> Self {\n        \
                     ErrorCode::try_from(v).map_or_else(\n            \
                         |()| LinkErrorCode::try_from(v).map_or(Self::Unknown(v), Self::LinkLocal),\n            \
                         Self::Client,\n        \
                     )\n    \
                 }\n\
             }\n\n",
        );

        let bits: Vec<_> = self
            .registry
            .client_capability
            .iter()
            .filter(|c| c.status == Some(Status::Live))
            .filter_map(|c| Some((screaming(c.name.as_ref()?), c.bit?)))
            .collect();
        if !bits.is_empty() {
            o.push_str(
                "/// The per-client capability mask, fixed at enrolment.\n\
                 ///\n\
                 /// Not a wire discriminant: an unallocated bit is a capability\n\
                 /// nobody has defined yet, not a value to reject.\n\
                 #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
                 #[cfg_attr(feature = \"defmt\", derive(defmt::Format))]\n\
                 pub struct ClientCapability(pub u16);\n\n\
                 impl ClientCapability {\n",
            );
            for (name, bit) in &bits {
                let _ = writeln!(o, "    pub const {name}: Self = Self(1 << {bit});");
            }
            o.push_str(
                "\n    #[must_use]\n    \
                 pub fn allows(self, want: Self) -> bool {\n        \
                     self.0 & want.0 == want.0\n    \
                 }\n",
            );
            o.push_str(&self.granted(bits.len()));
            o.push_str("}\n\n");
        }
        o
    }

    /// Which side may send each link-local request, from the `direction`
    /// column that until now only ever reached a table in the document.
    ///
    /// L-001 refuses the other side with the same code as an unknown opcode:
    /// from the receiver's side a message it has no business acting on is one
    /// mistake, not two, and neither firmware has to decide which kind of wrong
    /// it is looking at.
    fn link_directions(&self) -> String {
        let mut o = String::from(
            "/// Which side may send a link-local request.\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             #[cfg_attr(feature = \"defmt\", derive(defmt::Format))]\n\
             pub enum LinkDirection {\n    \
                 Either,\n    \
                 CommsToController,\n    \
                 ControllerToComms,\n\
             }\n\n\
             impl LinkMessageType {\n    \
                 /// Which side may send this, request and acknowledgement alike.\n    \
                 ///\n    \
                 /// Left unformatted for the reason `ClientCapability::granted` is:\n    \
                 /// a pattern list long enough to wrap comes back from `cargo fmt`\n    \
                 /// in a shape this generator does not emit, and then `cargo fmt`\n    \
                 /// and `cargo xtask check` cannot both be green.\n    \
                 #[rustfmt::skip]\n    \
                 #[must_use]\n    \
                 pub const fn direction(self) -> LinkDirection {\n        \
                 match self {\n",
        );
        let mut arms: Vec<(&str, Vec<String>)> = Vec::new();
        for m in &self.registry.link_messages {
            let side = match m.direction {
                crate::registry::LinkDirection::Either => "Either",
                crate::registry::LinkDirection::CommsToController => "CommsToController",
                crate::registry::LinkDirection::ControllerToComms => "ControllerToComms",
            };
            let name = variant(&m.name);
            let patterns = [
                format!("LinkMessageType::{name}"),
                format!("LinkMessageType::{name}Ack"),
            ];
            match arms.iter_mut().find(|(seen, _)| *seen == side) {
                Some((_, into)) => into.extend(patterns),
                None => arms.push((side, patterns.to_vec())),
            }
        }
        for (side, patterns) in &arms {
            for (n, pattern) in patterns.iter().enumerate() {
                let lead = if n == 0 {
                    "            "
                } else {
                    "            | "
                };
                let _ = writeln!(o, "{lead}{pattern}");
            }
            let _ = writeln!(o, "            => LinkDirection::{side},");
        }
        o.push_str("        }\n    }\n}\n\n");
        o
    }

    /// The mask each `client_kind` is handed at enrolment, folded out of the
    /// same `granted_to` lists that render the grid in REGISTRY.md.
    ///
    /// A grant list, so a `client_kind` allocated later and mentioned by no row
    /// comes out holding nothing. Folded the other way it would come out holding
    /// everything, and the bit it would arrive with is firmware push.
    ///
    /// Emitted rather than written by hand in the controller, because a mask
    /// kept in two places is a cloud client the document says cannot push
    /// firmware and the controller lets. The bits are in the order of the
    /// constants directly above, lowest first.
    fn granted(&self, width: usize) -> String {
        let Some(kinds) = self.registry.enums.get("client_kind") else {
            return String::new();
        };
        let mut o = String::from(
            "\n    /// The mask this `client_kind` is handed at enrolment.\n    \
             ///\n    \
             /// No message raises one and no message lowers one: either is a\n    \
             /// re-pair, which means somebody standing at the button.\n    \
             ///\n    \
             /// Left unformatted: a kind list long enough to wrap would be\n    \
             /// rewritten by `cargo fmt` into something this generator does not\n    \
             /// emit, after which `cargo fmt` and `cargo xtask check` cannot\n    \
             /// both be green and the fix is not obvious from either.\n    \
             #[rustfmt::skip]\n    \
             #[must_use]\n    \
             pub const fn granted(kind: ClientKind) -> Self {\n        \
             match kind {\n",
        );
        // Kinds that come out with the same mask share an arm, in first-seen
        // order. Three arms with identical bodies is what a reader has to
        // compare by eye to notice that only one of the four is restricted.
        let mut arms: Vec<(u16, Vec<String>)> = Vec::new();
        for kind in kinds.iter().filter(|k| k.status != Status::Withdrawn) {
            let mask = self
                .registry
                .client_capability
                .iter()
                .filter(|c| c.status == Some(Status::Live))
                .filter(|c| c.granted_to.contains(&kind.name))
                .filter_map(|c| c.bit)
                .filter_map(|bit| 1u16.checked_shl(u32::from(bit)))
                .fold(0u16, |mask, bit| mask | bit);
            let pattern = format!("ClientKind::{}", variant(&kind.name));
            match arms.iter_mut().find(|(seen, _)| *seen == mask) {
                Some((_, patterns)) => patterns.push(pattern),
                None => arms.push((mask, vec![pattern])),
            }
        }
        for (mask, patterns) in &arms {
            let _ = writeln!(
                o,
                "            {} => Self(0b{mask:0width$b}),",
                patterns.join(" | ")
            );
        }
        o.push_str("        }\n    }\n");
        o
    }

    fn typescript(&self) -> String {
        let mut o = String::new();
        for line in HEADER.lines() {
            let _ = writeln!(o, "// {line}");
        }
        let _ = writeln!(o, "{}{}\n", Self::DIGEST_MARKER, self.registry.digest);

        ts_enum(
            &mut o,
            "MessageType",
            self.registry
                .messages
                .iter()
                .filter(|m| !m.status.is_gone())
                .flat_map(|m| {
                    [
                        m.request.map(|r| (variant(&m.name), r.0)),
                        m.response
                            .map(|r| (format!("{}Response", variant(&m.name)), r.0)),
                    ]
                })
                .flatten(),
        );
        ts_enum(
            &mut o,
            "ErrorCode",
            self.registry
                .errors
                .iter()
                .filter(|e| e.status == Status::Live)
                .map(|e| (variant(&e.meaning), e.code)),
        );
        for (space, entries) in self.registry.outcomes.iter().chain(&self.registry.enums) {
            ts_enum(
                &mut o,
                &variant(space),
                entries
                    .iter()
                    .filter(|e| !e.status.is_gone())
                    .map(|e| (variant(&e.name), u16::from(e.value))),
            );
        }
        for (space, entries) in &self.registry.codes {
            ts_enum(
                &mut o,
                &variant(space),
                entries
                    .iter()
                    .filter(|e| e.status.is_some_and(|s| !s.is_gone()))
                    .filter_map(|e| e.number.map(|n| (variant(&e.name), n))),
            );
        }

        ts_enum(
            &mut o,
            "LinkErrorCode",
            self.registry
                .link_errors
                .iter()
                .filter(|e| e.status == Status::Live)
                .map(|e| (variant(&e.name), e.code)),
        );
        let bits: Vec<_> = self
            .registry
            .client_capability
            .iter()
            .filter(|c| c.status == Some(Status::Live))
            .filter_map(|c| Some((screaming(c.name.as_ref()?), c.bit?)))
            .collect();
        if !bits.is_empty() {
            o.push_str("export const ClientCapability = {\n");
            for (name, bit) in &bits {
                let _ = writeln!(o, "  {name}: 1 << {bit},");
            }
            o.push_str("} as const;\n\n");
        }

        o.push_str(&self.ts_open_sets());
        o
    }

    /// The open spaces and the unit table, for the same reason `rust_open_sets`
    /// exists: `typescript` crossed a hundred lines the moment open spaces stopped
    /// being two hardcoded calls, and the lint describing the fix is the lint that
    /// fired.
    fn ts_open_sets(&self) -> String {
        let mut o = String::new();
        o.push_str("// Open sets: a device may emit a value this table does not name, and a\n");
        o.push_str("// client shows that one carrier as unrecognised rather than blanking the\n");
        o.push_str("// message around it.\n");
        ts_const_map(
            &mut o,
            "MetricKind",
            self.registry
                .metrics
                .iter()
                .filter(|m| !m.status.is_gone())
                .map(|m| (m.name.clone(), m.kind)),
        );
        ts_const_map(
            &mut o,
            "EventKind",
            self.registry
                .events
                .iter()
                .filter(|e| !e.status.is_gone())
                .map(|e| (e.name.clone(), e.kind)),
        );
        for (space, rows) in &self.registry.open_registries {
            ts_const_map(
                &mut o,
                &variant(space),
                rows.iter()
                    .filter(|r| r.status.is_some_and(|s| !s.is_gone()))
                    .filter_map(|r| r.number.map(|n| (r.name.clone(), n))),
            );
        }

        o.push_str("export const metricUnits: Record<number, readonly [string, number]> = {\n");
        for m in &self.registry.metrics {
            let _ = writeln!(o, "  {:#06x}: [\"{}\", {}],", m.kind, m.unit, m.scale);
        }
        o.push_str("};\n");
        o.push_str(&self.ts_dataset());
        o
    }

    /// The name the registry gives a signal domain value, for the generated
    /// variant. A value the crosswalk resolved always exists, so an unknown one
    /// renders as its number and fails to compile rather than passing silently.
    fn domain_name(&self, value: u8) -> String {
        self.registry
            .enums
            .get("signal_domain")
            .and_then(|rows| rows.iter().find(|r| r.value == value))
            .map_or_else(|| value.to_string(), |r| r.name.clone())
    }

    /// The same crosswalk for a client, most specific row first.
    fn ts_dataset(&self) -> String {
        let mut o = String::new();
        o.push_str(
            "\n// The public equipment dataset's word for a reading: a metric kind over a\n\
             // signal domain, at a place. An undefined place matches any; the domain never\n\
             // does. Rows are most specific first.\n\
             export interface DatasetMetric {\n  \
                 readonly kind: number;\n  \
                 readonly domain: number;\n  \
                 readonly role?: number;\n  \
                 readonly point?: number;\n  \
                 readonly name: string;\n\
             }\n\n\
             export const datasetMetrics: readonly DatasetMetric[] = [\n",
        );
        for c in &self.registry.crosswalk.carried {
            let mut row = format!("  {{ kind: {:#06x}, domain: {:#04x}", c.kind, c.domain);
            if let Some(role) = c.role {
                let _ = write!(row, ", role: {role:#06x}");
            }
            if let Some(point) = c.point {
                let _ = write!(row, ", point: {point:#06x}");
            }
            let _ = writeln!(o, "{row}, name: {} }},", js(&c.name));
        }
        o.push_str(
            "];\n\n// Dataset words no metric carries, each with why.\n\
             export const datasetAbsent: Readonly<Record<string, string>> = {\n",
        );
        for (name, why) in &self.registry.crosswalk.absent {
            let _ = writeln!(o, "  {}: {},", js(name), js(why));
        }
        o.push_str(
            "};\n\n\
             export function datasetName(\n  \
                 kind: number,\n  \
                 domain: number,\n  \
                 role?: number,\n  \
                 point?: number,\n\
             ): string | undefined {\n  \
                 return datasetMetrics.find(\n    \
                     (m) =>\n      \
                         m.kind === kind &&\n      \
                         m.domain === domain &&\n      \
                         (m.role === undefined || m.role === role) &&\n      \
                         (m.point === undefined || m.point === point),\n  \
                 )?.name;\n\
             }\n",
        );
        o
    }
}

/// A closed space: an unknown value is a parse error, never a fallback.
fn closed_enum(
    o: &mut String,
    name: &str,
    repr: &str,
    entries: impl Iterator<Item = (String, u16)>,
) {
    let rows: Vec<_> = entries.collect();
    if rows.is_empty() {
        return;
    }
    let _ = writeln!(o, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
    let _ = writeln!(
        o,
        r#"#[cfg_attr(feature = "defmt", derive(defmt::Format))]"#
    );
    let _ = writeln!(o, "#[repr({repr})]");
    let _ = writeln!(o, "pub enum {name} {{");
    for (v, n) in &rows {
        let _ = writeln!(o, "    {v} = {n:#x},");
    }
    let _ = writeln!(o, "}}\n");
    let _ = writeln!(o, "impl TryFrom<{repr}> for {name} {{");
    let _ = writeln!(o, "    type Error = ();\n");
    let _ = writeln!(
        o,
        "    fn try_from(v: {repr}) -> Result<Self, Self::Error> {{"
    );
    let _ = writeln!(o, "        match v {{");
    for (v, n) in &rows {
        let _ = writeln!(o, "            {n:#x} => Ok(Self::{v}),");
    }
    let _ = writeln!(o, "            _ => Err(()),\n        }}\n    }}\n}}\n");
}

/// An open space: the value is carried whether or not it is named.
fn open_newtype(
    o: &mut String,
    name: &str,
    entries: impl Iterator<Item = (String, u16)>,
    open: bool,
) {
    if !open {
        return;
    }
    let _ = writeln!(
        o,
        "/// Open set: a value this list does not name is carried, not refused."
    );
    let _ = writeln!(o, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
    let _ = writeln!(
        o,
        r#"#[cfg_attr(feature = "defmt", derive(defmt::Format))]"#
    );
    let _ = writeln!(o, "pub struct {name}(pub u16);\n");
    let _ = writeln!(o, "impl {name} {{");
    for (v, n) in entries {
        let _ = writeln!(o, "    pub const {}: Self = Self({n:#06x});", screaming(&v));
    }
    let _ = writeln!(o, "}}\n");
}

fn ts_enum(o: &mut String, name: &str, entries: impl Iterator<Item = (String, u16)>) {
    let rows: Vec<_> = entries.collect();
    if rows.is_empty() {
        return;
    }
    let _ = writeln!(o, "export enum {name} {{");
    for (v, n) in rows {
        let _ = writeln!(o, "  {v} = {n:#x},");
    }
    let _ = writeln!(o, "}}\n");
}

fn ts_const_map(o: &mut String, name: &str, entries: impl Iterator<Item = (String, u16)>) {
    let _ = writeln!(o, "export const {name} = {{");
    for (v, n) in entries {
        let _ = writeln!(o, "  {}: {n:#06x},", screaming(&v));
    }
    let _ = writeln!(o, "}} as const;\n");
}

/// `battery voltage` becomes `BatteryVoltage`, which is what a Rust variant and
/// a TypeScript member both want.
///
/// A parenthetical is a note rather than part of the name — `battery current
/// (+ charge, − discharge)` is `BatteryCurrent` — and everything that is not a
/// letter or a digit is a separator.
fn variant(s: &str) -> String {
    words(s)
        .map(|w| {
            // Only the first letter is touched: `ReadLog` is already the name
            // somebody wrote, and lowercasing the rest gives `Readlog`.
            let mut c = w.chars();
            c.next().map_or_else(String::new, |f| {
                f.to_ascii_uppercase().to_string() + c.as_str()
            })
        })
        .collect()
}

/// The same name as a constant: `battery voltage` becomes `BATTERY_VOLTAGE`.
fn screaming(s: &str) -> String {
    words(s)
        .map(str::to_ascii_uppercase)
        .collect::<Vec<_>>()
        .join("_")
}

fn words(s: &str) -> impl Iterator<Item = &str> {
    s.split_once('(')
        .map_or(s, |(before, _)| before)
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty())
}

/// A JavaScript string literal for `s`: a JSON string is one, with quotes,
/// backslashes and control characters escaped.
fn js(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Open and closed are different shapes in the generated code, and the difference is
    /// what a decoder does with a number nobody has allocated: a newtype carries it, an
    /// enum refuses the message around it.
    ///
    /// Written against the emitter rather than against a second copy of the rule, because
    /// the rule this replaced — a list of space names read in one place — could be wrong
    /// in the file and right in every test that quoted it.
    #[test]
    fn an_open_space_emits_a_newtype_and_a_closed_one_emits_an_enum() {
        let mut open = String::new();
        open_newtype(
            &mut open,
            "ComponentRole",
            [("pv array".to_owned(), 0x0001u16)].into_iter(),
            true,
        );
        assert!(
            open.contains("pub struct ComponentRole(pub u16);"),
            "an open space is a newtype over the full width, so a vendor value survives"
        );
        assert!(
            open.contains("pub const PV_ARRAY: Self = Self(0x0001);"),
            "and the names it does know are constants on it"
        );

        let mut closed = String::new();
        closed_enum(
            &mut closed,
            "Severity",
            "u8",
            [("warning".to_owned(), 2u16)].into_iter(),
        );
        assert!(
            closed.contains("enum Severity"),
            "a closed space is an enum, so an unallocated value is a parse error"
        );
        assert!(!closed.contains("pub struct Severity"), "and never both");
    }

    /// `open` is not a flag that can be set in one file and read in another. This is the
    /// property the whole change exists for: there is no second place to keep in sync.
    #[test]
    fn an_open_space_declares_itself_by_the_table_it_is_in() {
        let mut nothing = String::new();
        open_newtype(
            &mut nothing,
            "MetricKind",
            [("battery voltage".to_owned(), 0x0101u16)].into_iter(),
            false,
        );
        assert!(
            nothing.is_empty(),
            "the two top-level tables are still gated, and that gate is now checked at load"
        );
    }
}
