// Generated by `cargo xtask registry` from crates/km43/protocol.toml.
// Do not edit. A number lives in one place or two people allocate it twice.
// registry-digest: e7cd78952d920dfa

/// Discover this service by UUID on every connection; names and addresses do not establish KM43 identity.
pub const BLE_SERVICE_UUID: &str = "ab43e89a-7c21-4a5d-9b62-19e430000001";

/// Discover this Write Without Response characteristic by UUID; handles are connection-local.
pub const BLE_RX_UUID: &str = "ab43e89a-7c21-4a5d-9b62-19e430000002";

/// Enable notifications on this characteristic before sending Discover so controller replies can arrive.
pub const BLE_TX_UUID: &str = "ab43e89a-7c21-4a5d-9b62-19e430000003";

/// Set this bit only on the final fragment; a receiver must not deliver an unfinished envelope.
pub const BLE_LAST_FLAG: u8 = 128;

/// Mask out the final flag before checking consecutive indices; a gap or duplicate discards the assembly.
pub const BLE_INDEX_MASK: u8 = 127;

/// An encoded envelope larger than this is refused; size receive buffers for the whole envelope, not just its body.
pub const MAX_PAYLOAD: usize = 1024;

/// Use this ATT MTU until negotiation completes; sending larger values early can lose the first request.
pub const BLE_MIN_MTU: u16 = 23;

/// Reject ATT MTUs above this transport's supported range before deriving fragment sizes.
pub const BLE_MAX_MTU: u16 = 517;

/// Cap fragment values at this GATT attribute bound even when the negotiated MTU permits more bytes.
pub const BLE_MAX_VALUE: usize = 512;

/// Discard an incomplete assembly at this inactivity boundary; adapters also close stalled sends at this deadline.
pub const BLE_TIMEOUT_MS: u64 = 5000;

/// Refuse new messages when this per-direction slot count is occupied; never evict a queued message.
pub const BLE_TX_CAPACITY: usize = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum MessageType {
    Discover = 0x0,
    DiscoverResponse = 0x80,
    Hello = 0x1,
    HelloResponse = 0x81,
    Subscribe = 0x3,
    SubscribeResponse = 0x83,
    EventResponse = 0x4,
    ReadLog = 0x5,
    ReadLogResponse = 0x85,
    GetConfig = 0x6,
    GetConfigResponse = 0x86,
    SetConfig = 0x7,
    SetConfigResponse = 0x87,
    Command = 0x8,
    CommandResponse = 0x88,
    Firmware = 0x9,
    FirmwareResponse = 0x89,
    Time = 0xa,
    TimeResponse = 0x8a,
    Pair = 0xb,
    PairResponse = 0x8b,
    Goodbye = 0xc,
    GoodbyeResponse = 0x8c,
    Inventory = 0xd,
    InventoryResponse = 0x8d,
    Readings = 0xe,
    ReadingsResponse = 0x8e,
    Concerns = 0xf,
    ConcernsResponse = 0x8f,
    History = 0x10,
    HistoryResponse = 0x90,
    ErrorResponse = 0xff,
}

impl TryFrom<u8> for MessageType {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x0 => Ok(Self::Discover),
            0x80 => Ok(Self::DiscoverResponse),
            0x1 => Ok(Self::Hello),
            0x81 => Ok(Self::HelloResponse),
            0x3 => Ok(Self::Subscribe),
            0x83 => Ok(Self::SubscribeResponse),
            0x4 => Ok(Self::EventResponse),
            0x5 => Ok(Self::ReadLog),
            0x85 => Ok(Self::ReadLogResponse),
            0x6 => Ok(Self::GetConfig),
            0x86 => Ok(Self::GetConfigResponse),
            0x7 => Ok(Self::SetConfig),
            0x87 => Ok(Self::SetConfigResponse),
            0x8 => Ok(Self::Command),
            0x88 => Ok(Self::CommandResponse),
            0x9 => Ok(Self::Firmware),
            0x89 => Ok(Self::FirmwareResponse),
            0xa => Ok(Self::Time),
            0x8a => Ok(Self::TimeResponse),
            0xb => Ok(Self::Pair),
            0x8b => Ok(Self::PairResponse),
            0xc => Ok(Self::Goodbye),
            0x8c => Ok(Self::GoodbyeResponse),
            0xd => Ok(Self::Inventory),
            0x8d => Ok(Self::InventoryResponse),
            0xe => Ok(Self::Readings),
            0x8e => Ok(Self::ReadingsResponse),
            0xf => Ok(Self::Concerns),
            0x8f => Ok(Self::ConcernsResponse),
            0x10 => Ok(Self::History),
            0x90 => Ok(Self::HistoryResponse),
            0xff => Ok(Self::ErrorResponse),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum LinkMessageType {
    LinkUp = 0x60,
    LinkUpAck = 0xe0,
    Heartbeat = 0x61,
    HeartbeatAck = 0xe1,
    ClientConnected = 0x62,
    ClientConnectedAck = 0xe2,
    ClientDisconnected = 0x63,
    ClientDisconnectedAck = 0xe3,
    CloseConnection = 0x64,
    CloseConnectionAck = 0xe4,
    NetConfig = 0x65,
    NetConfigAck = 0xe5,
    TimeOffer = 0x66,
    TimeOfferAck = 0xe6,
    CommsRelease = 0x67,
    CommsReleaseAck = 0xe7,
    EnterDownload = 0x68,
    EnterDownloadAck = 0xe8,
    PairingWindow = 0x69,
    PairingWindowAck = 0xe9,
}

impl TryFrom<u8> for LinkMessageType {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x60 => Ok(Self::LinkUp),
            0xe0 => Ok(Self::LinkUpAck),
            0x61 => Ok(Self::Heartbeat),
            0xe1 => Ok(Self::HeartbeatAck),
            0x62 => Ok(Self::ClientConnected),
            0xe2 => Ok(Self::ClientConnectedAck),
            0x63 => Ok(Self::ClientDisconnected),
            0xe3 => Ok(Self::ClientDisconnectedAck),
            0x64 => Ok(Self::CloseConnection),
            0xe4 => Ok(Self::CloseConnectionAck),
            0x65 => Ok(Self::NetConfig),
            0xe5 => Ok(Self::NetConfigAck),
            0x66 => Ok(Self::TimeOffer),
            0xe6 => Ok(Self::TimeOfferAck),
            0x67 => Ok(Self::CommsRelease),
            0xe7 => Ok(Self::CommsReleaseAck),
            0x68 => Ok(Self::EnterDownload),
            0xe8 => Ok(Self::EnterDownloadAck),
            0x69 => Ok(Self::PairingWindow),
            0xe9 => Ok(Self::PairingWindowAck),
            _ => Err(()),
        }
    }
}

/// Which side may send a link-local request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum LinkDirection {
    Either,
    CommsToController,
    ControllerToComms,
}

impl LinkMessageType {
    /// Which side may send this, request and acknowledgement alike.
    ///
    /// Left unformatted for the reason `ClientCapability::granted` is:
    /// a pattern list long enough to wrap comes back from `cargo fmt`
    /// in a shape this generator does not emit, and then `cargo fmt`
    /// and `cargo xtask check` cannot both be green.
    #[rustfmt::skip]
    #[must_use]
    pub const fn direction(self) -> LinkDirection {
        match self {
            LinkMessageType::LinkUp
            | LinkMessageType::LinkUpAck
            | LinkMessageType::Heartbeat
            | LinkMessageType::HeartbeatAck
            => LinkDirection::Either,
            LinkMessageType::ClientConnected
            | LinkMessageType::ClientConnectedAck
            | LinkMessageType::ClientDisconnected
            | LinkMessageType::ClientDisconnectedAck
            | LinkMessageType::TimeOffer
            | LinkMessageType::TimeOfferAck
            => LinkDirection::CommsToController,
            LinkMessageType::CloseConnection
            | LinkMessageType::CloseConnectionAck
            | LinkMessageType::NetConfig
            | LinkMessageType::NetConfigAck
            | LinkMessageType::CommsRelease
            | LinkMessageType::CommsReleaseAck
            | LinkMessageType::EnterDownload
            | LinkMessageType::EnterDownloadAck
            | LinkMessageType::PairingWindow
            | LinkMessageType::PairingWindowAck
            => LinkDirection::ControllerToComms,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u16)]
pub enum ErrorCode {
    MalformedFrame = 0x1,
    UnknownMessageType = 0x2,
    ProtocolMajorMismatch = 0x3,
    HelloRequiredFirst = 0x4,
    PayloadTooLarge = 0x5,
    UnknownSection = 0x6,
    BusyRetry = 0x7,
    SessionTableFull = 0x8,
    SessionExpired = 0x9,
    BadMAC = 0xa,
    CounterNotFresh = 0xb,
    UnknownClient = 0xc,
    StaleChallengeReconnectAndRetry = 0xe,
    ChallengeUnavailable = 0x12,
}

impl TryFrom<u16> for ErrorCode {
    type Error = ();

    fn try_from(v: u16) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::MalformedFrame),
            0x2 => Ok(Self::UnknownMessageType),
            0x3 => Ok(Self::ProtocolMajorMismatch),
            0x4 => Ok(Self::HelloRequiredFirst),
            0x5 => Ok(Self::PayloadTooLarge),
            0x6 => Ok(Self::UnknownSection),
            0x7 => Ok(Self::BusyRetry),
            0x8 => Ok(Self::SessionTableFull),
            0x9 => Ok(Self::SessionExpired),
            0xa => Ok(Self::BadMAC),
            0xb => Ok(Self::CounterNotFresh),
            0xc => Ok(Self::UnknownClient),
            0xe => Ok(Self::StaleChallengeReconnectAndRetry),
            0x12 => Ok(Self::ChallengeUnavailable),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Command {
    Accepted = 0x1,
    Rejected = 0x2,
    Duplicate = 0x3,
    Inhibited = 0x4,
    Unauthorised = 0x5,
    Shadowed = 0x6,
    StaleTopology = 0x7,
    WrongTarget = 0x8,
}

impl TryFrom<u8> for Command {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Accepted),
            0x2 => Ok(Self::Rejected),
            0x3 => Ok(Self::Duplicate),
            0x4 => Ok(Self::Inhibited),
            0x5 => Ok(Self::Unauthorised),
            0x6 => Ok(Self::Shadowed),
            0x7 => Ok(Self::StaleTopology),
            0x8 => Ok(Self::WrongTarget),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Concerns {
    Ok = 0x1,
    Superseded = 0x2,
    OutOfRange = 0x3,
}

impl TryFrom<u8> for Concerns {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Ok),
            0x2 => Ok(Self::Superseded),
            0x3 => Ok(Self::OutOfRange),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Firmware {
    Accepted = 0x1,
    BadOffset = 0x2,
    BadSignature = 0x3,
    WrongTarget = 0x4,
    TooLarge = 0x5,
    NoTransferInProgress = 0x6,
    NotOwner = 0x7,
    Unauthorised = 0x8,
}

impl TryFrom<u8> for Firmware {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Accepted),
            0x2 => Ok(Self::BadOffset),
            0x3 => Ok(Self::BadSignature),
            0x4 => Ok(Self::WrongTarget),
            0x5 => Ok(Self::TooLarge),
            0x6 => Ok(Self::NoTransferInProgress),
            0x7 => Ok(Self::NotOwner),
            0x8 => Ok(Self::Unauthorised),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum History {
    Ok = 0x1,
    Superseded = 0x2,
    UnknownSignal = 0x3,
    SeriesNotHistorable = 0x4,
    NoHistory = 0x5,
    OutOfRange = 0x6,
}

impl TryFrom<u8> for History {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Ok),
            0x2 => Ok(Self::Superseded),
            0x3 => Ok(Self::UnknownSignal),
            0x4 => Ok(Self::SeriesNotHistorable),
            0x5 => Ok(Self::NoHistory),
            0x6 => Ok(Self::OutOfRange),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Inventory {
    Ok = 0x1,
    Superseded = 0x2,
    UnknownKind = 0x3,
    OutOfRange = 0x4,
}

impl TryFrom<u8> for Inventory {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Ok),
            0x2 => Ok(Self::Superseded),
            0x3 => Ok(Self::UnknownKind),
            0x4 => Ok(Self::OutOfRange),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Pair {
    Enrolled = 0x1,
    WindowClosed = 0x2,
    BadProof = 0x3,
    TableFull = 0x4,
    Reclaimed = 0x5,
}

impl TryFrom<u8> for Pair {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Enrolled),
            0x2 => Ok(Self::WindowClosed),
            0x3 => Ok(Self::BadProof),
            0x4 => Ok(Self::TableFull),
            0x5 => Ok(Self::Reclaimed),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Readings {
    Ok = 0x1,
    Superseded = 0x2,
    UnknownSelector = 0x3,
    OutOfRange = 0x4,
}

impl TryFrom<u8> for Readings {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Ok),
            0x2 => Ok(Self::Superseded),
            0x3 => Ok(Self::UnknownSelector),
            0x4 => Ok(Self::OutOfRange),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum SetConfig {
    Accepted = 0x1,
    StaleVersion = 0x2,
    Invalid = 0x3,
    Unauthorised = 0x4,
    ExceedsCap = 0x5,
    Staged = 0x9,
}

impl TryFrom<u8> for SetConfig {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Accepted),
            0x2 => Ok(Self::StaleVersion),
            0x3 => Ok(Self::Invalid),
            0x4 => Ok(Self::Unauthorised),
            0x5 => Ok(Self::ExceedsCap),
            0x9 => Ok(Self::Staged),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Time {
    Accepted = 0x1,
    Rejected = 0x2,
    Unauthorised = 0x3,
    NeedsButton = 0x4,
}

impl TryFrom<u8> for Time {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Accepted),
            0x2 => Ok(Self::Rejected),
            0x3 => Ok(Self::Unauthorised),
            0x4 => Ok(Self::NeedsButton),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum BootReason {
    Power = 0x1,
    Watchdog = 0x2,
    SoftwareReset = 0x4,
    Panic = 0x5,
    PinReset = 0x6,
    OptionByteReload = 0x7,
    WindowWatchdog = 0x8,
    LowPowerEntry = 0x9,
}

impl TryFrom<u8> for BootReason {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Power),
            0x2 => Ok(Self::Watchdog),
            0x4 => Ok(Self::SoftwareReset),
            0x5 => Ok(Self::Panic),
            0x6 => Ok(Self::PinReset),
            0x7 => Ok(Self::OptionByteReload),
            0x8 => Ok(Self::WindowWatchdog),
            0x9 => Ok(Self::LowPowerEntry),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Bucket {
    Day = 0x1,
    Hour = 0x2,
    QuarterHour = 0x3,
}

impl TryFrom<u8> for Bucket {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Day),
            0x2 => Ok(Self::Hour),
            0x3 => Ok(Self::QuarterHour),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum ClientKind {
    App = 0x1,
    Browser = 0x2,
    Cloud = 0x3,
    Cli = 0x4,
}

impl TryFrom<u8> for ClientKind {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::App),
            0x2 => Ok(Self::Browser),
            0x3 => Ok(Self::Cloud),
            0x4 => Ok(Self::Cli),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum ConcernState {
    Active = 0x1,
    ActiveAcked = 0x2,
    LatchedCleared = 0x3,
    ClearingBlocked = 0x4,
    Cleared = 0x5,
}

impl TryFrom<u8> for ConcernState {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Active),
            0x2 => Ok(Self::ActiveAcked),
            0x3 => Ok(Self::LatchedCleared),
            0x4 => Ok(Self::ClearingBlocked),
            0x5 => Ok(Self::Cleared),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum ControlOwner {
    LocalPanel = 0x1,
    ThisController = 0x2,
    Bms = 0x3,
    GxEss = 0x4,
    RemoteClient = 0x5,
    DeviceAutomation = 0x6,
}

impl TryFrom<u8> for ControlOwner {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::LocalPanel),
            0x2 => Ok(Self::ThisController),
            0x3 => Ok(Self::Bms),
            0x4 => Ok(Self::GxEss),
            0x5 => Ok(Self::RemoteClient),
            0x6 => Ok(Self::DeviceAutomation),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Direction {
    PositiveIsIn = 0x1,
    PositiveIsOut = 0x2,
    MagnitudeOnly = 0x3,
}

impl TryFrom<u8> for Direction {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::PositiveIsIn),
            0x2 => Ok(Self::PositiveIsOut),
            0x3 => Ok(Self::MagnitudeOnly),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum GeneratorSelector {
    Auto = 0x1,
    Off = 0x2,
    Manual = 0x3,
}

impl TryFrom<u8> for GeneratorSelector {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Auto),
            0x2 => Ok(Self::Off),
            0x3 => Ok(Self::Manual),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum GeneratorState {
    Stopped = 0x1,
    Starting = 0x2,
    Running = 0x3,
    RunningNotOurs = 0x4,
    StopNotHonoured = 0x5,
    GaveUp = 0x6,
}

impl TryFrom<u8> for GeneratorState {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Stopped),
            0x2 => Ok(Self::Starting),
            0x3 => Ok(Self::Running),
            0x4 => Ok(Self::RunningNotOurs),
            0x5 => Ok(Self::StopNotHonoured),
            0x6 => Ok(Self::GaveUp),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum HistorySource {
    DeviceReported = 0x1,
    ControllerDerived = 0x2,
}

impl TryFrom<u8> for HistorySource {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::DeviceReported),
            0x2 => Ok(Self::ControllerDerived),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum HistoryStopReason {
    DeviceReplaced = 0x1,
    ComponentReassigned = 0x2,
    GapInRecord = 0x3,
    EndOfRecord = 0x4,
    OlderThanStore = 0x5,
    PageFull = 0x6,
}

impl TryFrom<u8> for HistoryStopReason {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::DeviceReplaced),
            0x2 => Ok(Self::ComponentReassigned),
            0x3 => Ok(Self::GapInRecord),
            0x4 => Ok(Self::EndOfRecord),
            0x5 => Ok(Self::OlderThanStore),
            0x6 => Ok(Self::PageFull),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum InventoryKind {
    Buses = 0x1,
    Devices = 0x2,
    Components = 0x3,
    Signals = 0x4,
    Parameters = 0x5,
}

impl TryFrom<u8> for InventoryKind {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Buses),
            0x2 => Ok(Self::Devices),
            0x3 => Ok(Self::Components),
            0x4 => Ok(Self::Signals),
            0x5 => Ok(Self::Parameters),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Presence {
    Online = 0x1,
    Degraded = 0x2,
    Offline = 0x3,
    NeverSeen = 0x4,
}

impl TryFrom<u8> for Presence {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Online),
            0x2 => Ok(Self::Degraded),
            0x3 => Ok(Self::Offline),
            0x4 => Ok(Self::NeverSeen),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Provenance {
    None = 0x0,
    Measured = 0x1,
    Counted = 0x2,
    Derived = 0x3,
    Estimated = 0x4,
    Reported = 0x5,
    Commanded = 0x6,
}

impl TryFrom<u8> for Provenance {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x0 => Ok(Self::None),
            0x1 => Ok(Self::Measured),
            0x2 => Ok(Self::Counted),
            0x3 => Ok(Self::Derived),
            0x4 => Ok(Self::Estimated),
            0x5 => Ok(Self::Reported),
            0x6 => Ok(Self::Commanded),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Quality {
    Measured = 0x1,
    Counted = 0x2,
    Estimated = 0x3,
    Stale = 0x4,
    Absent = 0x5,
}

impl TryFrom<u8> for Quality {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Measured),
            0x2 => Ok(Self::Counted),
            0x3 => Ok(Self::Estimated),
            0x4 => Ok(Self::Stale),
            0x5 => Ok(Self::Absent),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Severity {
    Info = 0x1,
    Warning = 0x2,
    Fault = 0x3,
    Protection = 0x4,
}

impl TryFrom<u8> for Severity {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Info),
            0x2 => Ok(Self::Warning),
            0x3 => Ok(Self::Fault),
            0x4 => Ok(Self::Protection),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Shape {
    Scalar = 0x1,
    Series = 0x2,
}

impl TryFrom<u8> for Shape {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Scalar),
            0x2 => Ok(Self::Series),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum SignalDomain {
    Live = 0x1,
    Lifetime = 0x2,
    SinceReset = 0x3,
    Today = 0x4,
    Yesterday = 0x5,
    LimitUpper = 0x6,
    LimitLower = 0x7,
    Max = 0x8,
    Min = 0x9,
}

impl TryFrom<u8> for SignalDomain {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Live),
            0x2 => Ok(Self::Lifetime),
            0x3 => Ok(Self::SinceReset),
            0x4 => Ok(Self::Today),
            0x5 => Ok(Self::Yesterday),
            0x6 => Ok(Self::LimitUpper),
            0x7 => Ok(Self::LimitLower),
            0x8 => Ok(Self::Max),
            0x9 => Ok(Self::Min),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum TimeSource {
    Client = 0x1,
    NtpViaComms = 0x2,
}

impl TryFrom<u8> for TimeSource {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Client),
            0x2 => Ok(Self::NtpViaComms),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum TopologyChangeReason {
    Boot = 0x1,
    ConfigWrite = 0x2,
    SubDeviceAdopted = 0x3,
    SubDeviceRemoved = 0x4,
    DeviceReplaced = 0x5,
}

impl TryFrom<u8> for TopologyChangeReason {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Boot),
            0x2 => Ok(Self::ConfigWrite),
            0x3 => Ok(Self::SubDeviceAdopted),
            0x4 => Ok(Self::SubDeviceRemoved),
            0x5 => Ok(Self::DeviceReplaced),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Transport {
    Rs485 = 0x1,
    Can = 0x2,
    VeDirect = 0x3,
    LocalIo = 0x4,
    Ip = 0x5,
    Onewire = 0x6,
    Internal = 0x7,
}

impl TryFrom<u8> for Transport {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Rs485),
            0x2 => Ok(Self::Can),
            0x3 => Ok(Self::VeDirect),
            0x4 => Ok(Self::LocalIo),
            0x5 => Ok(Self::Ip),
            0x6 => Ok(Self::Onewire),
            0x7 => Ok(Self::Internal),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Unit {
    Volt = 0x1,
    Ampere = 0x2,
    Watt = 0x3,
    WattHour = 0x4,
    AmpereHour = 0x5,
    DegreeCelsius = 0x6,
    Percent = 0x7,
    Hertz = 0x8,
    Second = 0x9,
    Minute = 0xa,
    Hour = 0xb,
    Count = 0xc,
    Ohm = 0xd,
    Pascal = 0xe,
    Litre = 0xf,
    None = 0x10,
}

impl TryFrom<u8> for Unit {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Volt),
            0x2 => Ok(Self::Ampere),
            0x3 => Ok(Self::Watt),
            0x4 => Ok(Self::WattHour),
            0x5 => Ok(Self::AmpereHour),
            0x6 => Ok(Self::DegreeCelsius),
            0x7 => Ok(Self::Percent),
            0x8 => Ok(Self::Hertz),
            0x9 => Ok(Self::Second),
            0xa => Ok(Self::Minute),
            0xb => Ok(Self::Hour),
            0xc => Ok(Self::Count),
            0xd => Ok(Self::Ohm),
            0xe => Ok(Self::Pascal),
            0xf => Ok(Self::Litre),
            0x10 => Ok(Self::None),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Validity {
    Ok = 0x1,
    Stale = 0x2,
    Initialising = 0x3,
    Unsupported = 0x4,
    SensorFault = 0x5,
    OutOfRange = 0x6,
    Absent = 0x7,
    UnnamedState = 0x8,
}

impl TryFrom<u8> for Validity {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Ok),
            0x2 => Ok(Self::Stale),
            0x3 => Ok(Self::Initialising),
            0x4 => Ok(Self::Unsupported),
            0x5 => Ok(Self::SensorFault),
            0x6 => Ok(Self::OutOfRange),
            0x7 => Ok(Self::Absent),
            0x8 => Ok(Self::UnnamedState),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum Vtype {
    Gauge = 0x1,
    Counter = 0x2,
    Enum = 0x3,
    Flags = 0x4,
}

impl TryFrom<u8> for Vtype {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Gauge),
            0x2 => Ok(Self::Counter),
            0x3 => Ok(Self::Enum),
            0x4 => Ok(Self::Flags),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u16)]
pub enum BehaviourKey {
    Shadow = 0x1,
}

impl TryFrom<u16> for BehaviourKey {
    type Error = ();

    fn try_from(v: u16) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Shadow),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u16)]
pub enum CapabilityBit {
    EventLogReadable = 0x0,
    ConfigurationWritable = 0x1,
    CommandsAccepted = 0x2,
    FirmwareUpdateAccepted = 0x3,
    ClockSettableByClient = 0x4,
    CountedStateOfChargeAvailable = 0x5,
    ACMeteringOnTheGenerator = 0x6,
    AnyBehaviourIsInShadowMode = 0x7,
}

impl TryFrom<u16> for CapabilityBit {
    type Error = ();

    fn try_from(v: u16) -> Result<Self, Self::Error> {
        match v {
            0x0 => Ok(Self::EventLogReadable),
            0x1 => Ok(Self::ConfigurationWritable),
            0x2 => Ok(Self::CommandsAccepted),
            0x3 => Ok(Self::FirmwareUpdateAccepted),
            0x4 => Ok(Self::ClockSettableByClient),
            0x5 => Ok(Self::CountedStateOfChargeAvailable),
            0x6 => Ok(Self::ACMeteringOnTheGenerator),
            0x7 => Ok(Self::AnyBehaviourIsInShadowMode),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u16)]
pub enum CommandKind {
    StartGenerator = 0x101,
    StopGenerator = 0x102,
    RunExerciseCycleNow = 0x103,
    SetOutput = 0x201,
    AcknowledgeConcern = 0x203,
    ClearOverride = 0x301,
}

impl TryFrom<u16> for CommandKind {
    type Error = ();

    fn try_from(v: u16) -> Result<Self, Self::Error> {
        match v {
            0x101 => Ok(Self::StartGenerator),
            0x102 => Ok(Self::StopGenerator),
            0x103 => Ok(Self::RunExerciseCycleNow),
            0x201 => Ok(Self::SetOutput),
            0x203 => Ok(Self::AcknowledgeConcern),
            0x301 => Ok(Self::ClearOverride),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u16)]
pub enum ConfigSection {
    IdentityAndSite = 0x1,
    Channels = 0x2,
    BusesAndDevices = 0x3,
    GeneratorBehaviour = 0x10,
    FrostBehaviour = 0x11,
    ScheduleBehaviour = 0x12,
    LoadShedBehaviour = 0x13,
    Network = 0x20,
    Cloud = 0x21,
}

impl TryFrom<u16> for ConfigSection {
    type Error = ();

    fn try_from(v: u16) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::IdentityAndSite),
            0x2 => Ok(Self::Channels),
            0x3 => Ok(Self::BusesAndDevices),
            0x10 => Ok(Self::GeneratorBehaviour),
            0x11 => Ok(Self::FrostBehaviour),
            0x12 => Ok(Self::ScheduleBehaviour),
            0x13 => Ok(Self::LoadShedBehaviour),
            0x20 => Ok(Self::Network),
            0x21 => Ok(Self::Cloud),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum ClientConnected {
    Accepted = 0x1,
    RefusedTableFull = 0x2,
    RefusedHandleInUse = 0x3,
    RefusedLinkNotUp = 0x4,
}

impl TryFrom<u8> for ClientConnected {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Accepted),
            0x2 => Ok(Self::RefusedTableFull),
            0x3 => Ok(Self::RefusedHandleInUse),
            0x4 => Ok(Self::RefusedLinkNotUp),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum ClientDisconnected {
    Released = 0x1,
    UnknownHandle = 0x2,
}

impl TryFrom<u8> for ClientDisconnected {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Released),
            0x2 => Ok(Self::UnknownHandle),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum CloseConnection {
    Closed = 0x1,
    UnknownHandle = 0x2,
}

impl TryFrom<u8> for CloseConnection {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Closed),
            0x2 => Ok(Self::UnknownHandle),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum CommsRelease {
    Authorised = 0x1,
    Installed = 0x2,
    Activated = 0x3,
    RefusedDigestMismatch = 0x4,
    RefusedSignature = 0x5,
    RefusedNoSpace = 0x6,
    RolledBack = 0x7,
}

impl TryFrom<u8> for CommsRelease {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Authorised),
            0x2 => Ok(Self::Installed),
            0x3 => Ok(Self::Activated),
            0x4 => Ok(Self::RefusedDigestMismatch),
            0x5 => Ok(Self::RefusedSignature),
            0x6 => Ok(Self::RefusedNoSpace),
            0x7 => Ok(Self::RolledBack),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum EnterDownload {
    Entering = 0x1,
    RefusedOutsideWindow = 0x2,
}

impl TryFrom<u8> for EnterDownload {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Entering),
            0x2 => Ok(Self::RefusedOutsideWindow),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum NetConfig {
    Stored = 0x1,
    RejectedInvalid = 0x2,
    NvsWriteFailed = 0x3,
}

impl TryFrom<u8> for NetConfig {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Stored),
            0x2 => Ok(Self::RejectedInvalid),
            0x3 => Ok(Self::NvsWriteFailed),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum TimeOffer {
    Accepted = 0x1,
    RefusedImplausible = 0x2,
    RefusedStepTooLarge = 0x4,
    RefusedRateLimited = 0x5,
}

impl TryFrom<u8> for TimeOffer {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Accepted),
            0x2 => Ok(Self::RefusedImplausible),
            0x4 => Ok(Self::RefusedStepTooLarge),
            0x5 => Ok(Self::RefusedRateLimited),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum CloseReason {
    SessionExpired = 0x1,
    Shedding = 0x2,
    AuthenticationFailures = 0x3,
    Resync = 0x4,
}

impl TryFrom<u8> for CloseReason {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::SessionExpired),
            0x2 => Ok(Self::Shedding),
            0x3 => Ok(Self::AuthenticationFailures),
            0x4 => Ok(Self::Resync),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum CommsReleaseOp {
    Authorise = 0x1,
    Activate = 0x2,
    Revoke = 0x3,
    ConfirmHealthy = 0x4,
}

impl TryFrom<u8> for CommsReleaseOp {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Authorise),
            0x2 => Ok(Self::Activate),
            0x3 => Ok(Self::Revoke),
            0x4 => Ok(Self::ConfirmHealthy),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum DisconnectReason {
    ClosedByClient = 0x1,
    TransportError = 0x2,
    IdleTimeout = 0x3,
    ClosedByComms = 0x4,
}

impl TryFrom<u8> for DisconnectReason {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::ClosedByClient),
            0x2 => Ok(Self::TransportError),
            0x3 => Ok(Self::IdleTimeout),
            0x4 => Ok(Self::ClosedByComms),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum DownloadReason {
    Bench = 0x1,
    Recovery = 0x2,
}

impl TryFrom<u8> for DownloadReason {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Bench),
            0x2 => Ok(Self::Recovery),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum LinkTransport {
    Ble = 0x1,
    WifiLocal = 0x2,
    Cloud = 0x3,
    Usb = 0x4,
}

impl TryFrom<u8> for LinkTransport {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Ble),
            0x2 => Ok(Self::WifiLocal),
            0x3 => Ok(Self::Cloud),
            0x4 => Ok(Self::Usb),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum NetConfigOp {
    Set = 0x1,
    Clear = 0x2,
}

impl TryFrom<u8> for NetConfigOp {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x1 => Ok(Self::Set),
            0x2 => Ok(Self::Clear),
            _ => Err(()),
        }
    }
}

/// Whether a receiver may read this code out of a **bare** body.
///
/// The registry's MAC'd column, which is the receiver's check and never
/// the sender's: P-142 decides the shape by whether the *sender* holds
/// a session, so a rule read off this column would be one the cases
/// with no session cannot obey. What it says is what a receiver will
/// accept, and a bare body carrying a code marked here is discarded
/// under P-051 rather than acted on. Sorted, so a lookup can bisect.
pub const ERROR_NEEDS_A_MAC: &[(u16, bool)] = &[
    (1, false),
    (2, false),
    (3, false),
    (4, false),
    (5, false),
    (6, true),
    (7, true),
    (8, false),
    (9, false),
    (10, false),
    (11, true),
    (12, false),
    (14, false),
    (18, false),
];

impl ErrorCode {
    /// Whether a receiver refuses to read this code out of a bare body.
    #[must_use]
    pub fn needs_a_mac(self) -> bool {
        ERROR_NEEDS_A_MAC
            .binary_search_by_key(&(self as u16), |&(c, _)| c)
            .ok()
            .and_then(|i| ERROR_NEEDS_A_MAC.get(i))
            .is_some_and(|&(_, m)| m)
    }
}

/// Which records survive a controller under pressure.
///
/// The registry's class column, and the two words are defined there
/// normatively rather than in a design document — a column with no
/// definition beside it is one every implementation fills in for itself,
/// and the two answers it picks between are *keep this alarm* and *drop
/// it*. A controller that ranks a value change above an alarm raised
/// loses the alarm on the busiest day, which is the day it mattered.
/// Sorted, so a lookup can bisect.
pub const EVENT_IS_CLASS_A: &[(u16, bool)] = &[
    (258, true),
    (513, true),
    (514, true),
    (515, true),
    (769, true),
    (770, true),
    (1025, true),
    (1281, true),
    (1282, true),
    (1537, true),
    (1538, true),
    (1539, true),
    (1540, true),
    (1793, true),
    (1794, true),
    (2049, true),
    (2050, true),
    (2051, true),
    (2052, true),
    (2053, true),
    (2305, true),
    (2306, true),
];

impl EventKind {
    /// Whether this record is never dropped — not from the log, and not
    /// from a queue.
    ///
    /// `None` for a kind this build has never heard of. Not `false`: a
    /// controller that treated an unknown record as droppable would shed
    /// exactly the records a newer firmware added because they mattered.
    #[must_use]
    pub fn is_class_a(self) -> Option<bool> {
        EVENT_IS_CLASS_A
            .binary_search_by_key(&self.0, |&(k, _)| k)
            .ok()
            .and_then(|i| EVENT_IS_CLASS_A.get(i))
            .map(|&(_, a)| a)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u16)]
pub enum LinkErrorCode {
    WrongSide = 0x100,
    LinkTypeOnClientTransport = 0x101,
    BeforeLinkUp = 0x102,
    UnknownHandle = 0x103,
    ConnectionTableFull = 0x104,
    LinkMajorMismatch = 0x105,
    TooManyOutstanding = 0x106,
    NonZeroSession = 0x107,
    NoAuthorisation = 0x108,
}

impl TryFrom<u16> for LinkErrorCode {
    type Error = ();

    fn try_from(v: u16) -> Result<Self, Self::Error> {
        match v {
            0x100 => Ok(Self::WrongSide),
            0x101 => Ok(Self::LinkTypeOnClientTransport),
            0x102 => Ok(Self::BeforeLinkUp),
            0x103 => Ok(Self::UnknownHandle),
            0x104 => Ok(Self::ConnectionTableFull),
            0x105 => Ok(Self::LinkMajorMismatch),
            0x106 => Ok(Self::TooManyOutstanding),
            0x107 => Ok(Self::NonZeroSession),
            0x108 => Ok(Self::NoAuthorisation),
            _ => Err(()),
        }
    }
}

/// A code off the wire, kept in the space it came from.
///
/// Widening `ErrorCode` to hold the link-local range would make a
/// routing fault in the comms processor look like the client's own
/// request failing, and the two want different retries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Incoming {
    Client(ErrorCode),
    LinkLocal(LinkErrorCode),
    Unknown(u16),
}

impl From<u16> for Incoming {
    fn from(v: u16) -> Self {
        ErrorCode::try_from(v).map_or_else(
            |()| LinkErrorCode::try_from(v).map_or(Self::Unknown(v), Self::LinkLocal),
            Self::Client,
        )
    }
}

/// The per-client capability mask, fixed at enrolment.
///
/// Not a wire discriminant: an unallocated bit is a capability
/// nobody has defined yet, not a value to reject.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct ClientCapability(pub u16);

impl ClientCapability {
    pub const WRITE_CONFIG: Self = Self(1 << 0);
    pub const WRITE_NETWORK_AND_CLOUD: Self = Self(1 << 1);
    pub const SEND_COMMAND: Self = Self(1 << 2);
    pub const SET_CLOCK: Self = Self(1 << 3);
    pub const PUSH_FIRMWARE: Self = Self(1 << 4);

    #[must_use]
    pub fn allows(self, want: Self) -> bool {
        self.0 & want.0 == want.0
    }

    /// The mask this `client_kind` is handed at enrolment.
    ///
    /// No message raises one and no message lowers one: either is a
    /// re-pair, which means somebody standing at the button.
    ///
    /// Left unformatted: a kind list long enough to wrap would be
    /// rewritten by `cargo fmt` into something this generator does not
    /// emit, after which `cargo fmt` and `cargo xtask check` cannot
    /// both be green and the fix is not obvious from either.
    #[rustfmt::skip]
    #[must_use]
    pub const fn granted(kind: ClientKind) -> Self {
        match kind {
            ClientKind::App | ClientKind::Browser | ClientKind::Cli => Self(0b11111),
            ClientKind::Cloud => Self(0b00101),
        }
    }
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct MetricKind(pub u16);

impl MetricKind {
    pub const DC_VOLTAGE: Self = Self(0x0101);
    pub const DC_CURRENT: Self = Self(0x0102);
    pub const DC_POWER: Self = Self(0x0103);
    pub const STATE_OF_CHARGE: Self = Self(0x0104);
    pub const AC_VOLTAGE: Self = Self(0x0201);
    pub const AC_CURRENT: Self = Self(0x0202);
    pub const AC_POWER: Self = Self(0x0203);
    pub const AC_FREQUENCY: Self = Self(0x0204);
    pub const AC_ENERGY: Self = Self(0x0205);
    pub const AC_ENERGY_IMPORTED: Self = Self(0x0206);
    pub const AC_ENERGY_EXPORTED: Self = Self(0x0207);
    pub const TEMPERATURE: Self = Self(0x0302);
    pub const TANK_LEVEL: Self = Self(0x0401);
    pub const TANK_SENDER_CURRENT: Self = Self(0x0402);
    pub const GENERATOR_STATE: Self = Self(0x0501);
    pub const GENERATOR_RUN_HOURS: Self = Self(0x0502);
    pub const GENERATOR_STARTS_SINCE_COMMISSIONING: Self = Self(0x0503);
    pub const RUN_CONTACT_COMMANDED: Self = Self(0x0504);
    pub const GENERATOR_SELECTOR_POSITION: Self = Self(0x0601);
    pub const UPTIME_SINCE_BOOT: Self = Self(0x0602);
    pub const LAST_BOOT_REASON: Self = Self(0x0603);
    pub const LOG_RING_UTILISATION: Self = Self(0x0604);
    pub const TIME_IN_BULK: Self = Self(0x0701);
    pub const TIME_IN_ABSORPTION: Self = Self(0x0702);
    pub const TIME_IN_FLOAT: Self = Self(0x0703);
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct EventKind(pub u16);

impl EventKind {
    pub const SIGNAL_VALIDITY_CHANGED: Self = Self(0x0102);
    pub const GENERATOR_STATE_CHANGED: Self = Self(0x0201);
    pub const GENERATOR_COMMAND_WITHDRAWN: Self = Self(0x0202);
    pub const GENERATOR_STOP_NOT_HONOURED: Self = Self(0x0203);
    pub const BEHAVIOUR_DECISION: Self = Self(0x0301);
    pub const BEHAVIOUR_INHIBITED: Self = Self(0x0302);
    pub const OUTPUT_CHANGED: Self = Self(0x0401);
    pub const CONCERN_RAISED: Self = Self(0x0501);
    pub const CONCERN_CHANGED: Self = Self(0x0502);
    pub const BOOT: Self = Self(0x0601);
    pub const CONFIG_CHANGED: Self = Self(0x0602);
    pub const CLIENT_ENROLLED: Self = Self(0x0603);
    pub const TIME_SET: Self = Self(0x0604);
    pub const RECORDS_DROPPED: Self = Self(0x0701);
    pub const RECORD_FAILED_CRC: Self = Self(0x0702);
    pub const COMMS_LINK_LOST: Self = Self(0x0801);
    pub const COMMS_POWER_CYCLED: Self = Self(0x0802);
    pub const COMMS_UNRECOVERABLE: Self = Self(0x0803);
    pub const SESSIONS_SHED_FOR_BACKPRESSURE: Self = Self(0x0804);
    pub const COMMS_BOOT_NOISE: Self = Self(0x0805);
    pub const TOPOLOGY_CHANGED: Self = Self(0x0901);
    pub const DEVICE_PRESENCE_CHANGED: Self = Self(0x0902);
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct ComponentRole(pub u16);

impl ComponentRole {
    pub const PV_ARRAY: Self = Self(0x0001);
    pub const MPPT_TRACKER: Self = Self(0x0002);
    pub const BATTERY_BANK: Self = Self(0x0003);
    pub const BATTERY_PACK: Self = Self(0x0004);
    pub const HEATER: Self = Self(0x0005);
    pub const CONTACTOR: Self = Self(0x0006);
    pub const FET: Self = Self(0x0007);
    pub const AC_INPUT: Self = Self(0x0008);
    pub const AC_OUTPUT: Self = Self(0x0009);
    pub const PHASE: Self = Self(0x000a);
    pub const LINE_PAIR: Self = Self(0x000b);
    pub const DC_OUTPUT: Self = Self(0x000c);
    pub const LOAD_OUTPUT: Self = Self(0x000d);
    pub const START_BATTERY: Self = Self(0x000e);
    pub const METER: Self = Self(0x000f);
    pub const CIRCUIT: Self = Self(0x0010);
    pub const MERGED_CIRCUIT: Self = Self(0x0011);
    pub const TRANSFER_RELAY: Self = Self(0x0012);
    pub const INVERTER: Self = Self(0x0013);
    pub const CHARGER: Self = Self(0x0014);
    pub const PROBE: Self = Self(0x0015);
    pub const TANK: Self = Self(0x0016);
    pub const CELL: Self = Self(0x0017);
    pub const RELAY: Self = Self(0x0018);
    pub const GENERATOR: Self = Self(0x0019);
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct Condition(pub u16);

impl Condition {
    pub const OVER_VOLTAGE: Self = Self(0x0001);
    pub const UNDER_VOLTAGE: Self = Self(0x0002);
    pub const OVER_TEMPERATURE: Self = Self(0x0003);
    pub const UNDER_TEMPERATURE: Self = Self(0x0004);
    pub const CHARGE_OVER_CURRENT: Self = Self(0x0005);
    pub const DISCHARGE_OVER_CURRENT: Self = Self(0x0006);
    pub const SHORT_CIRCUIT: Self = Self(0x0007);
    pub const OVERLOAD: Self = Self(0x0008);
    pub const CELL_IMBALANCE: Self = Self(0x0009);
    pub const LOW_STATE_OF_CHARGE: Self = Self(0x000a);
    pub const CHARGE_INHIBITED: Self = Self(0x000b);
    pub const DISCHARGE_INHIBITED: Self = Self(0x000c);
    pub const UNNAMED_STATE: Self = Self(0x000d);
    pub const REGISTRATION_REFUSED: Self = Self(0x000e);
    pub const SERIES_TOO_LONG: Self = Self(0x000f);
    pub const INVENTORY_FULL: Self = Self(0x0010);
    pub const BAY_FLAPPING: Self = Self(0x0011);
    pub const COUNTER_WRITE_FAILED: Self = Self(0x0012);
    pub const EPOCH_WRITE_FAILED: Self = Self(0x0013);
    pub const CLOCK_STEPPED: Self = Self(0x0014);
    pub const FLOOR_OVERRIDDEN: Self = Self(0x0015);
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct DeviceRole(pub u16);

impl DeviceRole {
    pub const SOLAR_CHARGER: Self = Self(0x0001);
    pub const INVERTER: Self = Self(0x0002);
    pub const INVERTER_CHARGER: Self = Self(0x0003);
    pub const BMS: Self = Self(0x0004);
    pub const ENERGY_METER: Self = Self(0x0005);
    pub const SHUNT: Self = Self(0x0006);
    pub const SENSOR: Self = Self(0x0007);
    pub const POWER_MODULE: Self = Self(0x0008);
    pub const CONTROLLER: Self = Self(0x0009);
    pub const BATTERY_MONITOR: Self = Self(0x000a);
    pub const TEMPERATURE_SENSOR: Self = Self(0x000b);
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct Dialect(pub u16);

impl Dialect {
    pub const NO_PROTOCOL: Self = Self(0x0001);
    pub const PZEM_DC: Self = Self(0x0002);
    pub const EPEVER_B: Self = Self(0x0003);
    pub const VICTRON_MPPT_RS_HEX: Self = Self(0x0004);
    pub const VICTRON_GX_MODBUS_VEBUS: Self = Self(0x0005);
    pub const EG4_LIFEPOWER4_SERIAL: Self = Self(0x0006);
    pub const MORNINGSTAR_SUNSAVER_DUO: Self = Self(0x0007);
    pub const EMPORIA_VUE3_ESPHOME_I2C: Self = Self(0x0008);
    pub const ECOFLOW_POWER_KITS: Self = Self(0x0009);
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct EnumSpace(pub u16);

impl EnumSpace {
    pub const PRESENCE: Self = Self(0x0001);
    pub const CONTROL_OWNER: Self = Self(0x0002);
    pub const GENERATOR_STATE: Self = Self(0x0003);
    pub const GENERATOR_SELECTOR: Self = Self(0x0004);
    pub const BOOT_REASON: Self = Self(0x0005);
    pub const CHARGE_STAGE: Self = Self(0x0006);
    pub const BALANCING: Self = Self(0x0007);
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct MeasurementPoint(pub u16);

impl MeasurementPoint {
    pub const LINE_TO_NEUTRAL: Self = Self(0x0001);
    pub const LINE_TO_LINE: Self = Self(0x0002);
    pub const TERMINAL: Self = Self(0x0003);
    pub const CELL: Self = Self(0x0004);
    pub const INTERNAL: Self = Self(0x0005);
    pub const AMBIENT: Self = Self(0x0006);
    pub const HEATSINK: Self = Self(0x0007);
    pub const CASE: Self = Self(0x0008);
    pub const INLET: Self = Self(0x0009);
    pub const OUTLET: Self = Self(0x000a);
    pub const TRANSFORMER: Self = Self(0x000b);
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct Product(pub u16);

impl Product {
    pub const ORIGIN_89_CONTROLLER: Self = Self(0x0001);
    pub const PZEM_003: Self = Self(0x0002);
    pub const PZEM_017: Self = Self(0x0003);
    pub const EPEVER_TRACER_B: Self = Self(0x0004);
    pub const VICTRON_MPPT_RS: Self = Self(0x0005);
    pub const VICTRON_MULTIPLUS: Self = Self(0x0006);
    pub const EG4_LIFEPOWER4: Self = Self(0x0007);
    pub const MORNINGSTAR_SUNSAVER_DUO: Self = Self(0x0008);
    pub const EMPORIA_VUE_3: Self = Self(0x0009);
    pub const ECOFLOW_POWER_KIT: Self = Self(0x000a);
}

/// Open set: a value this list does not name is carried, not refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct VendorNamespace(pub u16);

impl VendorNamespace {
    pub const VICTRON: Self = Self(0x0001);
    pub const EPEVER: Self = Self(0x0002);
    pub const PZEM: Self = Self(0x0003);
    pub const EG4: Self = Self(0x0004);
    pub const MORNINGSTAR: Self = Self(0x0005);
    pub const EMPORIA: Self = Self(0x0006);
    pub const ECOFLOW: Self = Self(0x0007);
    pub const MAGNUM: Self = Self(0x0008);
    pub const XANTREX: Self = Self(0x0009);
}

/// What every enum space contains, by the registry's own tables. Sorted on
/// both axes, so a lookup can bisect. A space with no members is absent here
/// rather than present and empty.
pub const ENUM_SPACE_MEMBERS: &[(u16, &[i32])] = &[
    (0x0001, &[1, 2, 3, 4]),
    (0x0002, &[1, 2, 3, 4, 5, 6]),
    (0x0003, &[1, 2, 3, 4, 5, 6]),
    (0x0004, &[1, 2, 3]),
    (0x0005, &[1, 2, 4, 5, 6, 7, 8, 9]),
];

impl EnumSpace {
    /// The values this build can name in this space, or `None` where it names
    /// none at all.
    ///
    /// The `None` is the case worth having: a space allocated with no members
    /// can never name one of its own values, so a signal drawn from it reads
    /// `unnamed_state` at every poll. That is a registry entry half written,
    /// and it is a different thing from a device reporting a state this build
    /// has not heard of.
    #[must_use]
    pub fn members(self) -> Option<&'static [i32]> {
        let at = ENUM_SPACE_MEMBERS
            .binary_search_by_key(&self.0, |&(space, _)| space)
            .ok()?;
        ENUM_SPACE_MEMBERS.get(at).map(|&(_, members)| members)
    }

    /// Whether this build can name `value` as a member of this space.
    ///
    /// False for a space that names nothing, which is deliberate: the caller
    /// that needs to tell the two apart asks [`Self::members`].
    #[must_use]
    pub fn names(self, value: i32) -> bool {
        self.members()
            .is_some_and(|members| members.binary_search(&value).is_ok())
    }
}

/// Every metric with the unit and scale it is read in:
/// `value = raw * 10^scale`. Sorted, so a lookup can bisect.
pub const METRIC_UNITS: &[(u16, &str, i8)] = &[
    (0x0101, "V", -3),
    (0x0102, "A", -3),
    (0x0103, "W", -1),
    (0x0104, "%", -1),
    (0x0105, "°C", -1),
    (0x0110, "V", -3),
    (0x0111, "A", -3),
    (0x0112, "W", -1),
    (0x0120, "A", -3),
    (0x0121, "W", -1),
    (0x0130, "V", -3),
    (0x0201, "V", -1),
    (0x0202, "A", -3),
    (0x0203, "W", -1),
    (0x0204, "Hz", -2),
    (0x0205, "Wh", 0),
    (0x0206, "Wh", 0),
    (0x0207, "Wh", 0),
    (0x0301, "°C", -1),
    (0x0302, "°C", -1),
    (0x0401, "%", -1),
    (0x0402, "A", -6),
    (0x0501, "—", 0),
    (0x0502, "h", -2),
    (0x0503, "count", 0),
    (0x0504, "—", 0),
    (0x0601, "—", 0),
    (0x0602, "s", 0),
    (0x0603, "—", 0),
    (0x0604, "%", -1),
    (0x0701, "min", 0),
    (0x0702, "min", 0),
    (0x0703, "min", 0),
];

impl MetricKind {
    #[must_use]
    pub fn unit_and_scale(self) -> Option<(&'static str, i8)> {
        METRIC_UNITS
            .binary_search_by_key(&self.0, |&(k, _, _)| k)
            .ok()
            .and_then(|i| METRIC_UNITS.get(i))
            .map(|&(_, u, s)| (u, s))
    }
}

/// The public equipment dataset's word for a reading: a metric kind over a
/// signal domain, at a place. A `None` place matches any; the domain never
/// does, so a limit or a period counter cannot borrow a live reading's word.
/// Rows are most specific first, so the first match is the one to take.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct DatasetMetric {
    pub kind: MetricKind,
    pub domain: SignalDomain,
    pub role: Option<ComponentRole>,
    pub point: Option<MeasurementPoint>,
    pub name: &'static str,
}

pub const DATASET_METRICS: &[DatasetMetric] = &[
    DatasetMetric {
        kind: MetricKind(0x0101),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0001)),
        point: None,
        name: "pv-voltage",
    },
    DatasetMetric {
        kind: MetricKind(0x0101),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0002)),
        point: None,
        name: "pv-voltage",
    },
    DatasetMetric {
        kind: MetricKind(0x0101),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0003)),
        point: None,
        name: "battery-voltage",
    },
    DatasetMetric {
        kind: MetricKind(0x0101),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0004)),
        point: None,
        name: "battery-voltage",
    },
    DatasetMetric {
        kind: MetricKind(0x0101),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x000d)),
        point: None,
        name: "load-voltage",
    },
    DatasetMetric {
        kind: MetricKind(0x0102),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0001)),
        point: None,
        name: "pv-current",
    },
    DatasetMetric {
        kind: MetricKind(0x0102),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0002)),
        point: None,
        name: "pv-current",
    },
    DatasetMetric {
        kind: MetricKind(0x0102),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0003)),
        point: None,
        name: "battery-current",
    },
    DatasetMetric {
        kind: MetricKind(0x0102),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0004)),
        point: None,
        name: "battery-current",
    },
    DatasetMetric {
        kind: MetricKind(0x0102),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x000d)),
        point: None,
        name: "load-current",
    },
    DatasetMetric {
        kind: MetricKind(0x0103),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0001)),
        point: None,
        name: "pv-power",
    },
    DatasetMetric {
        kind: MetricKind(0x0103),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0002)),
        point: None,
        name: "pv-power",
    },
    DatasetMetric {
        kind: MetricKind(0x0103),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0003)),
        point: None,
        name: "battery-power",
    },
    DatasetMetric {
        kind: MetricKind(0x0103),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0004)),
        point: None,
        name: "battery-power",
    },
    DatasetMetric {
        kind: MetricKind(0x0103),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x000d)),
        point: None,
        name: "load-power",
    },
    DatasetMetric {
        kind: MetricKind(0x0302),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0003)),
        point: None,
        name: "battery-temperature",
    },
    DatasetMetric {
        kind: MetricKind(0x0302),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0004)),
        point: None,
        name: "battery-temperature",
    },
    DatasetMetric {
        kind: MetricKind(0x0302),
        domain: SignalDomain::Live,
        role: Some(ComponentRole(0x0017)),
        point: None,
        name: "battery-temperature",
    },
    DatasetMetric {
        kind: MetricKind(0x0104),
        domain: SignalDomain::Live,
        role: None,
        point: None,
        name: "state-of-charge",
    },
    DatasetMetric {
        kind: MetricKind(0x0201),
        domain: SignalDomain::Live,
        role: None,
        point: None,
        name: "ac-voltage",
    },
    DatasetMetric {
        kind: MetricKind(0x0202),
        domain: SignalDomain::Live,
        role: None,
        point: None,
        name: "ac-current",
    },
    DatasetMetric {
        kind: MetricKind(0x0203),
        domain: SignalDomain::Live,
        role: None,
        point: None,
        name: "ac-power",
    },
    DatasetMetric {
        kind: MetricKind(0x0204),
        domain: SignalDomain::Live,
        role: None,
        point: None,
        name: "ac-frequency",
    },
    DatasetMetric {
        kind: MetricKind(0x0205),
        domain: SignalDomain::Lifetime,
        role: None,
        point: None,
        name: "ac-energy-total",
    },
    DatasetMetric {
        kind: MetricKind(0x0205),
        domain: SignalDomain::Today,
        role: None,
        point: None,
        name: "ac-energy-today",
    },
    DatasetMetric {
        kind: MetricKind(0x0302),
        domain: SignalDomain::Live,
        role: None,
        point: None,
        name: "temperature",
    },
    DatasetMetric {
        kind: MetricKind(0x0401),
        domain: SignalDomain::Live,
        role: None,
        point: None,
        name: "tank-level",
    },
    DatasetMetric {
        kind: MetricKind(0x0501),
        domain: SignalDomain::Live,
        role: None,
        point: None,
        name: "generator-run-state",
    },
    DatasetMetric {
        kind: MetricKind(0x0502),
        domain: SignalDomain::Lifetime,
        role: None,
        point: None,
        name: "generator-run-hours",
    },
    DatasetMetric {
        kind: MetricKind(0x0602),
        domain: SignalDomain::SinceReset,
        role: None,
        point: None,
        name: "uptime",
    },
];

/// Dataset words no metric carries, each with why.
pub const DATASET_ABSENT: &[(&str, &str)] = &[
    ("ac-apparent-power", "no metric kind"),
    ("ac-power-factor", "no metric kind"),
    (
        "charge-stage",
        "the charge stage enum space has no members yet (#3)",
    ),
    ("consumed-amp-hours", "no DC charge counter kind (#2)"),
    ("cycle-count", "no metric kind"),
    ("humidity", "no metric kind"),
    ("link-downlink", "no metric kind"),
    ("link-latency", "no metric kind"),
    (
        "link-online",
        "link state is presence and the comms link events, not a metric",
    ),
    (
        "link-signal-quality",
        "no metric kind; the comms processor's radio is not a reading the controller carries",
    ),
    ("link-uplink", "no metric kind"),
    ("pressure", "no metric kind"),
    ("pv-energy-today", "no DC energy kind (#2)"),
    ("pv-energy-total", "no DC energy kind (#2)"),
    ("pv-irradiance", "no metric kind"),
    ("state-of-health", "no metric kind"),
    (
        "switch-state",
        "the only switch metric is the generator run contact command, an echo of a command rather than a measured state",
    ),
    (
        "tank-volume",
        "the protocol carries a tank level in percent, never a volume",
    ),
    ("time-to-go", "no metric kind"),
];

impl MetricKind {
    /// The dataset's word for this kind over a domain at a place, or `None`
    /// when it has none.
    #[must_use]
    pub fn dataset_name(
        self,
        domain: SignalDomain,
        role: Option<ComponentRole>,
        point: Option<MeasurementPoint>,
    ) -> Option<&'static str> {
        DATASET_METRICS
            .iter()
            .find(|m| {
                m.kind == self
                    && m.domain == domain
                    && m.role.is_none_or(|r| Some(r) == role)
                    && m.point.is_none_or(|p| Some(p) == point)
            })
            .map(|m| m.name)
    }
}
